### ISSUE TITLE
scroll to top on alert

### ISSUE THREAD

**Issue by frafu** [makeusabrew/bootbox#128]
Hi!

When I open a bootbox.alert window and the document is higher than the browser viewport, the document scrolls always to the top of the page.
Is there a way to avoid this behaviour?

The same problem is also described here:
http://stackoverflow.com/questions/12575222/bootbox-js-is-scrolling-the-window-up

regards
franz

**Comment by IsaacBruno** [comment]
$('.modal').animate({scrollTop:0}, 500, 'swing');
