### ISSUE TITLE
No option for default value in prompt

### ISSUE THREAD

**Issue by LukasFT** [makeusabrew/bootbox#143]
I have an idea - What if you made an option in the prompt, to set a default value? So the textbox that would popup, already was filled, but could be changed.

I couldn't figure out how to do it in a proper way, so I'm asking here if it is ok. 

Don't think you need this info, but I am running Bootstrap v2.3.0 and jQuery 1.9.1

**Comment by zcpefaisal** [comment]
I have fetching a problem in the prompt about input type date to set a default value. when i use input type text and set a default value in value property, it is working good. But when using input type date then set default value, it did not work. how can i set a default value with input type date when prompt showing popup.

Also another issue: In prompt date picker show in chrome browser, but in firefox browser date picker didnot working. 

I couldn't figure out how to do it in a proper way, so I'm asking here if it is ok.

**Comment by tiesont** [comment]
@zcpefaisal You really should post this as a separate issue, although it's not really a Bootbox problem.

Firefox does not have a native date-picker (as of version 54), even though it supports the type="date" input. Chrome (and probably Safari and/or Opera) expect date values to be in the `YYYY/mm/dd` format - anything else will cause the date input to (basically) ignore the value, at least when presenting the value in the UI.

**Comment by pinguin999** [comment]
Hi is it possible to set the default value text as selected text. So I can press enter if I want the default or can start typing if I want to override,
I think it's also browsers default behavior.

Thanks
