### ISSUE TITLE
Double scrollbar on browser when modal is called

### ISSUE THREAD

**Issue by markwienands** [makeusabrew/bootbox#145]
This occurs when styling the following:

html {
 overflow-y: scroll;  
}

This forces a permanent vertical scrollbar to the page.
A common practice used for websites to disable content re-positioning between pages with small content and large content. 

However, using this causes a double scrollbar to appear.

Any of you encountered this problem?

note: Bootbox 4.0 with bootstrap 3.0

**Comment by wqsaali** [comment]
just add this script if your bootstrap model have double scroll
this is the case if your css have html tag styling
$(function(){
  $(document.body).on('show.bs.modal', function () {
    $(window.document).find('html').addClass('modal-open');
  });
  $(document.body).on('hide.bs.modal', function () {
    $(window.document).find('html').removeClass('modal-open');
  });
});
this is the case if your css doesn't have html tag styling
$(function(){
  $(document.body).on('show.bs.modal', function () {
    $(document.body).addClass('modal-open');
  });
  $(document.body).on('hide.bs.modal', function () {
    $(document.body).removeClass('modal-open');
  });
});

**Comment by roydipti23** [comment]
https://github.com/reactjs/react-modal/issues/114

**Comment by tiesont** [comment]
@roydipti23 Not sure what you're trying to say, there. Is that supposed to be a fix for this issue? Bootbox doesn't supply any styles, so there's nothing we're doing that would cause double-scrollbars.

**Comment by roydipti23** [comment]
@tiesont yes its supposed to be a fix

The overflow property specifies whether to clip the content or to add scrollbars when the content of an element is too big to fit in the specified area.
So here we are having 2 scrollers, one of the main body and one of the modal. We only need modal's scroller; hence overflow: hidden
