### ISSUE TITLE
Custom Button Values For Confirm - How To?

### ISSUE THREAD

**Issue by Joyrex** [makeusabrew/bootbox#152]
I want to customize the button names/classes in a Confirm dialog, and from the code in the demos.js file linked in the main page, it looks possible, but when I try to pass the  button values in the confirm() function, it says I have too many arguments - is doing a Dialog the only way to specify these features? Here's my code I have for a working confirm - I'm just missing the customization I think should be possible:

```
$(document).on("click", "a[data-bb]", function(e) {
        e.preventDefault();
        bootbox.confirm("Are you sure you want to delete this Calendar Event. If not, click Cancel. There is no undo!", function(confirmed) {
            if (confirmed) {
                window.location = $("a[data-bb='confirm']").attr('href');
            } else {
                bootbox.hideAll();
            }
        });
    });
```

**Comment by AliLozano** [comment]
This should be in documentation.

**Comment by tarlepp** [comment]
@AliLozano yep it should really... Could you make PR to docs?

**Comment by yoeurn** [comment]
I want to change default focus button on confirm alert dialog from OK to Cancel. Who can help me please?
Here is my code...
///////////////////
<button class="btn btn-primary" type="button" onclick="confSubmit(this.form);">Send</button>
<script type="text/javascript">
    function confSubmit(form) {
    if (confirm("Are you sure you want to send reminder to guests?")) {
    form.submit();
    }else {
    //alert("You Decided Not Send Reminder To Guest...");
    }
    }

**Comment by yoeurn** [comment]
<button class="btn btn-primary" type="button" onclick="confSubmit(this.form);">Send</button>
<script type="text/javascript">
    function confSubmit(form) {
    if (confirm("Are you sure you want to send reminder to guests?")) {
    form.submit();
    }else {
    //alert("You Decided Not Send Reminder To Guest...");
    }
    }

**Comment by tiesont** [comment]
@yoeurn Please create a new issue. What you're asking is not related to changing the button text.

**Comment by tan1193** [comment]
i want to add more attr to button confirm and my code 

 ```
bootbox.confirm({
                message: data.Message,
                buttons: {
                    confirm: {
                        label: 'yes',
                        typeName: 'saveconfirm',
                        className: 'btn-success'
                      
                    },
                    cancel: {
                        label: 'no',
                        className: 'btn-danger'
                    }
                },
                callback: function () {
                    $('#frm').submit();
                }
            });
```
but it dosen't work. i do somethings wrong?

**Comment by tiesont** [comment]
@tan1193 Please create a new issue. What you're asking is not related to changing the button text.
