### ISSUE TITLE
Data attribute support

### ISSUE THREAD

**Issue by dam-scasi** [makeusabrew/bootbox#156]
Hi !

It would be great if we can do a button like this :
```
<button data-bootbox-confirm="Do you really want to submit this?"
        type="submit" class="btn">Submit</button>
```
And with no additionnal js, bootbox will automatically launch a confirm box with the text found in the data attribute on button click. And if we click OK in the confirm box, then continue (submit here), or if we click Cancel then abort.

Same for alert with for example data-bootbox-alert attribute.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
