### ISSUE TITLE
center bootbox vertically

### ISSUE THREAD

**Issue by PepeVasquez** [makeusabrew/bootbox#166]
I use the below script to automatically center any bootstrap modal I use in my web site, and it works fine, but it does not work with bootbox even though bootbox uses the 'modal' class. Is bootbox somehow overwriting the show event? If so, is there a work-around to vertically center bootbox? Thanks. 

$(".modal").on("show", function () {
    $(this).css({
        'top': '50%',
        'margin-top': function () {
            return -($(this).height() / 2);
        }
    });
});

**Comment by youradds** [comment]
This didn't work for me. For some reason it shifts the whole page down:

![broke](https://cloud.githubusercontent.com/assets/2000191/5973156/eabc3272-a85c-11e4-85a0-42b65750ffc0.jpg)

I then tried a different approach:

    $("body").on("shown.bs.modal", ".modal", function() {
        $(this).find('div.modal-dialog').css({
            'top': '50%',
            'margin-top': function () {
                return -($(this).height() / 2);
            }
        });
    });

...which kinda works - but not in Chrome for some reason:

![broke2](https://cloud.githubusercontent.com/assets/2000191/5973164/0fd532de-a85d-11e4-87bc-3b991e4a7471.jpg)

Any suggestions?

**Comment by cvsguimaraes** [comment]
Use the method suggested by @tarlepp but pay attention to the parent (probably the document `body`) positioning. Check if you used some `absolute` or `fixed` positioning.

**Comment by youradds** [comment]
Mmm nope, didn't have that. Its weird, as the modal-wrapper looks like it has scrollbars (but starting part way down the page)

Anyway, I managed to get it going with this "hacky" solution :)

    $("body").on("shown.bs.modal", ".modal", function() {
        $(this).find('div.modal-dialog').css({
            'margin-top': function () {
                var modal_height = $('.modal-dialog').first().height();
                var window_height = $(window).height();
                return ((window_height/2) - (modal_height/2));
            }
        });
    });

**Comment by diegomesata** [comment]
Hello, how could I get this on angular??

**Comment by tarlepp** [comment]
@diegomesata use directive for that.

**Comment by rasmuschristensen** [comment]
Just had this issue after I made a top fixed header. The fix I did was to add a css class in the bootbox config with a high z-index as in:

bootbox.dialog({
            className: "dialogFixedtop"......

and the class is 

 .dialogFixedtop {     
     z-index: 9999 !important;
 }

Also tried to move the top margin, but the shadow became an issue.

**Comment by IanIT** [comment]
Hi,
A little late to the party but the way I do it is 
 var box = bootbox.dialog({
,,,
});

    box.css({
      'top': '50%',
      'margin-top': function () {
        return -(box.height() / 2);
      }
    });

Hope this helps :)

**Comment by hamdiceylan** [comment]
thank you makeusabrew its worked for me.

**Comment by andysaini** [comment]
so what's the final solution?

**Comment by alexmahterian** [comment]
IanIT's comment worked for me.

**Comment by jneutronmatias** [comment]
Huy guys this would fix all guys :)

var box = bootbox.dialog({
 ....
});
dialog = box.find('.modal-dialog');
box.css('display', 'block');        
dialog.css("margin-top", Math.max(0, ($(window).height() - dialog.height()) / 2));

**Comment by shayanpaul91** [comment]
i did this by going to bootbox.js file and added a css in dialog:
var template ={
dialog:
'<div class='bootbox modal' tabindex='-1' role='dialog' style='padding-top:15%; overflow-y:visible;'>
...........
....

}
