### ISSUE TITLE
backdrop closing not functioning with default & 'backdrop: true'

### ISSUE THREAD

**Issue by nightbook** [makeusabrew/bootbox#177]
Hello,
Firstly thank you for this plugin, beautifully done I'm replacing all my modal handling with bootbox.
I found one annoyance which had me amend the code for my purposes, simply to have the dialog operate similar to the original bootstrap modal.
I tried to leave the default and even specify 'backdrop: true' as indicated on the website but found clicking out of the modal didn't close it.

Delving into the code I found 'backdrop: true' is being disallowed completely;
```
    // we only support Bootstrap's "static" and false backdrop args
    // supporting true would mean you could dismiss the dialog without
    // explicitly interacting with it
    options.backdrop = options.backdrop ? "static" : false;
```
Note: Working with Bootbox 4.1.0

I understand the comment indicating it's disabled to force the user to select an option, which makes sense if Cancel/Close isn't one of the options provided and a response is required necessary.
99% of my current use-cases however provide Cancel as an option which simply closes the model. This cancel option I'd like to be available through several means; Cancel Button, Close (x) Modal Header Button, Esc and clicking out of the modal. All but the last is available with the final one being disallowed only by bootbox.

I believe I saw a comment suggesting a .modal() functionality, which ok I see that, but all I see is maybe have the default for backdrop be false or static for dialog response requirement but still allow backdrop:true so as not to disallow standard modal functionality.

If anyone else finds they need to re-enable the backdrop click to close ability (backdrop: true) simply comment/remove the following code:
bootbox.js
```
options.backdrop = options.backdrop ? "static" : false;
```
bootbox.min.js
```
a.backdrop=a.backdrop?"static":!1,
```
* You can either not provide the backdrop option in your call which would default it to true, or you can specify it 'backdrop: true'.

Just wanted to share my thoughts/use-case.
Thanks

**Comment by pribilinskiy** [comment]
@HaNdTriX solution works fine

**Comment by makeusabrew** [comment]
This made it in to 4.4.0 :)
