### ISSUE TITLE
Occasionally .modal-dialog doesn't fill full .bootbox.modal container

### ISSUE THREAD

**Issue by nightbook** [makeusabrew/bootbox#178]
I'm having an odd and sporadic issue, it only came to my attention once I styled the modals but I've tested unstyled to replicate and ensure it's not the css I introduced.

When consecutively opening a modal after the 3rd, sometimes 4th/5th/6th/etc., time it loads with a slight margin on the .modal-dialog (or a padding on the .modal depending on how you look at it.
I've tested with standard bootstrap modals without causing the issue.

I can't delve into it through inspect sadly as each time I select an element in the .modal in inspector the issue corrects itself. I was able to take a screenshot of the issue while inspecting and hovering on the .modal-dialog to show the margin/padding.
![Styled Modal](https://f.cloud.github.com/assets/670280/1481310/83fdccb0-46c6-11e3-9b55-f081a14d734f.png)
*And another screen showing it works with the default bootbox theme.
![Unstyled Modal](https://f.cloud.github.com/assets/670280/1481311/83ff103e-46c6-11e3-8ea1-9e585f99f232.png)

Any help with this would be greatly appreciated, not a HUGE issue but definitely a nuisance and aesthetically detrimental.
Much appreciated.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
