### ISSUE TITLE
Hiding a modal removes components wired to modal's fields

### ISSUE THREAD

**Issue by jpa00** [makeusabrew/bootbox#179]
If I have for example a jqueryUI datepicker attached to an input field inside a dialog, it works as expected when the dialog is opened for the first time. However, when the dialog is opened for the second time, the datepicker no longer functions. This seems to be due to Bootbox calling dialog.remove() on the hidden.bs.modal-event. Removing the handler for this event appears to fix the issue and allow the datepicker to work correctly.

Using Bootbox 4.1.0, Bootstrap 3.0.0 and jQuery 2.0.2

**Comment by floriancargoet** [comment]
I like to reuse dialogs too, thanks @jpa00 for the tip.
