### ISSUE TITLE
Can support for radio button groups be added? 

### ISSUE THREAD

**Issue by CrankyDragon** [makeusabrew/bootbox#189]
I got it working on my by adding a case for radio where ever I saw checkbox, and adding:
```
radio:
        "<div class='radio'><label><input class='bootbox-input bootbox-input-radio' type='radio' /></label></div>",
```
and
```
if( typeof option.name !== 'undefined' ) {
    checkbox.find("input").attr("name", option.name);
}
```
In the checkbox render loop, so the following would work:
```
bootbox.prompt({
				message : "Select prompt", 
				title    : "Select prompt",
				inputType : 'radio',
				inputOptions : [
					{ text : 'yay', value: 'yay', name: 'yay_group'},
					{ text : 'nay', value: 'nay', name: 'yay_group'},
				],
				callback : function(blah) {
					console.log(blah)
				}
			});
```

http://jsfiddle.net/Uv38G/2/

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
