### ISSUE TITLE
Issue with bootstrap-modal-bs3patch.css library and Bootbox

### ISSUE THREAD

**Issue by rogertcd** [makeusabrew/bootbox#200]
I have been trying work with Bootbox and modals at the same time, but when I load "bootstrap-modal-bs3patch.css" library in the same file the Bootbox dialog appears weird, see the next screen
![issue](https://f.cloud.github.com/assets/6172810/1736968/172cd114-636b-11e3-8fc9-69e651b75ccb.PNG)

Could you please help me with it?

**Comment by markormesher** [comment]
menacestudio's solution didn't work for me, so instead I came up with this (very hacky) fix:

I renamed `.modal` to `.modal-fix` in bootstrap-modal-bs3patch.css, then added this to the `init` method in modal.js:

```
if (!this.$element.hasClass('bootbox')) {
    this.$element.addClass('modal-fix');
}
```

Modals and Bootbox are now working beautifully together :)

**Comment by ThaDafinser** [comment]
@markormesher your hack worked.

But i also needed to adjust the backdrop z-index
```
baseIndex['backdrop'] = baseIndex['backdrop'] - 1;
```

**Comment by AnasSafi** [comment]
markormesher Thank you very much...

**Comment by dipan66** [comment]
Worked like a charm - thank you @markormesher and @ThaDafinser both. Just an addition for those who may be wanting to know where to add  @ThaDafinser's change  - it has to be added inside bootstrap-modalmanager.js, in the getzIndex function.

**Comment by RokSiEu** [comment]
I just had to use @menacestudio solution with one additional css
```
.modal.bootbox .modal-dialog
{
    width:auto;
}
```

because otherwise it will conflict with bootstrap rules for max width of modals.

**Comment by cunhanohaole** [comment]
Worked perfectly! Thank you!!!

**Comment by Xiao-Ai** [comment]
@markormesher Thanks!

**Comment by hlwz5735** [comment]
Thanks you all!

**Comment by sinceq** [comment]
@markormesher Thanks!

**Comment by palashmon** [comment]
Thanks @menacestudio & @RokSiEu :+1:

**Comment by liangzhongzhuang** [comment]
Thank you very much! Your solution works beautiful! @markormesher

**Comment by gajendra7590** [comment]
Not Working

**Comment by tiesont** [comment]
Bootbox doesn't have it's own stylesheet. If loading another library causes issues with Bootbox modals, you need to take that up with _that_ library. 

Locking this.
