### ISSUE TITLE
Can you add setLocales() public method to bootbox?

### ISSUE THREAD

**Issue by dmarko484** [makeusabrew/bootbox#206]
Would be possible to add public setLocales() method to bootbox to allow to set alternative locales for special usage? As an example is the confirm box with Yes/No buttons instead of OK/Cancel . Maybe this could be part of  'options' ?

e.g.
```javascript
bootbox.setLocales({
en : {
      OK      : "YES",
      CANCEL  : "No",
      CONFIRM : "Yes"
    }
}
)
```

**Comment by makeusabrew** [comment]
Available in 4.4.0 :)
