### ISSUE TITLE
Add minified JS to bower repo

### ISSUE THREAD

**Issue by avp** [makeusabrew/bootbox#208]
It would be immensely helpful if you could add `bootbox.min.js` to the bower repo, so we don't have to install a bunch of node modules and run grunt uglify just to get a minified version.

**Comment by samuelfac** [comment]
+1 for this

**Comment by migig** [comment]
+1

**Comment by ArturFormella** [comment]
+1

**Comment by pmaselkowski** [comment]
Keeping minified files in dist folder makes it easier to use too, as it's popular practice - so one using package knows what files should be included clearly. 

And you could add dist folder to ignored list in your IDE to not clutter project.
