### ISSUE TITLE
Close dialog on backdrop click?

### ISSUE THREAD

**Issue by amerikan** [makeusabrew/bootbox#210]
I had never used bootbox until now. I saw that there's an option called `backdrop` which I thought would behave like the one in bootstrap (http://getbootstrap.com/javascript/#modals-usage), but it doesn't, though they share the same name. 

I'm trying to allow the dialog to close whenever the back drop is clicked. Is it possible?

**Comment by brunjick** [comment]
When there is multiple classnames
```
$(document).on('click', '.bootbox', function(){
    var classname = event.target.className;
    classname = classname.split(' ').join('.')

    if(classname && !$('.' + classname).parents('.modal-dialog').length)
        bootbox.hideAll();
});
```

**Comment by Maidomax** [comment]
Y'all forgot tho get a reference to the event object
```
$(document).on('click', '.bootbox', function(){
    var classname = event.target.className;
    classname = classname.replace(/ /g, '.');

    if(classname && !$('.' + classname).parents('.modal-dialog').length)
        bootbox.hideAll();
});
```
