### ISSUE TITLE
How to escape on 'click away'

### ISSUE THREAD

**Issue by optikalefx** [makeusabrew/bootbox#217]
Is there a way to do this? I don't see any option for it.
Thanks.

**Comment by MaicolBen** [comment]
+1

**Comment by makeusabrew** [comment]
Hi all,

Apologies; I've been on vacation for the past 3 weeks and have a rather large backlog of issues to get through. I'm equally keen to get this feature in; I just need to find the time.

Nick

**Comment by makeusabrew** [comment]
All,

This is now in progress. Will hopefully have a 4.4.0 release out within a week.

**Comment by makeusabrew** [comment]
Fixed in 4.4.0 released last week
