### ISSUE TITLE
allow both "title" and "message" property for prompt dialogs

### ISSUE THREAD

**Issue by lsloan** [makeusabrew/bootbox#230]
prompt dialogs currently ignore the "message" property.  Please update prompt dialogs to show any given message just before the input field.

**Comment by lvostinar** [comment]
We also need this. Can you merge my commit ?

**Comment by tarlepp** [comment]
@lvostinar please make pull request and read contributin guide, that will need some tests before we can approve that PR.

**Comment by lvostinar** [comment]
Created pull request, tests are ok.

**Comment by tarlepp** [comment]
@lvostinar with tests I ment that you need to write some for this new feature.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
