### ISSUE TITLE
Bootstrap .modal-open being left on body

### ISSUE THREAD

**Issue by chrissexton** [makeusabrew/bootbox#232]
I have a site with the latest Bootbox (4.2.0) and Bootstrap (3.1.1). These were recently upgraded from 4.1.0 and 3.1.2 to confirm the issue.

When I call bootbox.confirm/alert/etc., the modal-open class is being left on the body of the page when the Bootbox is dismissed. As a hack to test my theory, adding a quick $('.modal-open').removeClass('modal-open') to the two spots in Bootbox where the hide method is called works great, but I'd rather not be so hacky. 

I haven't seen anything obvious in the Bootbox code that would lead to the issue, and it may just be a Bootstrap issue, but I wanted to run it by here first. Bootstrap modals work just fine on the same pages in separate tests. I verified that there was only one modal open at any given time.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
