### ISSUE TITLE
Namespacing support

### ISSUE THREAD

**Issue by cworsley4** [makeusabrew/bootbox#234]
With LESS and SASS, we can add a name space to bootstrap, but currently I don't see a way to solve this with Bootbox without editing the source.

**Comment by sabl0r** [comment]
I'm searching for the same functionality. I put bootstrap into a scope (.bs) to avoid it to override my own styles.

The desired result would be something like this:
```
<div id="#bootbox-container" class="bs">
... bootbox code ...
</div>
```

Two suggestions for how bootbox could provide this:
* Let the user specify a jQuery selector, which points to the target wrapper element: `wrapper: '#bootbox-container'`. The developer has to make sure, that the wrapper element is at the right position in the DOM (before `</body>`).
* Let the user specify a CSS class name, create the wrapper element by yourself and add the provided class name to it: `wrapperClassName: 'bs'`

Or maybe even both ;)

What do you think about it? Would this even work? Is it something you would consider adding?
If you do, I could try to find some time and create a pull request. I didn't look into the code yet, so no idea how complex it would be ;)

**Comment by sabl0r** [comment]
Ok. I should have digged into the code first. There is already a `container` option :-)

Unfortunately the backdrop isn't added to this container, but this is related to bootstrap itself.
To deal with that, I'm using `$('body').on('shown.bs.modal', function(){ $('#bootbox-container').append($('.modal-backdrop').remove()); });` to dynamically move the backdrop element to my container element.

I think you can close this issue.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
