### ISSUE TITLE
Option to make bootbox synchronous

### ISSUE THREAD

**Issue by pennstatephil** [makeusabrew/bootbox#244]
First: Love the library, and use it/evangelize it often.

That said, is there _any_ possible way (maybe using jQuery promise or something else) to provide a synchronous option for bootbox dialogs that require user responses (confirm/prompt)? It would save me a lot of heartburn in situations where I need it.

**Comment by pdorgambide** [comment]
+1. The `bootbox.confirm` is asynchronous, and could be awesome that allow configure or has a specific method that make synchronous, i.e. the same behaviour of `window.confirm` to allow block event propagation until the user confirm the action. 
This behaviour allow use `bootbox.confirm` for use case as to exit from one form before save the changes once time the user press the browser back button

**Comment by asdfghjkl777** [comment]
asynchronous bootbox.confirm is not a solution for the real world. I supposed we will have to nest calls or something to make it work.
