### ISSUE TITLE
`undefined is not a function` when using from bower install

### ISSUE THREAD

**Issue by joseym** [makeusabrew/bootbox#253]
Just installed the plugin from bower, when trying to use `bootbox.alert('guess what?!', callback(){ console.log('alerted'); })` I get the following error.

~~~
TypeError: undefined is not a function
    at Object.exports.dialog (http://localhost:5000/assets/bower_components/bootbox/bootbox.js:699:12)
    at Object.exports.alert (http://localhost:5000/assets/bower_components/bootbox/bootbox.js:320:20)
~~~

**Comment by jtan743** [comment]
@brenwell did you manage to fix your problem with the uncaught typeerror? because im getting that error aswell and im not sure whats wrong, i have included both dependencies (jquery and bootstrap js) they are being loaded in the right order but im still getting that error

**Comment by brenwell** [comment]
@jtan743 No sadly I never got it working, The probelm I had was that the jquery object being passed to bootbox has not been extend by bootstrap, and therefore didn't have the `$.fn.modal` object. To patch this I ended up editing the library, getting jquery from the window instead.

```javascript
}(this, function init($, undefined) {
  $ = window.$
  ...
```

I have no idea why this was happening and I didn't have the time to work it out. If you ever solve it, please let me know.

**Comment by KseniaBel** [comment]
I had exactly the same problem as @brenwell ... and most probably as the rest of the guys here ... and I had to modify the library by adding $ = window.$ at the place I had an exception. 

I've downloaded my bootbox via bower install and manually imported it in my index.html. I use jQuery version 2.2.2 and bootstrap version 3.3.6

**Comment by brenwell** [comment]
Never got it sorry, sometimes it worked sometimes not

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
