### ISSUE TITLE
Invalid argument length when specifying "Cancel text" in confirm

### ISSUE THREAD

**Issue by juancresc** [makeusabrew/bootbox#256]
This code is giving me "Uncaught Error: Invalid argument length"
$(".cancel").click(function(){
        bootbox.confirm("Salir?", "Cancelar", function(result) {
            if(result){
                window.location.href = "index.php";
            }
        }); 
    });

According to the docs this would be OK:

bootbox.confirm(str message, str cancel, fn callback)

**Comment by batu19** [comment]
Thanks tarlepp :+1:
