### ISSUE TITLE
Add option to disable focus on submit button

### ISSUE THREAD

**Issue by ramon18** [makeusabrew/bootbox#260]
If the parent page needs vertical scroll to show the modal, it causes an awful effect and automatic scroll on the page to focus the button.

**Comment by junkiepipes** [comment]
to remove focus, I just commented: 

dialog.on("shown.bs.modal", function() {
      dialog.find(".btn-primary:first").focus();
});

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
