### ISSUE TITLE
Disabling spellcheck

### ISSUE THREAD

**Issue by dsoprea** [makeusabrew/bootbox#262]
Ordinarily, an input can take an attribute like the following to disable spell-checking under Chrome (and maybe other browsers):

```
spellcheck="false"
```

I took a quick look, but didn't see a straightforward way to do this in Bootbox, nor any other threads discussing it. Is there a solution for this?

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
