### ISSUE TITLE
A href option than using callback

### ISSUE THREAD

**Issue by bluee** [makeusabrew/bootbox#275]
Would it be possible to have buttons as 'a href' as an option rather than using callback?

In many scenarios you want the user to go to another page like this:

    <a href="page2.html" class="btn btn-success">Button</a>

But currently it doesn't seem possible. The only way which is not as effective is this:

                 main: {
                        label: "Button",
                        className: "btn-success",
                        callback: function () {
                            window.location.replace('page2.html');
                        }
                    }

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
