### ISSUE TITLE
Style problem

### ISSUE THREAD

**Issue by d33d** [makeusabrew/bootbox#278]
There are display problems using bootbox with other plugins such as bootstrap-modal version that has a custom css that overrides the style ".modal" 

Do you think that it is useful to find a solution for this kind of situations? by the way.. there is a solution ... I do not know? :) 

Could be useful have the possibility to overwrite the base dom structure hardcoded in the var templates

**Comment by sahinyanlik** [comment]
Hello is there any way to fix this problem ?

**Comment by tarlepp** [comment]
Could someone first provide eg. plunker example of this problem?

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
