### ISSUE TITLE
Monthpicker doesn't work on Bootbox

### ISSUE THREAD

**Issue by MaicolBen** [makeusabrew/bootbox#281]
The plugin of jQuery Monthpicker (https://github.com/lucianocosta/jquery.mtz.monthpicker) doesn't work on bootbox modals, but yes in Bootstrap Modals, i can't use the dropdown generated in the plugin because dissapear (in Firefox). Maybe the modal block dropdown in the popup of the Bootbox modal?
This is a example http://jsfiddle.net/eaXVU/

Thanks and good work!

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
