### ISSUE TITLE
Add option to switch button order on non-dialog bootboxes

### ISSUE THREAD

**Issue by dennisbaskin** [makeusabrew/bootbox#293]
Currently, as of the latest release, it is impossible to specify button order on anything other than dialogs. Since "cancel" and  "confirm" are always added in an array and in an alphabetical order, It is extremely difficult to make modifications.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
