### ISSUE TITLE
Add button customization / internationalization option

### ISSUE THREAD

**Issue by IcarusHU** [makeusabrew/bootbox#294]
We'd like to customize the buttons of bootbox alert and confirm windows. In earlier versions, internationalization was an option at initialization of the plugin, where one could add compliances for general buttons, such as Ok, Cancel.
But in the latest version (which we really need - so we cannot go back to earlier version) it's missing. Because of this we should create a more complicated custom dialog in order to use translations on confirm dialogs, which, I think a bit over the top workaround :).

I'm thinking about the opportunity to add button texts in the second options parameter, where you can override predifined button text, like this:

bootbox.confirm(
      "Are you sure?",
      {
           "button_ok" : "Alright",
           "button_cancel": "No way..."
      },
      function(result) {
           Example.show("Confirm result: "+result);
      }
); 

thank you :)

**Comment by klikin** [comment]
soon ...

**Comment by makeusabrew** [comment]
Hi all,

Apologies; I've been on vacation for the past 3 weeks and have a rather large backlog of issues to get through. I'll try and look at this and have a think about 4.4.0 soon.

Nick

**Comment by makeusabrew** [comment]
Available in 4.4.0 with `addLocale`, `deleteLocale` and `setLocale`
