### ISSUE TITLE
Content not clickable on android browser

### ISSUE THREAD

**Issue by gregorgodoy** [makeusabrew/bootbox#308]
Hi,

Great library! I found a problem with this library. All clickable elements (input, buttons, etc) are not working on android browser 4.x. To reproduce this issue, please open the main page http://bootboxjs.com/ with android browser, then scroll down untill the prompt dialog button and click it.
Try to click the input element, or try to click the buttons, they are not listening the clicks.

This only occurs with android native browser, works fine on chrome and firefox for android. You can replicate this problem if you open the boostrap page, open the modal examples and try to click the inputs or buttons. http://getbootstrap.com/javascript/#modals

But the problem disapears when yo scroll the background to the top of the page. Magically all clicks are working fine again. It seams like android browser has a issue with clickable elements inside fixed containers (div) when they dont are located at the top of the page. I try to fix that scrolling programatically the window to the top when the dialog was opened

window.scrollTo(0,0);

This fix works, but is not exactlly what i want. Modal should be opened and working in the current scrolled position. Sorry for my poor english, hope it was understood. Any fix for this issue?! THANKS!

**Comment by makeusabrew** [comment]
Sorry for bringing this old issue up. As noted in it, this occurs on the Bootstrap site too so not something which falls under Bootbox's remit to fix.

Thanks!

Nick
