### ISSUE TITLE
Bootbox can't scroll modal on mobile browser

### ISSUE THREAD

**Issue by chanx** [makeusabrew/bootbox#309]
When using android browser or chrome, we cannot scroll on the long modal that call by bootbox. it works okay on usual bootstrap modal. do you know how to fix it? thanks

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
