### ISSUE TITLE
Npm package  update

### ISSUE THREAD

**Issue by PeterDaveHello** [makeusabrew/bootbox#310]
Hi there, 

I'm Peter from cdnjs.com, I found that there is a npm package of this lib here https://www.npmjs.org/package/bootbox, but didn't update for a long time.

The package owner seems to be @defunctzombie, I want to ask @defunctzombie, can can/would you update for it?

Thanks a lot!

**Comment by makeusabrew** [comment]
Although this came first, #358 is more active so closing this for cleanliness.
