### ISSUE TITLE
z-index issue

### ISSUE THREAD

**Issue by caleb87** [makeusabrew/bootbox#311]
I'm working with modals and other windows that are hiding the bootbox. Is there a clean way to customize to z-index or set it to maximum?

**Comment by kofifus** [comment]
It would be really useful to add a z-index to bootbox. it is often the case that one wants to show a bootbox on top of another bootstrap modal

**Comment by tarlepp** [comment]
actually bootstrap itself doesn't support that so, imho isn't bootbox scope to handle.

**Comment by kofifus** [comment]
issue is you have a bootstrap modal and you want to show a prompt above it ... would be useful to have a simple way to do this rather then changin a global css such as .bootbox.modal
