### ISSUE TITLE
Problem with overflow for body

### ISSUE THREAD

**Issue by phoenix3008** [makeusabrew/bootbox#313]
1. Click "Open modal"
2. Is scroll working for bootbox dialog? - Yes
3. Click "Open modal - 2" 
4. Close the opened alert. There remained first modal dialog
5. Is scroll working for bootbox dialog? - No!!! Its working only for body... Not for bootbox dialog

http://jsfiddle.net/kxokmxdg/ check this out

**Comment by giolvani** [comment]
I have this issue also, and I think bootboxjs should fix it, because this feature is not supported by bootstrap as show this thread https://github.com/makeusabrew/bootbox/issues/356.

**Comment by giolvani** [comment]
I have suggested a fix for this issue https://github.com/makeusabrew/bootbox/pull/375

I hope be helpful!

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
