### ISSUE TITLE
How to change locale?

### ISSUE THREAD

**Issue by mabasic** [makeusabrew/bootbox#320]
Well, I am really puzzled.

How do you change the locale for `bootbox.confirm` ?

**Comment by Mithgol** [comment]
Documentation currently says that `locale` property can be set in an individual dialog's options (instead of global defaults).

However, such setting does not seem to have any effect on `confirm`.

Is it the same issue or should I open a separate issue?

**Comment by tiesont** [comment]
@Mithgol I would open a new issue, but yes, it appears that the docs for locale are wrong. You can change the locale (without setting the default locale) using `setLocale`, like so:
```
bootbox.setLocale('de');
bootbox.confirm('Sprechen sie Deutsch?', function(result){ 
    /* Buttons will be "Abbrechen" and "Akzeptieren" */ 
});
```
