### ISSUE TITLE
remove scrollbar in iframe

### ISSUE THREAD

**Issue by Se0ng11** [makeusabrew/bootbox#323]
when use inside iframe, a scrollbar will appear, any way to remove it or prevent it appear? currently now i add this to remove the scrollbar, hopefully in next version will cater this matter
$('.bootbox.modal').css({ "overflow-y": "hidden" });

![aler](https://cloud.githubusercontent.com/assets/2733646/4485973/7569ff60-49d7-11e4-9dd0-ec29fb822004.PNG)

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
