### ISSUE TITLE
Wait until modal closed before showing scroll bar

### ISSUE THREAD

**Issue by justin-hackin** [makeusabrew/bootbox#330]
On the demo page, when I click something to close the dialog, the scroll bar gets shown right away, causing the dialog to jump to the left before it zips up.  It would be nicer if you waited until the dialog was closed to reshow the scroll bar

**Comment by makeusabrew** [comment]
Hi @justin-hackin,

Sorry for bringing up this old issue; doing some house keeping. The scrollbar behaviour is completely determined by Bootstrap rather than this project so as such going to close this.

Thanks,

Nick
