### ISSUE TITLE
Use title instead of body for alert and confirm messages.

### ISSUE THREAD

**Issue by lipis** [makeusabrew/bootbox#334]
I think they are too small and it looks nice with the prompt so why not having it the same style for all.

**Comment by makeusabrew** [comment]
You're all correct; putting the alert and confirm text in the `title` would be better. I'll have a think about whether this constitutes a breaking change or not which will affect whether it makes 4.4.0 or not.

**Comment by tarlepp** [comment]
Imho there should be option to set both for alert and confirm. Sometimes I'm using loooong texts on that message, so that won't fit on the title.

**Comment by makeusabrew** [comment]
True. I'm conflicted as to how this would work though; your suggestion in this thread makes sense but opens up the possibility of setting a `title` *and* `message` on an alert/confirm - maybe okay?

**Comment by tarlepp** [comment]
Imho that's also good, because then you could set some "common" title for all "similar" alert / confirm boxes and just change the actual message. So basically three choices:

1) Only title
2) Only message
3) title + message

Default choice would be 1st (only title). Perhaps there should be different syntax for this too. Like:

```bootbox.alert(title, [callback|message], [callback])``` 

And of course object as a parameter where those variables are determined.

What do you think?

**Comment by makeusabrew** [comment]
I don't really want to go too far down the route where different arguments can be different properties - that used to exist in version prior to 4.x and turned into a mess. It also makes it more difficult for the scenario you mentioned where you want lots of body text but no title; you'd have to call:

`bootbox.alert(null, "my long body message here", [callback])`.

Off the top of my head, I think I'd prefer to keep the arguments as they are, but simply allow users to choose `title`, `message` or both when using the object form. This keeps things as backwardly compatible as possible but allows more flexibility with relatively little effort, so could be bumped into 4.4.0. So:

`bootbox.alert("foo");`
`bootbox.alert({message: "foo"});

Will still populate the body, 

`bootbox.alert({title: "foo"})`

Will populate the title, and

`bootbox.alert({title: "foo", message: "bar"})`

Will populate both. Sound alright?

**Comment by lipis** [comment]
I would just argue that the default if nothing else implied should be the title and if two params it should be the message or provided with the arguments..

```
bootbox.alert("foo");           bootbox.alert({title: "foo"});
bootbox.alert("foo", "bar");    bootbox.alert({title: "foo", message: "bar"});
bootbox.alert(null, "bar");     bootbox.alert({message: "bar"});
```

And if  you are about to change the version it doesn't matter if it will break (or more accurate just change the layout) a bit..

Either case it's really annoying to write the object every time that you want to alert and you know that it should be the default..

**Comment by makeusabrew** [comment]
Need to fix the issue of having no `.modal-body` causing the margins from the header and the footer to overlap (which comes from Bootstrap, not Bootbox) but will try and get this in for 4.4.0 (#300)

**Comment by makeusabrew** [comment]
This didn't make 4.4.0 but will hopefully get it into the next patch release :)

**Comment by migig** [comment]
+1 to this feature

**Comment by gbreeze** [comment]
+1

**Comment by mumairanwaar** [comment]
how to change title class such as danger, success or info ??

**Comment by tiesont** [comment]
@mumairanwaar You can't do that directly via the options. You can use a few different routes to accomplish what you're after:

Use HTML for the title, like so:
```
bootbox.alert({ 
    title: '<span class="text-danger">Something serious!</span>', 
    message: 'Your message here' 
});
```
Modify the modal's markup after it's been created:
```
bootbox.alert({ 
    title: 'Something serious!', 
    message: 'Your message here' 
})
.find('.modal-title')
.addClass('text-danger');
```
Add a custom class to the modal, and then style appropriately:
```
bootbox.alert({
    title: 'Something serious!',
    message: 'Your message here',
    className: 'serious-title'
});
```
All of these are demoed here: https://jsfiddle.net/yc8yt3Lk/

**Comment by mumairanwaar** [comment]
Thanx @tiesont  Very clean demo with code thanx  I just used second option to change header class


`
bootbox.alert({ 
    title: 'Something serious!', 
    message: 'Your message here' 
})
.find('.modal-header')
.addClass('alert-danger');
`

**Comment by tarlepp** [comment]
@lipis take a look about @tiesont solution, I think that is what you're looking for. Close the issue if this is solving your issue - otherwise provide more information about your use-case.

And many thanks to @tiesont for excellent solution + demo.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
