### ISSUE TITLE
Get rid of the localisation from the main file

### ISSUE THREAD

**Issue by lipis** [makeusabrew/bootbox#335]
I understand that at the moment is not much, but it would be nice to have that in a separate file anyway.

These days more and more people are using bower and it's included in the buildscript, so editing that file is kind of out of question on production, but if it was in a separate file would be much easier to deal with your own localisation.

Or have two files.. one that has it and one that doesn't like Moment.js is doing it http://momentjs.com/

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
