### ISSUE TITLE
Incorrect brazilian translation

### ISSUE THREAD

**Issue by lfbittencourt** [makeusabrew/bootbox#344]
I wonder if people complained about it before, but it's still in the source, so... Brazilian portuguese for CONFIRM can be "Confirm" or "OK", never "Sim" (which is "yes" in English).

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
