### ISSUE TITLE
Callback and input focusing issues

### ISSUE THREAD

**Issue by ray73864** [makeusabrew/bootbox#345]
Trying to do a Bootbox comfirm dialog and for the most part it works perfectly.

The issue i'm having however is that if the person presses the 'cancel' button i want it to put the focus back onto a text box and that part never happens at all.

```
$("#myButton").on("click", function(e) {
  bootbox.confirm("Some text", function(result) {
    if ( result ) { window.location = mypage.html; }
   else { $("#textbox").focus(); }
  });
  return false;
});
```
If i switch it out for an ``` alert (result); ``` it shows the alert box, console.log has the same effect, i just can't seem to get it to focus back to a text box.

**Comment by wilsonrg** [comment]
Create a generic function to focus without repeating the code.

This example is for the bootbox alert, for others (confirm, etc ...) just adapt the code:

    <script>
    $(function(){
    	$('#btnAlerta').on('click',function(){
    		falert('modal title','message you want to view','#nome');
    	});
    });
    function falert(tit,msg,obj){
        var box = bootbox.alert({
            size: 'small',
            title: tit,
            message:'<p>'+msg+'</p>'
        });
        box.on('hidden.bs.modal',function(){
            $(obj).focus();
        });
    }
    </script>

    <input type="text" id="nome" name="nome" />
    <button type="button" id="btnAlerta">Alert</button>
follows the example in practice
[https://jsfiddle.net/marsites/tLwo253e/](https://jsfiddle.net/marsites/tLwo253e/)
