### ISSUE TITLE
Couldn't get bootbox from dependency manager like bower or composer

### ISSUE THREAD

**Issue by adiramardiani** [makeusabrew/bootbox#355]
I used bower or composer to get bootbox, but now code "bower-asset/bootbox": "~4.3.0", is no longer valid

**Comment by nnmer** [comment]
even doing "bootbox.js": "~4.3.0" also says that not found

**Comment by tarlepp** [comment]
have you tried ```bootbox``` like it's listed on bower pages http://bower.io/search/?q=bootbox ?

**Comment by tarlepp** [comment]
Also command ```bower search bootbox``` shows that.

**Comment by nnmer** [comment]
thanks, this works.
i was using the data from this repo bower.js, the name there was bootbox.js

**Comment by tarlepp** [comment]
Closing this now.
