### ISSUE TITLE
Calling bootbox with bootstrap 3 modal open makes bootstrap modal lose focus when bootbox gets closed

### ISSUE THREAD

**Issue by andrewbaker00** [makeusabrew/bootbox#356]
Open a bootbox dialog from inside a bootstrap modal. 

When closing that bootbox, the bootstrap modal loses focus and the scroll now scrolls the page behind the modal, and not the modal itself. (So scrolling scrolls the body, and not the modal itself).

Fiddle showing the problem:

http://jsfiddle.net/q6gh9zu8/

**Comment by nishant-befree** [comment]
box.on('hidden.bs.modal', function (e) {
if($('.modal.in').css('display') == 'block'){
        $('body').addClass('modal-open');
      }
    });


solve issue for body overflow /  scroll issue

**Comment by dschuett** [comment]
Sorry for being ignorant, but what does "box" refer to in the fix for this:

box.on('hidden.bs.modal', function (e) {
if($('.modal.in').css('display') == 'block'){
$('body').addClass('modal-open');
}
});

**Comment by solvedigital** [comment]
I was having some issues with this as I was using multiple modals constantly throughout my application.

I ended up going into **bootbox.js** and adding the following line to the end of the **processCallback function**.

    setTimeout(function(){
        var modal_count = $('.modal-dialog').length;
        if(modal_count > 0)
        {
            $('body').addClass('modal-open');
        }
        console.log('count' + modal_count);
    }, 500);

**Comment by wsyeager** [comment]
andrewbaker00 / nishant-befree, WHERE in the code do you place your solving for the overflow issue? If I'm using a bootbox dialog, WHERE do I place that code to solve the issue? 

Thanks in advance....

**Comment by nishant-befree** [comment]
please check below in main bootbox js change... not sure for all this work but mine project it works fine....

![image](https://cloud.githubusercontent.com/assets/6196479/10988880/8eb5991e-8466-11e5-8d51-27021f7b55f1.png)


/**
     * Bootstrap event listeners; used handle extra
     * setup & teardown required after the underlying
     * modal has performed certain actions
     */
```javascript

    dialog.on("hidden.bs.modal", function(e) {
      // ensure we don't accidentally intercept hidden events triggered
      // by children of the current dialog. We shouldn't anymore now BS
      // namespaces its events; but still worth doing
      if (e.target === this) {
        dialog.remove();
      }
      //Addded By Nishant
      //if (!dialog.isOpener) {
       //   $('body').addClass('modal-open');
      //} 
      if($('.modal.in').css('display') == 'block'){
        $('body').addClass('modal-open');
      }
    });

    /*
    dialog.on("show.bs.modal", function() {
      // sadly this doesn't work; show is called *just* before
      // the backdrop is added so we'd need a setTimeout hack or
      // otherwise... leaving in as would be nice
      if (options.backdrop) {
        dialog.next(".modal-backdrop").addClass("bootbox-backdrop");
      }
    });
    */
```

**Comment by hilbrink** [comment]
@nishant-befree  - that worked for me, thanks!

**Comment by anggalisdiyanto** [comment]
Worked for me too.
Please note, if we using Dreamweaver then it's editor would give us an alert if we must use` ===` but then it's not working. So, just use double equal '==' :
`if($('.modal.in').css('display') == 'block')`

**Comment by luthfidc03** [comment]
appreciate it man, help me a LOT

**Comment by lakagawa** [comment]
Thank you guys.
