### ISSUE TITLE
Distribute the latest bootbox version on npm

### ISSUE THREAD

**Issue by Spy-Seth** [makeusabrew/bootbox#358]
The last bootbox.js distributed on [npmjs.com](https://www.npmjs.com/) is the 4.0.0 version. Can you keep it updated ?

**Comment by rnicholus** [comment]
Any update on this?  Or perhaps can you, @defunctzombie, update the version on npm to 4.3?

**Comment by makeusabrew** [comment]
Sorry, I'll take care of it ASAP. Sometime this weekend at the latest.

**Comment by rnicholus** [comment]
Cool.  Thanks for all of your work on this project!

**Comment by makeusabrew** [comment]
Apologies; quite clearly last weekend came and went with no release. I'll absolutely, definitely, undoubtedly get this published this week... honest.

**Comment by makeusabrew** [comment]
Hi @defunctzombie,

As @Spy-Seth points out there are two packages on npm both owned by you; could you possibly please add me to the bootbox.js one (https://www.npmjs.com/package/bootbox.js) which is more up-to-date and appears to be the most commonly used one? Frankly you can probably bin the other one; it's extremely old and probably causes more confusion than it's worth. Cheers dude!

Nick

**Comment by defunctzombie** [comment]
@makeusabrew added.

Unless you specifically want to use the `.js` one I would update the non `.js` one since the js suffix is not really needed.

Whichever one you end up deciding to not use, I will just add a deprecation message via npm to indicate users should switch to the new one. We shouldn't delete it outright since it might break some people that are using it.

**Comment by makeusabrew** [comment]
@defunctzombie thank you!

Yeah, deletion is probably a bit hasty. Looking at the current `package.json` (which itself isn't even the latest version!) in my past wisdom I seem to have preferred bootbox.js as the package name; given that's the most up-to-date package on npm and most downloaded, I'll stick with that being the main one.

Much appreciated :)

**Comment by rnicholus** [comment]
Awesome!  Thanks a ton for publishing this.  I just pulled it in via npm.

**Comment by makeusabrew** [comment]
You're welcome - sorry to all for the delay.
