### ISSUE TITLE
Bootbox appears behind a PDF on IE 11

### ISSUE THREAD

**Issue by waynebrantley** [makeusabrew/bootbox#362]
Add an iframe on your page where the source points to a PDF.
Click a button to popup bootbox - and it will appear behind it.
(Make the pdf take up the browser page where the bootbox renders).
Found this...but unsure if fixable.
http://stackoverflow.com/questions/18846604/zindex-issue-with-pdf-indise-iframe-in-ie

**Comment by makeusabrew** [comment]
Hi @waynebrantley,

This is unfortunately a Bootstrap issue; as such you may want to raise it on their repo (https://github.com/twbs/bootstrap) and see if it's something which can be / has been fixed.
