### ISSUE TITLE
Problem with JQuery form and BootBox

### ISSUE THREAD

**Issue by mr-ocean** [makeusabrew/bootbox#369]
Hi friends, i've a problem when i try to send data through form. I've used BootBox for confirm dialog, before send data, but after i choose "OK", the data are not sent and the page not changing. Can you help me?
This is my code: 
[JQUERY]
![1](https://cloud.githubusercontent.com/assets/10356870/5586729/207a5ca0-90d8-11e4-8f37-4088288693ad.JPG)

[HTML]
![2](https://cloud.githubusercontent.com/assets/10356870/5586730/241c68bc-90d8-11e4-8dfc-aa6f7fcb734b.JPG)

Thanks and Happy New Year! :)

**Comment by mr-ocean** [comment]
I'm sorry but i don't understand. Can you give me an example?

**Comment by makeusabrew** [comment]
Hi @mr-ocean,

Your issue here is a jQuery one, not a Bootbox one. Your selector trying to submit the form is wrong; it should be `[name=modulo]` as currently it's trying to select an element type of `modulo` instead.
