### ISSUE TITLE
Cancel button in bootbox.prompt still performs callback.

### ISSUE THREAD

**Issue by bgunnink** [makeusabrew/bootbox#37]
I'm calling `bootbox.prompt`, which automagically generates a text input, an OK, and a Cancel buttons.  My expectations are that pressing `Cancel` should simply close the box without performing any more logic.  However, when using the latest version (2.3.1) of bootbox, pressing `Cancel` still fires the callback.  The normal close (x) button works as expected.  

Here's a pared down example of my code:

```
function deny() {

        bootbox.prompt("Enter a comment here.", function(result) {

           alert("This should not fire when pressing Cancel!")

        }, {
            "animate": false
        });

    }
```

**Comment by ajeetmalviya** [comment]
var dialog = bootbox.prompt({
            title: (templateId > 0) ? "Edit Template" : "Create Template",
            message: '<p><i class="fa fa-spin fa-spinner"></i> Loading...</p>',
            size: "large",
            callback: function(result) {
                if (checkForSignalTemplateContainsDuplicates() === true) {
                    showErrorBox(Translator.SignalsPleaseCheckForDuplicates);
                    e.preventDefault();
                    return false;
                }
                if (isValidDataRangeY1() === false ||
                    isValidDataRangeY2() === false ||
                    isValidDataRangeY3() === false) {
                    return false;
                }
                if (result != null) {
                    SaveYAxiesValues();
                }
            }

Here is my code, As soon as I cancel Modal is not getting closed kindly help. If returns true, it closes the model.

**Comment by tiesont** [comment]
Open a new issue, please.

**Comment by omidxan** [comment]
> I'm calling `bootbox.prompt`, which automagically generates a text input, an OK, and a Cancel buttons. My expectations are that pressing `Cancel` should simply close the box without performing any more logic. However, when using the latest version (2.3.1) of bootbox, pressing `Cancel` still fires the callback. The normal close (x) button works as expected.
> 
> Here's a pared down example of my code:
> 
> ```
> function deny() {
> 
>         bootbox.prompt("Enter a comment here.", function(result) {
> 
>            alert("This should not fire when pressing Cancel!")
> 
>         }, {
>             "animate": false
>         });
> 
>     }
> ```

please check result value, if was null == cancel button cliked if was empty string '' ok button with empty comment box clicked.

this worked for me.
