### ISSUE TITLE
Set prompt field as password?

### ISSUE THREAD

**Issue by nadeemja** [makeusabrew/bootbox#370]
Any way to set the input field on the prompt as type=password?

**Comment by nadeemja** [comment]
I know you can set custom html in message option. But, is there an easier way?

**Comment by tarlepp** [comment]
Sure just use ```inputType: "password"```

**Comment by nadeemja** [comment]
You. Are. Awesome. But you knew that already, didn't you? <3

**Comment by nadeemja** [comment]
You. Are. Awesome. But you knew that already, didn't you? <3

**Comment by tarlepp** [comment]
There is also possible to make different input prompts. Look at code at https://github.com/makeusabrew/bootbox/blob/master/bootbox.js#L49-L68 Going to close this one now.

**Comment by nadeemja** [comment]
Uhm, I've tried both of these:

    bootbox.prompt "Password?", (result) ->
      inputType: "password"

    bootbox.prompt "Password?", (result) ->
      inputs: "password"

I can't make it work. Perhaps I'm stupid... :(

**Comment by nadeemja** [comment]
This worked:
http://stackoverflow.com/a/21477259/1022059

**Comment by tarlepp** [comment]
I made example page for you http://jsfiddle.net/hcbkf/5/ this should help. Feel free to open again if any problems.

**Comment by nadeemja** [comment]
Thanks for helping me!

I'm trying to add a "forgot password" button to the prompt. Labeling the cancel button is a halfway solution, because clicking that button and clicking the X to close the modal yields the same result, namely, null. Any suggestions?

**Comment by tarlepp** [comment]
With prompt you cannot change those texts as you like - for now.

See that prompt uses ```cancel``` and ```confirm``` texts on those buttons. https://github.com/makeusabrew/bootbox/blob/master/bootbox.js#L385

If you really need to change those labels, just make normal dialog and attach buttons that you like to it.

**Comment by makeusabrew** [comment]
@tarlepp yet again, thank you *so* much for helping folks out with this one :)
