### ISSUE TITLE
Bootbox appearing behind the backdrop on latest Bootstrap

### ISSUE THREAD

**Issue by samppis** [makeusabrew/bootbox#371]
Does bootbox support the latest Bootstrap version (3.3.1)? I have a problem where the bootbox appears behind the backdrop and it can only be "fixed" by setting the backdrop option to false. If I remember right it worked just fine on a previous bootstrap version a while ago. Thanks for any help!

**Comment by makeusabrew** [comment]
Hi @samppis,

Honestly not sure - haven't tested it. If it proves incompatible that would be pretty frustrating! I'll try and find some time to check it out myself and let you know - a jsFiddle link or similar would help too!

**Comment by samppis** [comment]
Couldn't reproduce on jsFiddle so figured out it was an external css messing with the z-index. Sorry for a wrong alert.
