### ISSUE TITLE
Tagged version does not match bower.json version

### ISSUE THREAD

**Issue by cmwelsh** [makeusabrew/bootbox#372]
I noticed your last release gives a warning in Bower because the tag is wrong here:

https://github.com/makeusabrew/bootbox/blob/v4.3.0/bower.json

I would bump to 4.3.1 and re-release.

**Comment by makeusabrew** [comment]
Will fix this with the impending 4.4.0 release

**Comment by makeusabrew** [comment]
4.4.0 now available & on npm :)
