### ISSUE TITLE
Add "main" field to package.json so the module can work with Browserify

### ISSUE THREAD

**Issue by Mavann1988** [makeusabrew/bootbox#373]
Right now this module doesn't work with browserify. https://github.com/substack/browserify-handbook#how-node_modules-works 

Since there is no "main" field, browserify cannot resolve the path correctly. By adding "main: 'bootbox.js'" to the package.json file it will fix this issue.

**Comment by makeusabrew** [comment]
Will be part of 4.4.0 (#300)

**Comment by makeusabrew** [comment]
4.4.0 now available & on npm :)
