### ISSUE TITLE
Calling bootbox.dialog from within callback triggers scrolling bug in chrome

### ISSUE THREAD

**Issue by cwohlman** [makeusabrew/bootbox#376]
I've been running into [this bug](https://github.com/twbs/bootstrap/issues/13628) in my app. I'm not sure what's causing it but have created a reproduction which depends on bootboxjs.

http://embed.plnkr.co/7oLaRa9LUpwc7D0OSUJ3/preview

**Comment by cwohlman** [comment]
Note adding a setTimeout fixes this.

**Comment by boustanihani** [comment]
@cwohlman Is meteor-addons.js (https://github.com/cwohlman/meteor-bootboxjs/blob/master/meteor-addons.js) really needed for bootbox to work under meteor, for me bootbox seems to work fine even without.., could you please explain the need for the extra code and perhaps enable issues on your repo :)

```javascript
// Meteor specific addons to the bootbox.js object
bootbox.templateDialog = function(options) {
  var div = document.createElement("div");
  UI.insert(UI.renderWithData(options.template, options.data), div);
  options.message = div;

  var result = bootbox.dialog(options);
  result.on('done.bootbox.modal', function (e, data) {
    var callback = options.callback;
    if (_.isFunction(callback)) callback(data);
  });
  return result;
};
```

**Comment by cwohlman** [comment]
@boustanihani It's not necessary, but it certainly is very helpful. That allows meteor developers to use reactive templates in bootbox dialogs, and in fact to display any template as a dialog, I've used it extensively in my latest project.

Do you think it's related to this bug at all? **I don't think it's in the version of bootbox I used for the reproduction.**

**Comment by cwohlman** [comment]
@boustanihani Sorry, I didn't realize I had issues turned off!

**Comment by boustanihani** [comment]
No, I don't think it's related to this bug, I just posted here because issues were turned off :)

**Comment by makeusabrew** [comment]
Hi @cwohlman,

Although your example uses this library the issue exists with Bootstrap - is that right? (Just doing some housekeeping)

**Comment by cwohlman** [comment]
Yes, I wasn't sure what was causing the issue, but I'm sure it's a
bootstrap issue.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
