### ISSUE TITLE
don't scroll on the first bootbox when close the second (2 level popup)?

### ISSUE THREAD

**Issue by yuomtheara** [makeusabrew/bootbox#378]
I use bootbox in bootbox (2 level popup).
but the first bootbox can not scroll when the second is closed.
Pl help me.

**Comment by tarlepp** [comment]
Have you read Bootstrap modal documentation? http://getbootstrap.com/javascript/#modals That says fair clearly that multiple modals are not supported.

**Comment by yuomtheara** [comment]
Thanks.
