### ISSUE TITLE
Bootbox.alert() Runaway Modals

### ISSUE THREAD

**Issue by patinthehat** [makeusabrew/bootbox#380]
I was doing some testing for a project I am writing, and due to a bug (not related), `bootbox.alert()` was called repeatedly until it exhausted browser resources.  Should't there be some type of maximum number of dialogs that can be displayed at any given time to avoid situations like this?

**Comment by makeusabrew** [comment]
Hi @patinthehat,

Apologies; I've been on vacation for the past 3 weeks and have a rather large backlog of issues to get through. In any case, this is really something for users to cater for and code against if they feel the need to. Putting some sort of arbitrary detection of this sort of situation inside the core library doesn't make sense; pretty much *any* library or given snippet of code can be misused / abused and cause detrimental effects like this, and coding against every scenario is impractical.

Cheers,

Nick
