### ISSUE TITLE
Why doesn't submit a form in a bootbox dialog?

### ISSUE THREAD

**Issue by fellipeh** [makeusabrew/bootbox#381]
Hello, I have these code:

```javascript
function exec_new($url_add) {
            jQuery.ajax({
                type: 'GET',
                url: $url_add,
                success: function (data) {
                    bootbox.dialog({
                        message: data,
                        title: "Custom title",
                        buttons: {
                            success: {
                                label: "Success!",
                                className: "btn-success",
                                callback: function () {
                                    $('#form_basic').submit();
                                    });
                                }
                            },
                        }
                    });
                }
            });
        }
```

My problem is: I have one form, named "form_basic" loaded using Ajax, And, I want, when press Confirm bootbox button, submit them, and if all is ok, close ... but these code above doesn't work.

Why?

Cheers

**Comment by CGeorges** [comment]
You have an error in your code 
 $('#form_basic').submit();
                                    });

that }); isn't supposed to be there. To avoid this type of errors use a better IDE that highlights syntax errors.

**Comment by tarlepp** [comment]
@CGeorges thanks for the solution, and @fellipeh you should really use some IDE so that you could easily avoid this kind of errors. Also your browser console should show some errors from that code too.

**Comment by fellipeh** [comment]
Ok thanks.... even fix that line, doesn't submit... any ideia?

**Comment by CGeorges** [comment]
Did you check you browser console for any other errors ?

**Comment by makeusabrew** [comment]
Closing; not a Bootbox issue.
