### ISSUE TITLE
Processing state for confirm dialog

### ISSUE THREAD

**Issue by benbro** [makeusabrew/bootbox#383]
Hi,

It will be useful to have a processing or loading state for the confirm dialog.
Use case:
- A user clicks on a button to delete a record in a table.
- A bootbox confirm dialog is shown asking "Are you sure?".
- The user clicks "OK".
- The dialog go to the Processing state. The Buttons are hidden and a message "Processing..." is shown.
- An Ajax request to delete the message is shown.
- When the Ajax request is done, the row is removed from the table and the dialog is hidden. If the Ajax request fails, an error message is displayed with a prompt dialog.

Thanks

**Comment by tarlepp** [comment]
Imho this is something that is application specified, not so much bootbox territory.

**Comment by makeusabrew** [comment]
Hi @djalexd, @tarlepp,

Apologies; I've been on vacation for the past 3 weeks and have a rather large backlog of issues to get through. I agree with @tarlepp that this is app-specific logic, not Bootbox's realm.

Nick
