### ISSUE TITLE
Not fire event 'show(n).bs.modal' with option 'animate: false'

### ISSUE THREAD

**Issue by alexpts** [makeusabrew/bootbox#386]

**Comment by tarlepp** [comment]
Could you provide plunker example of this?

**Comment by makeusabrew** [comment]
Additionally; a comparison of Bootbox Vs Bootstrap behaviour too; I suspect this is actually just how Bootstrap works, and have a *very* vague memory of at least one of the events definitely not firing with `animate: false` at the Bootstrap level.

**Comment by Dacesilian** [comment]
This issue is still there - onShow not fire when animation: false.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
