### ISSUE TITLE
Prompt modal could have a boolean to keep a required text.

### ISSUE THREAD

**Issue by danicomas** [makeusabrew/bootbox#387]

**Comment by makeusabrew** [comment]
Hi @danicomas,

Apologies; I've been on vacation for the past 3 weeks and have a rather large backlog of issues to get through. I'll try and think this over and get back to you as soon as I can :).

Nick

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
