### ISSUE TITLE
many layer in page , the background is black

### ISSUE THREAD

**Issue by sekole** [makeusabrew/bootbox#388]
Dear all, 
i have problem in my bootbox, when i launch bootbox displaying with many background layer, making the  background / page is black dosnt opacity as usual
here is my capture screen
![bootbox-error](https://cloud.githubusercontent.com/assets/10907478/6096357/2cba2ae4-afbf-11e4-91e4-07e42889c55b.jpg)

hope you would help me, thank you verymuch

**Comment by PiQ99** [comment]
Hey guy, 

I had the same problem. Just add the following line to your css. This helped for me

`.modal-backdrop.fade {
background-color: rgba(0,0,0,0.5);
}`
// or less opacity for more layers in your case

**Comment by alexliubj** [comment]
Same, how did you solved this finally.
