### ISSUE TITLE
Switch OK an Cancel buttons

### ISSUE THREAD

**Issue by Majstr** [makeusabrew/bootbox#389]
Switch OK and Cancel buttons so they will be like in system dialog box.
![system](https://cloud.githubusercontent.com/assets/5053492/6225319/be628868-b688-11e4-8ac2-4fe6396af096.PNG)
In Bootbox are other way around.
![bootbox](https://cloud.githubusercontent.com/assets/5053492/6225351/1e738644-b689-11e4-9859-0807142daa7c.PNG)

**Comment by makeusabrew** [comment]
Unfortunately this differs between operating systems and isn't something I'd particularly like to achieve by any sort of user-agent sniffing. Mac OS X and Linux render their confirm buttons the other way round; I believe it's only windows which is the main exception. This has been raised once or twice before but I'm afraid won't be changed any time soon.

**Comment by Majstr** [comment]
Maybe you put in an option how to render buttons. Most of users are on Windows.

**Comment by Mariatta** [comment]
@Majstr: I think you should utilize the Custom Dialog option for this.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
