### ISSUE TITLE
Bootbox Modal Form Validation

### ISSUE THREAD

**Issue by jdriesen** [makeusabrew/bootbox#390]
Hi,

First of all,  congratz with the development if this component...
Really great work !

I'm having a problem with Form Validation.
The scenario:
I created a form with 2 buttons.
Each button has a data-id="<article_number>" 

Based on the button click, the idea is to populate (via Ajax) a bootbox modal form.
The bootbox modal can't be closed, without all fields being validated... (I'm using http://formvalidation.io)

My question: How can I do this ?

(I already took a look at http://formvalidation.io/examples/bootbox/ , but I can't make it working via an AJAX load of the Bootbox modal (while keeping the validation rules ...)

Can smb PLEASE provide me an example ?

Thanks in advance,

Johnny
Belgium

**Comment by tarlepp** [comment]
You might need to load that form data before actually showing the modal, and on that event attach necessary validations to that form.

**Comment by jdriesen** [comment]
Thanks for the info @tarlepp .
Gonna study your project in detail, and will keep you posted.

Regards,

Johnny

**Comment by jdriesen** [comment]
Hi @tarlepp ,

I created a very small HTML page, describing my "problem".
Are you willing to help me ?
If so, how can I provide you the source / which is the most easy way to get in touch ?

Grtz & thanks in advance,

Johnny

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
