### ISSUE TITLE
Modal hide on "modal-backdrop" click

### ISSUE THREAD

**Issue by venanciorodrigo** [makeusabrew/bootbox#394]
Hi,

As mentioned on the ticket https://github.com/makeusabrew/bootbox/issues/217 the dismiss event when the user click on backdrop was implement in 4.4.0 release...

How do I activate that? Sorry but I didn't found any mention on the documentation. 

Thanks for this amazing project!

**Comment by makeusabrew** [comment]
Don't apologise; the docs are very poor and in desperate need of an update.

You can dismiss the dialog now by simply passing any of the standard Bootstrap values in, i.e. `static` (which is what Bootbox uses by default for backwards compatibility), `true` or `false`.

Passing `true` will show the backdrop but let you dismiss the dialog by clicking it. `false` won't show a backdrop and will let you dismiss the dialog by clicking anywhere outside of the modal.

`backdrop` is simply an option to any Bootbox dialog, e.g:

```
bootbox.alert({
  message: "Hi there!",
  backdrop: true / false / "static"
});```

**Comment by tarlepp** [comment]
Yeah the docs need some improvements.

**Comment by makeusabrew** [comment]
@tarlepp sure do! I'm thinking they need a total overhaul. Any ideas welcome :)

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
