### ISSUE TITLE
escape and backdrop won't work if no onEscape function is defined

### ISSUE THREAD

**Issue by jpass** [makeusabrew/bootbox#395]
"escape.close.bb" checks if callbacks.onEscape is defined, only then callback is processed and in the end modal("hide") is called.

**Comment by jpass** [comment]
I've added simple fix #396, unless it's supposed to work this way, but i can't see why.

**Comment by makeusabrew** [comment]
It's intentional, albeit perhaps not obvious. The idea being if you don't pass an on escape handler you have to explicitly interact with the dialog to dismiss it by clicking one of the available actions & triggering its callback.

**Comment by jpass** [comment]
I think modals should be cancellable by default otherwise its bad UX. But in rare occasions we require action from user we should be able to lock this modal. 

Instead of this fix, maybe onEscape should be set to true, by default. Then if we need to handle closing we can change it to callback, but if we need user to do something we just set onEscape to false.

If you disagree then i'll just set onEscape = true globally.

**Comment by makeusabrew** [comment]
I agree; they should be. All of the main built in methods, that is:

* alert
* confirm
* prompt

... allow you to dismiss the dialog by pressing the escape key.

However, when you elect to construct a custom dialog, it's *completely up to you* how you handle things. Try it for yourself - the only required parameter is a message. It's not Bootbox's job to impress upon people its own views on good or bad UX - that's up to the individual and their use case. It's not much hardship to add `onEscape: true` to any custom dialogs you're creating in my opinion.

Nick

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
