### ISSUE TITLE
bootbox from a modal

### ISSUE THREAD

**Issue by valix85** [makeusabrew/bootbox#398]
Hi i have a problem with bootstrap [dialog | alert] when i call it with a button on a modal open yet.
When i confirm (close) bootbox the parent modal don't scroll and i can't do anything!
i see body scroll but a long modal open stay blocked in center page, i can't scroll and i can't close.

what can i do to fire alert when there is just open modal on screen?

i try to compile a form in a modal and when i check the value before send, on error, i show an error with bootbox.alert but i have a problem with it. help me to resolve it pls.

thank you
Valerio

**Comment by tarlepp** [comment]
Basically this isn't not bootbox issue, because bootstrap doesn't support multiple modals at same time. Related to #375, #350, #378, #181

**Comment by makeusabrew** [comment]
Thanks @tarlepp. @valix85 I can't really add any more than what's already been said I'm afraid.

**Comment by valix85** [comment]
ok, than it's not possible, for fix my problem i have create a div in modal-body that contain error string and show/hide error in this space, without use bootbox when another modal is just open.


Thank all for support
bye
