### ISSUE TITLE
DOM Element gets removed

### ISSUE THREAD

**Issue by sumityadav** [makeusabrew/bootbox#399]
When you use a DOM element as message. It gets removed and next time bootbox loads blank body.
http://jsfiddle.net/sumityadav/e841q26j/1/

**Comment by makeusabrew** [comment]
Thanks for the concise bug report and clear jsFiddle. Much appreciated :)

**Comment by tarlepp** [comment]
Simple fix is to add ```.clone()``` to that message part.

**Comment by sumityadav** [comment]
Thanks @makeusabrew and @tarlepp for the quick responses. 

I tried the `clone()` to the message part and it doesn't remove it. But there is another issue with the `clone()` and `html()` functions that the jquery events don't work when we do it in bootbox.

I updated the jsFiddle at: http://jsfiddle.net/sumityadav/e841q26j/2/ which uses `clone()`.
In the jsFiddle try to remove the `clone()` and it will work for the first time and also remove the element from DOM (original issue).

**Comment by tarlepp** [comment]
imho, that's not bootbox problem at all. Basically that's javascript / jQuery "problem" when you're manipulation DOM like that.

If you need some "two way" binding like that, then I would just use angular.

**Comment by sumityadav** [comment]
@makeusabrew @tarlepp Are we accepting pull requests or there are no plans for further releases?

**Comment by MissChocoe** [comment]
Another option would be to add an option so the dialog doesn't get remove on close. In bootstrap, we can reuse modal.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!

**Comment by hisune** [comment]
@sumityadav How do you solve this problem? I have the same problem. when use `clone()` `bootstrap-datepicker` plugin not work in dialog

**Comment by sumityadav** [comment]
@hisune I created the pull request #401 which didn't get merged.
You can either use the changes I did in the pull request manually or use my fork which is current with the changes + the fix.
