### ISSUE TITLE
Can't click overlay to dismiss

### ISSUE THREAD

**Issue by ghost** [makeusabrew/bootbox#405]
The Bootstrap modal is dismissable by clicking outside it (on the overlay), but Bootbox doesn't seem to do this.

**Comment by makeusabrew** [comment]
Hi @CaptSaltyJack,

Apologies; the docs are hopelessly out of date. Try this:

```
bootbox.dialog({
  message: "hi",
  onEscape: function() { console.log("Escape!"); },
  backdrop: true
})
```

Cheers,

Nick

**Comment by CaptSaltyJack** [comment]
Doesn't work for me. `backdrop` and `onEscape` have no effect. Though I am using this:

https://github.com/TimHeckel/meteor-bootboxjs/

Which uses bootbox 4.3.0. Is that an issue?

**Comment by makeusabrew** [comment]
Yes, 4.4.0 only I'm afraid.

**Comment by CaptSaltyJack** [comment]
Thanks, Nick. Time to pressure that repo maintainer! ;)

**Comment by tarlepp** [comment]
Yep, that escape was implemented to 4.4.0 version, and this related to #402 where we discuss on same issue. I suggested that we add that necessary file for meteor package + hooks for auto publish, so that 3rd party doesn't have to maintain these.

**Comment by CaptSaltyJack** [comment]
Just curious, with `onEscape`, how would you trigger the modal to close? Is there some sort of `bootbox.hide` method?

**Comment by jevanlingen** [comment]
@CaptSaltyJack: just read the code. As seen below, only if onEscape has been defined, it will call the processCallback function.

````javascript
dialog.on("escape.close.bb", function(e) {
  if (callbacks.onEscape) {
     processCallback(e, dialog, callbacks.onEscape);
  }
});

function processCallback(e, dialog, callback) {
  dialog.modal("hide");
}

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
