### ISSUE TITLE
how to set modal id on bootbox?

### ISSUE THREAD

**Issue by yuomtheara** [makeusabrew/bootbox#411]
how to set modal id on bootbox?

**Comment by makeusabrew** [comment]
You can't natively, but something like:
```
var dialog = bootbox.alert("hi");

dialog.on("shown.bs.modal", function() {
  dialog.attr("id", "my-id");
});
```

Should work. A bit clunky I know, but not a use-case we've needed to accomodate so far.

**Comment by yuomtheara** [comment]
very thanks for your reply.

**Comment by GopalChavan** [comment]
var dialog = bootbox.alert("hi");
dialog.init(function(){
      dialog.attr("id", "my_id");
});
the Nick's answer work's but if you want to add some css based on id
then the css will be applied after the model is loaded completely on screen
so you see modal loading two times

**Comment by philippebickham** [comment]
Re https://github.com/makeusabrew/bootbox/issues/411#issuecomment-431823715
If you use the init function instead, the CSS will be applied before the popup is displayed, so you don't get the lag of application of CSS
```js
dialog.init(function() {
        dialog.attr("id", "my_id")
});
```
see http://bootboxjs.com/documentation.html#bb-function-init
