### ISSUE TITLE
Consider moving/cloning documentation to ReadTheDocs.org

### ISSUE THREAD

**Issue by tiesont** [makeusabrew/bootbox#412]
I've seen a few projects move their official docs to https://readthedocs.org. I like the general layout and structure of that site; would it make sense to move bootbox's documentation there?

As an example of a project that seemed to benefit from a more formal structure: http://bootstrap-datepicker.readthedocs.org/en/latest/

This is more of a "poll" than issue. I would be volunteering to do the initial port if there is enough interest by @makeusabrew and/or the community.

**Comment by tarlepp** [comment]
@tiesont Personally I like this idea. I didn't even know about that site before, so thanks for sharing that. Could you make really simple ```tl;dr``` of that service; how that works, who has access to modify docs, and so on...

**Comment by tiesont** [comment]
@tarlepp To be honest, I haven't published anything to that site myself at this point. I think this does a decent job of explaining the service: https://docs.readthedocs.org/en/latest/index.html. It looks like access is based on the source project, so anyone with write permissions to the Github project (or, the gh-pages branch, at least) could update the docs. 

I'll be doing a better exploration of the service over the next week or so, so at some point I can give you a better answer.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
