### ISSUE TITLE
Bootbox stops input after < symbol

### ISSUE THREAD

**Issue by jgordon510** [makeusabrew/bootbox#413]
If you type the < symbol into a field, bootbox stops taking input from that field at the symbol.  For example, on the bootbox example page and click on the prompt, and type your name as John<Doe, it will say, "Hello, John" instead of "Hello, John Doe".

**Comment by tarlepp** [comment]
Have you tried to ```encodeURI(input)``` for that callback function?

**Comment by jgordon510** [comment]
That works beautifully.  Thanks!

-Jeffrey
---------- Forwarded message ----------

**Comment by tarlepp** [comment]
imho this isn't bootbox 'error' this is just your application logic to handle different inputs. Or what do you think about this @makeusabrew ?

**Comment by makeusabrew** [comment]
@tarlepp completely agree; but it's something we should definitely fix on the example pages to encode the input as you've suggested here :)
