### ISSUE TITLE
Bootbox not working with Bootstrap 3.3.4

### ISSUE THREAD

**Issue by thirsch** [makeusabrew/bootbox#414]
Looks like the fix for backdrop in Bootstrap 3.3.2 was actually a bug and has been fixed now. Unfortunately, Bootbox is working with 3.3.2, but not with 3.3.4. The backdrop will be rendered above the dialog and the buttons can't be clicked anymore.

**Comment by makeusabrew** [comment]
Wonderful... more patching to do :). Thanks for the heads up!

**Comment by tiesont** [comment]
@thirsch  Are you sure you're not using an older version of Bootbox? I threw together the following bare-bones example, using the most recent version of Bootbox, and they seem to work just fine:
```
<!doctype html>
<html>
	<head>
		<meta charset="utf-8" />
		<title></title>
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">	
	</head>
	<body>
		<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
		<script src="file:///C:/path/to/your/copy/of/bootbox.js"></script>
		<script>
			$(function(){
				bootbox.alert('test');
				bootbox.confirm('test', function(result){});
				bootbox.prompt('test', function(result){});
			});
		</script>
	</body>
</html>
```

**Comment by thirsch** [comment]
Hi @tiesont, thanks for testing it too. The same example ist working for me (https://jsfiddle.net/8pkwddd8/2/). The only difference to my local version: I'm using Bootstrap SASS to be able to change the font-variable to another directory. For the latest Bootstrap SASS + the small CSS style from #415, everything is working for me as well. But pushing the z-index to 0 might not be the correct solution.

**Comment by tiesont** [comment]
@thirsch I just tried that fiddle on Firefox (37.0.1), Chrome (latest), and IE11, and it worked for me on all. I don't have a Mac handy at the moment, though I can test one tomorrow (technically, later today, I suppose); what OS and browser are you seeing this behavior in? Does the same happen with a [clean download](http://getbootstrap.com/getting-started/#download) of the SASS version of Bootstrap?

**Comment by thirsch** [comment]
Sorry for the confusion, the fiddle is the same example you provided and is working for me as well in all browsers. I tested it locally with a clean installation of the SASS version and the same result showed up. I'll try to create a fiddle that reflects my issue (including the build result of the SASS compiler).

In one of the next steps I'm planning to change the base colors of bootstrap on a per customer base. Therefore I thought it might be a good idea to use the SASS version and build a js version as soon as the customer has changed his colors.

**Comment by tiesont** [comment]
It might be possible that the SASS version is not in sync with the compiled CSS (which gets generated from the LESS files, I believe). Unfortunately, I don't use either build system, so I can't confirm or exclude that at the moment.

Either way, I don't think this is really a *Bootbox* issue, but I can't speak for @makeusabrew on whether this is a valid issue or not.

**Comment by tiesont** [comment]
It does seem more likely that this is a Bootstrap issue. See https://github.com/twbs/bootstrap/issues/16148

**Comment by makeusabrew** [comment]
Hi guys,

Will try and catch up on this thread soon and get back to you.

**Comment by thirsch** [comment]
I'm sorry, maybe any caching problems while I used the old bootstrap 3.3.2 SASS. After wiping all data from my browser and rebuild bootstrap 3.3.4 out of the latest SASS files, everything seems to work fine now! Thanks for your help!
