### ISSUE TITLE
Shaded bootbox dialog

### ISSUE THREAD

**Issue by dzlab** [makeusabrew/bootbox#415]
I'm trying to use bootbox (version 4.4.0) to create bootstrap (version 3.3.2) modals as follows:
```
bootbox.dialog({message: "hello"});`
```
My problem is that the rendered dialog is kind of disabled (all screen is shaded), I can't click on it and even `ESC` cannot make the modal disappear!
When I inspect the dialog element in the browser this is what I see:
````html
<div class="bootbox modal fade in" tabindex="-1" role="dialog" style="display: block;" aria-hidden="false">
  <div class="modal-backdrop fade in" style="height: 321px;"></div>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="bootbox-close-button close" data-dismiss="modal" aria-hidden="true" style="margin-top: -10px;">×</button>
        <div class="bootbox-body">hello</div>
      </div>
    </div>
  </div>
</div>
```
I checked with bootbox examples and it looks like it's the same CSS classes that have been used. So what's wrong here?

**Comment by thirsch** [comment]
Strange. Seems to be exactly what I'm experiencing with Bootbox 4.4.0 but Bootstrap 3.3.4. For Bootbox 4.4.0 and Bootstrap 3.3.2 at least bootbox.alert('abc'); is working fine for me.

**Comment by dzlab** [comment]
@thirsch  I tried `bootbox.alert('abc');` it's not working for me which makes sense as it uses [bootbox.dialog](https://github.com/makeusabrew/bootbox/blob/master/bootbox.js#l296-l316).

**Comment by makeusabrew** [comment]
@dzlab could you reproduce this please using a jsFiddle example or similar? Thanks :)

**Comment by dzlab** [comment]
@makeusabrew here is a [jsfiddle](https://jsfiddle.net/akLvxsrg/) sample

**Comment by thirsch** [comment]
Hi @dzlab, which browser are you using? Your fiddle is working fine for me in Safari, Chrome and Firefox under Mac OS X

**Comment by dzlab** [comment]
@thirsch  I was using Dragon, just tested in chromium and it works! I'have to dig further to reproduce the problem.

**Comment by dzlab** [comment]
I can't figure out the cause, here is a preview on chromium ![image](https://cloud.githubusercontent.com/assets/1645304/7086562/dabb2dda-df82-11e4-8c51-c6ad655d40e1.png)

**Comment by thirsch** [comment]
Could you please try to set the z-index of modal-backdrop to 0 in the inspector?

**Comment by dzlab** [comment]
thanks @thirsch the following fixed the problem:
```css
.modal-backdrop.fade.in {
  z-index: 0;
}
```
