### ISSUE TITLE
Alert, Confirm needs title and text

### ISSUE THREAD

**Issue by elgs** [makeusabrew/bootbox#420]
Currently it's only possible to set the text on the title area of the alert and confirm box. The font looks too small. I think setting title and text for alert and confirm box will make them look better. I understand this will break the API. I tried to use dialog as a workaround. But I found when I use dialog, it is not possible to press the ESC key to dismiss the dialog box. Is there a way to set the dialog box to be dismissed by pressing the ESC key?

**Comment by makeusabrew** [comment]
@elgs this is something which is is being requested more often and is under serious consideration (see #334).

In the meantime, yes, you can pass an `onEscape` handler to the dialog method: http://bootboxjs.com/documentation.html

**Comment by tiesont** [comment]
@elgs You can also override the default CSS for `.modal-title`, if all you're after is tweaking the font size. I tend to trim some of the padding and/or margin from the title, myself.

If you set the `className` option, you can even selectively tweak just about any style for the modals with your custom class.
```
bootbox.alert({
    className: 'my-modal',
    message: "I'm a custom modal alert!",
    callback: function() {
        // whatever you might need to do when dialog is dismissed
    }
});
```
With some rules:
```
.my-modal .modal-header h4.modal-title
{
    font-size: 24px; /* go wild. MAKE THE TITLE HUGE! */    
    color: #f40; /* orange is the new orange! */
}
```

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
