### ISSUE TITLE
calling prompt with a value containing single quote truncates it

### ISSUE THREAD

**Issue by jonrahoi** [makeusabrew/bootbox#421]
$('body').on("click", ".addNick", function(){
                bootbox.prompt("Enter Nickname",
                "cancel",
                "save",
                function(nick) {
                    if (nick){
                        $.post('/addNick', {
                            "uid" : $("#uid").val(), 
                            "nick" : nick
                        },function(info) {
                            $("#nickname").val(nick);
                            $("#deviceName").html(nick);
                        });
                    }
                },
                $("#nickname").val());
            });

if the value of nickname contains an apostrophe, the value displayed in the bootbox will be truncated at that index.  

here's the value displayed before launching the prompt:
![value displayed before clicking](https://cloud.githubusercontent.com/assets/2737471/7129153/374ca192-e211-11e4-8d80-d35205cb79e9.png)

here's the prompt with the value truncated:
![nickname value truncated](https://cloud.githubusercontent.com/assets/2737471/7129163/4fa676a0-e211-11e4-8035-3939a9975f65.png)

here's the inspector view - the value is getting cut off - i'm guessing boombox is using single quotes around the value - can we switch to double quotes?  or is there a better way to escape this?
![clearly you can see the value truncated in the output HTML](https://cloud.githubusercontent.com/assets/2737471/7129176/84e4bc8c-e211-11e4-95a8-7b6ef9690794.png)

**Comment by jonrahoi** [comment]
i figure the best workaround would be to escape single quotes with &#39; but should this be something bootbox does by itself?

**Comment by makeusabrew** [comment]
Hi @jonrahoi,

Which version of Bootbox is this? It looks quite old. I can't actually see anywhere in your snippet (and I may just need more :coffee:) where you're using Bootbox itself to set the prompt value either.

Cheers,

Nick

**Comment by jonrahoi** [comment]
ah yes, Nick - a totally relevant point I should have included.  This problem is on boombox 3.3.0, as i'm still on bootstrap 2.x.  The part that initializes the value is this line in the snippet: 

$("#nickname").val());

the last param to the .prompt function.

a simpler test:

    bootbox.prompt("Enter Nickname",
        "cancel",
        "save",
        function(nick) {
            console.log(nick);
            // or whatever
        },
        "jon's test case"
    );

you can see that the input in the boombox contains only "jon".  if you inspect the markup, you'll see the rest, malformed.  I suspect this could cause problems on older browsers.

**Comment by jonrahoi** [comment]
i've confirmed the problem is fixed in v 4.4.0.   I'm not sure if it's something you want to fix in 3.3.0, or if you're supporting it at all.  If not, feel free to close it and i'll migrate at some point.  Thanks!

**Comment by tiesont** [comment]
@jonrahoi The offending bit seems to be on line 215 of the 3.x branch. And yes, it's using single-quotes in the input template. So, you *could* just update that line in your local copy. 

I can also update the fork I keep handy (for making pull-requests as I find a few moments here and there to expand the documentation), if you need a dev + minified pair of the bootbox.js files.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
