### ISSUE TITLE
cdnjs for 4.4.0 missing

### ISSUE THREAD

**Issue by back-2-95** [makeusabrew/bootbox#422]
Hi,

Can you get latest version to https://cdnjs.com/libraries/bootbox.js ?

Thanks!

**Comment by tiesont** [comment]
I don't believe Nick actually manages that resource (he doesn't, for instance, manage any of the NuGet packages). From what I can tell, you can basically submit a pull-request against https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/bootbox.js, though.

**Comment by back-2-95** [comment]
Thanks for the information, I'll post request to cdnjs for this.

**Comment by tiesont** [comment]
@back-2-95 I don't know that you *have* to close this issue, especially as Nick hasn't reviewed it yet. I simply wanted to let you know what his likely response would be.

According to https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library, it seems like pretty much anyone can submit a pull-request with the current version. If you don't get a response from cdnjs, I'll take a crack at it some time this weekend.

**Comment by back-2-95** [comment]
Ok, I'll leave this open for now. Here is the issue on the cdnjs:
https://github.com/cdnjs/cdnjs/issues/4566

I checked the documentation, but it's still something I cannot do. Learning the git basics currently.

**Comment by tiesont** [comment]
Looks like the CDN is updated, so you could close this now if you want.

**Comment by back-2-95** [comment]
Yes, thanks!
