### ISSUE TITLE
bootbox not working with bs 3.3.4

### ISSUE THREAD

**Issue by kamiloCervantes** [makeusabrew/bootbox#424]
Hi there,

When you use this version (bootstrap v. 3.3.4), bootbox dialogs look like this:

![bootbox](https://cloud.githubusercontent.com/assets/540429/7251231/049e257a-e7ef-11e4-9b0f-81f4fdcb22c9.png)

**Comment by tiesont** [comment]
Which version of Bootbox? I use both the 4.4 version of Bootbox and Bootstrap 3.3.4 and I do not see this behavior.

**Comment by tarlepp** [comment]
Maybe related to #414 ?

**Comment by chuwik** [comment]
This works fine for me as well with Bootbox 4.4 and Bootstrap 3.3.4.
Could it be an issue with some custom CSS?

**Comment by tarlepp** [comment]
@chuwik that should be easily tested just disabled those custom CSS styles.

**Comment by chuwik** [comment]
@tarlepp it is working fine for me, I was just offering a possibility for why it doesn't work in @kamilinWP 's case

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
