### ISSUE TITLE
using rtl-bootstrap

### ISSUE THREAD

**Issue by tuytoosh** [makeusabrew/bootbox#427]
Hi , I am using rtl-bootstrap and when i click on link , the page the page become dark and i not see anything

**Comment by tarlepp** [comment]
Could you provide a plunker of your problem? That would help us a lot.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
