### ISSUE TITLE
Please can you guys create a DefinitelyTyped file for bootbox?

### ISSUE THREAD

**Issue by topgun743** [makeusabrew/bootbox#429]
Hi, 
Can you guys please create a DefinitelyTyped file for bootbox?
Need this to use in Visual Studio 2012 for using with TypeScript.

**Comment by makeusabrew** [comment]
Not familiar with TypeScript or what the DefinitelyTyped file would need to look like; happy to accept a PR though :)

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
