### ISSUE TITLE
vertical Align

### ISSUE THREAD

**Issue by farturi** [makeusabrew/bootbox#433]
Hi,

I'm using bootox with Bootstrap 3,
I'd like to know how to align an alert vertically in the page.
It's possible to set up options to the alerts?

Thank you very much.

**Comment by makeusabrew** [comment]
I'm afraid not; the presentation options for dialogs simply follow's Bootstrap's modals - so if they can't be vertically aligned then neither can those created with Bootbox.

**Comment by tarlepp** [comment]
Although you can make this by yourself using bootstrap modal events. Simple workflow:

```
var modal = bootbox.dialog({
  message: 'your content here',
  title: 'your title here',
  buttons: 'buttons configuration,
  show: false, // do not open modal automatic
  onEscape: function() {
    modal.modal("hide");
  }
});

modal.on("shown.bs.modal", function onShownBsModal() {
  // Calculate modal height and add necessary top offset to it
});

modal.modal("show");
```

I hope this helps.

**Comment by tarlepp** [comment]
Duplicate with #166, closing this now.
