### ISSUE TITLE
Dynamic Dialog buttons

### ISSUE THREAD

**Issue by seemple** [makeusabrew/bootbox#435]
Hi ! I Want to place dinamycs buttons according to a previous validation. In my case, is to put a "Try Again?" button on the modal only if a variable is set to true. How can I do that ? Thanks in advance!

**Comment by KrunchMuffin** [comment]
Looking to do this as well.

**Comment by tarlepp** [comment]
You could always change button text using simple jQuery, is that enough?

**Comment by KrunchMuffin** [comment]
I think I got something figured out. You can pass a variable to the label option. I just define it before the dialog. and in the callback is easy enough since you can do anything in there.

**Comment by seemple** [comment]
Hey! I don´t remember how i did with this but thanks anyway!
