### ISSUE TITLE
Dialog is not show

### ISSUE THREAD

**Issue by shangdiyisi** [makeusabrew/bootbox#438]
![qq 20150605085452](https://cloud.githubusercontent.com/assets/5936448/7997495/9b8e36e8-0b60-11e5-8b3f-f329f62db11f.jpg)

This is my code:
```javascript
bootbox.dialog("123");
```

**Comment by tarlepp** [comment]
Could you make a plunker example of this?

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
