### ISSUE TITLE
add callback if i press close button or esc 

### ISSUE THREAD

**Issue by publicocean0** [makeusabrew/bootbox#439]
i dont find in the bootbox a callback when user close dialog pressing on close button or esc ...

**Comment by OpacumHub** [comment]
up.
$(".bootbox").on("hidden.bs.modal", function() { }); dont work

**Comment by OpacumHub** [comment]
solved. 
You can use onEscape: function() {} in bootbox options

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
