### ISSUE TITLE
Need for double click on OK confirmation for Chrome 

### ISSUE THREAD

**Issue by ihr** [makeusabrew/bootbox#44]
I use booxbox confirm functionality and I have a problem with Chrome v21.0.1180.79 which I don't have with Firefox v14.0.1. The problem is as follows: when a bootbox confirmation appears I have to click two times on the OK button to confirm and close the confirmation box, clicking on cancel once is enough to close the confirmation.

**Comment by nishant-befree** [comment]
Hi Nick,

i face issue while i double click on Run Example it open two dialog box on http://bootboxjs.com/

Thanks
Nishant
