### ISSUE TITLE
Getting jSignature to work (repeatedly) with Bootbox

### ISSUE THREAD

**Issue by donluz** [makeusabrew/bootbox#441]
Hello. I am using Bootbox for my modal method in Bootstrap 3. I am initializing jSignature and when I click my button, the modal appears and the signature pad is inside it; I capture the signature and the modal closes. All works fine.

However, without a page refresh, once that modal closes and I click the button (to open the modal) again, the signature pad is NOT inside it - the entire body section is empty whereas the first time, it contains the signature pad.

I realize this is not support for "jSignature".  However, the real question is why do the contents of the Bootbox modal only appear the first time the modal is shown and not again until a page refresh?

I have gotten this code to work with BS3's modal method, but would much prefer Bootbox. A complete working example would be helpful.

Here is my JS code:

function resetSignature() {
$sigdiv.jSignature("reset"); // clears the canvas and rerenders the decor on it.
}

function getSignature() {
var theImgUrl = "/images/icons/stopwarn32x32.png";
var box = bootbox.dialog({
onEscape: function() {},
closeButton: true,
message: $('#signature'),
title: ' SIGNATURE CAPTURE',
buttons: {
reset: {
label: "RESET",
className: "btn-danger",
callback: function() {
resetSignature();
return false;
}
},
danger: {
label: "CANCEL",
className: "btn-warning",
},
success: {
label: "ACCEPT",
className: "btn-success",
callback: function(result) {
saveSignature();
}
}
}
})
.on('shown.bs.modal', function() {
$sigdiv = $("#signature");
$sigdiv.jSignature();
resetSignature();

    adjustModalMaxHeightAndPosition();
})

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
