### ISSUE TITLE
bootbox.alert() opens and closes before i click ok button

### ISSUE THREAD

**Issue by brday** [makeusabrew/bootbox#442]
Using: Bootstrap 3.3.4
           JQuery     1.11.2
           Bootbox    4.4.0

I am running in sharepoint 2010

I have a simple on click event like so:
```javascript
        //Event is called when button is clicked.
        <button id="bootbox" class="btn">Open dialog</button>

        <script>
        $("#bootbox").on("click", function(event) {    
            bootbox.alert("Hello world!", function() {
                Example.show("hello world callback");
            });
        });
        /**
         * This tiny script just helps us demonstrate
         * what the various example callbacks are doing
         */
        var Example = (function() {
            "use strict";

            var elem,
                hideHandler,
                that = {};

            that.init = function(options) {
                elem = $(options.selector);
            };

            that.show = function(text) {
                clearTimeout(hideHandler);

                elem.find("span").html(text);
                elem.delay(200).fadeIn().delay(4000).fadeOut();
            };
            return that;
        }());
        </script>
```
The Problem: Clicking the button will open the alert modal on the page but only for a few seconds
                       then it closes without clicking the 'ok' button. 
Also:               When the modal is open, my web page stays in a re-rendering state until the modal
                        closes.

![modalclosureissue](https://cloud.githubusercontent.com/assets/3953116/8072187/d875a042-0ecf-11e5-8f9d-f972b9c57ca2.PNG)

I have created one from scratch, that works, using bootstrap 3.3.4 but would prefer to use this library (love it!!).
Am I just not using this library correctly?

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!

**Comment by maq208** [comment]
I faced the same issue, but in my case following was the flow:
bootbox.alert("test bootbox #$%^&", function (x) {
                debugger;
            });
            window.open(redirect, "_self");
            return false;
I corrected it as follows, and it started working fine.
 bootbox.alert("test bootbox #$%^&", function (x) {
                debugger;
                window.open(redirect, "_self");
                return false;
            });
