### ISSUE TITLE
No example in documentation for bootbox.init 

### ISSUE THREAD

**Issue by otravers** [makeusabrew/bootbox#446]
It would be helpful to provide an example showing how to use bootbox.init before bootbox.dialog. It's described very succinctly and absent from the list of examples:
http://bootboxjs.com/documentation.html#bb-method-init

**Comment by tiesont** [comment]
From what I've been able to figure out, it's called like so:
```
bootbox.alert({ 
    /* ... your options... */ 
}).init(function(){
    /* ...your init code... */
});
```
Calling `init()` on it's own doesn't seem to have any effect, so I assume it has to be chained onto a dialog.

So, if you needed to, say, apply another plugin to your dialog contents (like datepickers or whatnot), you'd do it there.

**Comment by natecox** [comment]
@tiesont 
That doesn't seem to be the case. I get this result: 

```
bootbox.alert({message: 'test'}).init(function() { console.log('blah'); });
jquery.min.js:3 Uncaught TypeError: Cannot read property 'ready' of undefined(…)
```

**Comment by tiesont** [comment]
@natecox I made [this example](https://jsfiddle.net/Lu1wp3nn/) for a StackOverflow question, which seemed to work.

I'm not sure where your error comes from. If I copy your code verbatim to a jsFiddle, it doesn't generate an error and the console logs 'blah'.

**Comment by natecox** [comment]
@tiesont 

The referenced code was copy/pasted verbatim from Chrome's dev console.

![screen shot 2015-09-30 at 3 28 55 pm](https://cloud.githubusercontent.com/assets/2782695/10208403/0a068188-6788-11e5-8b6b-5239a5672b58.png)

**Comment by tiesont** [comment]
@natecox I don't get that error, [using the code you provided](https://jsfiddle.net/p5pcyt4d/). It seems more like you might have the scripts in the wrong order. It should be 

jquery
bootstrap
bootbox

The jsFiddle is using Bootstrap 3 and Bootbox.js 4.4.

**Comment by natecox** [comment]
@tiesont 

This is related to the jQuery version. If you switch the fiddle's version to anything less than 1.11 you will get the same error that I am.

**Comment by tiesont** [comment]
@natecox I would recommend opening a new issue, then.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
