### ISSUE TITLE
confirm callback misses to received forwarded event.

### ISSUE THREAD

**Issue by burmester** [makeusabrew/bootbox#447]
I'm using jQuery dirtycheck and bootbox.
Dirtycheck checks if a form has been altered and warn if you trying to leave the page. You can choose yes to leave and no to stay. By pressing yes a event triggers, which triggers the callback function. The callback function takes a event, but bootbox misses to forward it along the way, see attached screenshots. 

row 108 : callback.call(dialog, e) - e is forwarded
row 330: options.buttons.confirm.callback = function(){ - not received 
row 331: return options.callback.call(this, true); - not forwarded

so arguments need to be forwarded to the callback function.

![screen shot 2015-06-24 at 15 55 15](https://cloud.githubusercontent.com/assets/1188802/8331597/85c4d140-1a89-11e5-9eb1-8f4d42e2aa4f.png)

![screen shot 2015-06-24 at 15 55 30](https://cloud.githubusercontent.com/assets/1188802/8331604/8d9974fc-1a89-11e5-85d7-01b82dfd7274.png)

**Comment by tarlepp** [comment]
Could you provide plunker of this?

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
