### ISSUE TITLE
bootbox.prompt does not work as expected

### ISSUE THREAD

**Issue by mondwan** [makeusabrew/bootbox#450]
Bootbox Version 4.4.0 production version

According to document [here][1], prompt accepts ```message``` and ```title```. However, only ```title``` work.

JSFiddle [here][2]

[1]: http://bootboxjs.com/documentation.html#bb-prompt-dialog-options
[2]: https://jsfiddle.net/Gzagv/20/

**Comment by mondwan** [comment]
The problematic codes spotted: https://github.com/makeusabrew/bootbox/blob/master/bootbox.js#L379-382

Why we need to override this field?

**Comment by mondwan** [comment]
Same issue as #397 with pull request https://github.com/Servoy/bootbox/commit/b275c2e85487081b65897cfacf1cb87db4f26641

**Comment by tiesont** [comment]
I suppose the primary reason for not allowing a message is to prevent "unhandled" inputs from being added to the prompt. By "unhandled", I suppose I mean "unexpected", in that the prompt code assumes a single form with it's own templated inputs. If a developer attempts to add more inputs to the prompt, expecting them to be part of the result object, they might be confused when they're not.

That being said, it seems like message could be allowed. I was able to get consistent results from prepending the message to the form. I could have also used a custom dialog, which seemed like a bit of overkill when I just needed the one return value that prompt provides.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
