### ISSUE TITLE
Bootbox over another modal

### ISSUE THREAD

**Issue by delta1186** [makeusabrew/bootbox#451]
So I found an interesting issue.  You can review it here:  https://jsfiddle.net/zrky7qum/

Scenario:
Page has content where you have to scroll to view all. You have a modal which is launched and page scrollbar is hidden which is by design.  Then you have a bootbox confirm linked to the modal's save button.  Bootbox confirm opens.

Issue:
When you close the bootbox confirm the modal's backdrop is now scrolling.  Somehow the modal's backdrop height has been set to the full height of the body when you close the bootbox dialog.

Hopefully this makes sense.

**Comment by Niades** [comment]
Same here. It might be related to #482 .

**Comment by mohammedabualsoud** [comment]
This issue occurred to me too.
Thanks delta1186 I use your solution.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
