### ISSUE TITLE
Show bootbox synchronization

### ISSUE THREAD

**Issue by phanhongphucit** [makeusabrew/bootbox#452]
When bootbox is shown, the code below bootbox.alert/confirm run. Is there any option to let the below code run just when after the callback finished?

Thanks

**Comment by KrunchMuffin** [comment]
u have to implement promises or use standard alert/confirm

**Comment by tarlepp** [comment]
Bootbox won't block any javascript logic to run on your page when modals are opened. You should add that logic to your application, or use standard alert/confirm which will block other code to run.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
