### ISSUE TITLE
Override templates options

### ISSUE THREAD

**Issue by Grey2k** [makeusabrew/bootbox#454]
It will be very useful to override templates variables with options 

like 

````js
options = {
...
templates:
   closeButton: '<html here>'
}

````

**Comment by superKalo** [comment]
+1

**Comment by tarlepp** [comment]
That could be useful in some cases, but that will also complex actual button handling alot. eg. if you define:

```
options = {
...
templates:
   closeButton: '<span><button>foo</button><button>bar</button></span>'
}
```

Which element "click" will make actual close function callback? So imho this feature _could_ be useful in some cases _but_ this will add a lot of complexity to bootbox itself,  so I wouldn't recommend to add this atm. What do you think @makeusabrew ?

And of course I might be wrong with this too - @Grey2k could you make a PR about this feature and prove that I'm wrong?

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
