### ISSUE TITLE
Documentation for 'backdrop' is lacking

### ISSUE THREAD

**Issue by dvanderfaeillie** [makeusabrew/bootbox#456]
There is no note in the documentation of the `backdrop`requirement that `onEscape` must be set to `true` (or as a custom function?).

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
