### ISSUE TITLE
When I use bootbox + browserify, I've this error « $.fn.modal is not defined; please double check you have included the Bootstrap JavaScript library »

### ISSUE THREAD

**Issue by harobed** [makeusabrew/bootbox#457]
When I use bootbox + browserify, I've this error « $.fn.modal is not defined; please double check you have included the Bootstrap JavaScript library »

**Comment by harobed** [comment]
Too fix that, I need : 

```
var $ = require('jquery');
global.jQuery = require("jquery");
window.$ = $;
var bootstrap = require('bootstrap');
var bootbox = require('bootbox');
```

Are there a better solution ?

Suggest : append browserify section in bootbox documentation.

**Comment by tiesont** [comment]
Bootbox is **not** self-contained library. It builds on top of Bootstrap's modals, so yes, you need to load Bootstrap first. Or am I missing something?

**Comment by tarlepp** [comment]
@tiesont No you're not missing anything bootbox needs ```Bootstrap``` to work as it's explained [here](https://github.com/makeusabrew/bootbox#a-note-on-bootstrap-dependencies) and Bootstrap itself needs jQuery which is explained [here](http://getbootstrap.com/getting-started/#whats-included).

@harobed Could you make a PR to [gh-pages](https://github.com/makeusabrew/bootbox/tree/gh-pages) branch and explain there how to make bootbox + browserify combo to work?

**Comment by tarlepp** [comment]
Hmm, this is also related to #455

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!

**Comment by dejwid** [comment]
I have the same problem..

**Comment by donnyjeremiah** [comment]
I had the same issue importing bootbox in webpack. I don't know what is causing the problem, but I solved it by getting it from the cdn, rather than installing it via npm and bundling it via webpack.

**Comment by nckg** [comment]
I'm sorry for commenting on a closed issue but this did the trick for me:

```js
var $ = jQuery = require("jquery");
require("bootstrap-sass");
var bootbox = require('bootbox');
```

**Comment by baskicisamet** [comment]
where should we write this?

**Comment by ernestgwilsonii** [comment]
@nckg You are AWESOME! Thank you for posting your follow-up on what did the trick for you!
Hours of searching and your comment did the trick!
I am playing around with Chrome Extensions and Bootbox works because of you taking the time to comment!
REF: https://github.com/ernestgwilsonii/snce/releases/tag/v0.0.2
