### ISSUE TITLE
composer.json missing

### ISSUE THREAD

**Issue by janwalther** [makeusabrew/bootbox#459]
In the released tags of bootbox the composer.json is missing.
composer.json complains:
Skipped tag v4.4.0, no composer file

Moreover the "v" at the beginning of the versions prevents composer from recognizing versions. Why not use semantic versioning (without v)?

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
