### ISSUE TITLE
close bootbox dialog on click-link

### ISSUE THREAD

**Issue by wakaguaka** [makeusabrew/bootbox#460]
Hello,
I have a messy HTML bootbox dialog and I was wondering how can I close that dialog after clicking my custom link? (the custom link fires a javascript function and passes some values to the main form)
The purpose of the dialog is that the user will select an item from a list, the selection is when the item is being clicked.
Thanks

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
