### ISSUE TITLE
Fade Effect

### ISSUE THREAD

**Issue by ray73864** [makeusabrew/bootbox#462]
Is it possible to have it so that you can turn the fade effect on and off? In some instances I would like the dialog (alert, prompt, custom, etc...) to just appear on the screen, and in other instances I don't mind if it fades.

Thought about using 'show.bs.modal', but for some reason (at least with a custom dialog using bootbox.dialog), that particular event doesn't fire at all.

Tested it by doing a 

```
bootbox.dialog({
  title: "My Test Dialog",
  message: "This is a dialog!"
}).on("show.bs.modal", function(e) {
  var the_modal = $(this);
  console.log(the_modal);
});
```

However (at least in chrome), I never see anything in the log at all, it works perfectly for 'shown.bs.modal', 'hide.bs.modal', and 'hidden.bs.modal'.

**Comment by tarlepp** [comment]
There is ```animate``` option for this more info [here](http://bootboxjs.com/documentation.html#bb-dialog-options).
