### ISSUE TITLE
Glyphicons in buttons are rendered oddly

### ISSUE THREAD

**Issue by spencer-shadley** [makeusabrew/bootbox#463]
When attaching a bootstrap glyphicon to bootbox buttons the text is rendered in low resolution and odd spacing occurs between words.

Code:
someBtn: {
							label: " Btn",
							className: 'btn-info glyphicon glyphicon-download',
							callback: function() {
							}
						}

Result:
![unnamed image 1](https://cloud.githubusercontent.com/assets/7321105/9285494/011dd4a0-42ac-11e5-8829-62df2d18e253.png)

**Comment by clemens321** [comment]
You cannot add glyphicon-classes to the button's className-List. This way all text inside the button is rendered using the glyphicon-font. Instead add a new <span>-tag for your icon.

    someBtn: {
        label: '<span class="glyphicon glyphicon-download"></span> Btn',
        className: 'btn-info',
        callback: function() {
        }
    }

live example: http://jsfiddle.net/x4vorjmL/

**Comment by spencer-shadley** [comment]
Interesting, just embed the HTML directly into the label tag. Thanks for the information!
