### ISSUE TITLE
Close button position when no title

### ISSUE THREAD

**Issue by andrews05** [makeusabrew/bootbox#464]
Bootbox is currently setting margin-top: -10px on the close button when the modal has no title. Maybe this is leftover from bootstrap 2 or something, but in bootstrap 3 it should be set to -2px.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
