### ISSUE TITLE
Bootbox closes after alert window

### ISSUE THREAD

**Issue by mladenko** [makeusabrew/bootbox#467]
I have a alert if all fields are empty, in my callback of Success button, but when i click OK in alert, modal also closes. How to make bootbox stay open?

**Comment by tarlepp** [comment]
Could you provide example of this at [plunker](http://plnkr.co/)? That would help to understand what you're trying to do.

**Comment by ryanicle** [comment]
@mladenko I encountered this before. At the end of success callback, you can just include`return false;` It will only close alert and then main modal still opens. Hope this helps you.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
