### ISSUE TITLE
Autoclose function for alerts

### ISSUE THREAD

**Issue by Hejprint** [makeusabrew/bootbox#468]
It will be awesome to have autoclose function for alerts.
A number of seconds/microseconds will be passed as parameter to `bootbox.alert()`

**Comment by tarlepp** [comment]
Imho that is not something that bootbox should support because Bootstrap itself doesn't support this kind of modals.

Although you can easily make this happen by yourself. I created a plunker to demonstrate this http://plnkr.co/edit/b948vPtGHrh0LnzliAoR?p=preview check that out.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
