### ISSUE TITLE
hide.bs.modal called twice

### ISSUE THREAD

**Issue by gdycus** [makeusabrew/bootbox#482]
The close link has a close event attached to it and also includes data-dismiss=true on the link. This is causing "hide.bs.modal" to be called twice. I hacked it by adding the following code to "shown.bs.modal".

$(this).find('.bootbox-close-button').removeAttr('data-dismiss');

**Comment by soisme** [comment]
Same here . Which shown.bs.modal should I add the above code into?

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
