### ISSUE TITLE
adding "shouldAccept" callback

### ISSUE THREAD

**Issue by thethirduniverse** [makeusabrew/bootbox#485]
Currently the callback is only called upon dismissal of the pop-up. It makes it difficult to provide validation for entered values. 

I think it would be great to add a new callback that is called with the current value of the box when user tries to click the 'OK' button. If the value is 'good', then user can return true and let the real callback be called. If the value is 'bad', the user should be able to provide an error message that will be displayed on the pop-up directly without dismissing it.

**Comment by ryanicle** [comment]
To keep popup opens, you can try to use `return false;` in the end of callback function. Then add message. Let me know if it works for you.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
