### ISSUE TITLE
bootbox.confirm should accept Enter/Return key as "OK"

### ISSUE THREAD

**Issue by avindra** [makeusabrew/bootbox#486]
The native JavaScript confirm api will accept "Enter" as selecting "OK". Bootbox should mimic this, because it's a very well established pattern and honestly quite annoying when it doesn't work.

**Comment by avindra** [comment]
Code example which does not work:


```
bootbox.confirm({
		title : "Test",
		message : "Do you agree?",
		buttons : {
			confirm : {
				label : "Yes",
				className: "btn-success"
			},
			cancel : {
				label : "No",
				className: "btn-warning"
			}
		},
		callback: function(result) {
			console.log(result);
		}
});
```

Possible that I am not using the API correctly.

**Comment by avindra** [comment]
```
bootbox.confirm("Are you sure?", function(result) {
  console.log(result);
}); 
```

A more basic example that does not work. Interestingly on your demo site, it works from the play button but not from the console.

**Comment by ArktekniK** [comment]
Also a problem for me

**Comment by Kasceh** [comment]
Escape should also dismiss the window!

**Comment by ArktekniK** [comment]
````
bootbox.confirm("hey", function(ret){console.log(ret)});
````
A quick test indicates that escape does dismiss the window.

bootbox.js v4.4.0

**Comment by Kasceh** [comment]
Did you try a `bootbox.dialog`?

**Comment by ArktekniK** [comment]
The dialog has an extra parameter to enable that:

````
var dialog = bootbox.dialog({
  title: 'My title',
  message: formElement,
  onEscape: true,       //HERE
  buttons: {
    cancel: {
      label: 'Cancel',
      className: 'btn-default',
      callback: function () {
      }
    },
    confirm: {
      label: 'OK',
      className: 'btn-primary',
      callback: onSubmit
    }
  }
});
````
Try **onEscape: true**

**Comment by ArktekniK** [comment]
The solution to this issue by the way, (in my case for the dialog) was to bind an event handler to the jQuery element object's **submit**, as it was a form within the fialog. That way, if you hit enter within the form, then the handler processes it and calls dialog.modal('hide'); If OK was pressed, the same handler is hit.

````
var onSubmit = function(){
  //  Process form data
  dialog.modal('hide');    // Hoisted from below and refers to the specific dialog
}

var formEle = $('<form class="bootbox-form">');
formEle.on('submit', onSubmit); // Handles Enter key in form

var dialog = bootbox.dialog({
  title: 'My title',
  message: formElement,
  onEscape: true,       // Handles Escape
  buttons: {
    cancel: {
      label: 'Cancel',
      className: 'btn-default',
      callback: function () {
      }
    },
    confirm: {
      label: 'OK',
      className: 'btn-primary',
      callback: onSubmit  // Handles OK button
    }
  }
});
````

**Comment by glaidler** [comment]
+1

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
