### ISSUE TITLE
Dialog options change if initial options are show:false

### ISSUE THREAD

**Issue by leqwasd** [makeusabrew/bootbox#488]
So I will explain how it looks like:

    //Initialize
     var bb = bootbox.dialog({message: "Test", backdrop: false, show: false});
    bb.modal("show"); // shows dialog without backdrop
    bb.modal("hide");
    bb.modal("show") // shows dialog with backdrop!

And this not only about backdrop. Basicly I have dialog with table, and user can click on a row to proceed further. Basicly inside the message I have something like this:

    $('#table tr').click(function(){
        //do something
        bb.modal("hide");
    }

Next time when I call 

    bb.modal("show");

the interface inside basicly becomes unresponsive. table click events never fire, close button does nothing (OK button), modal can only be closed by [X] in the top right, but that is useless for me.

I am not sure if this is an actual issue, or error in my side.

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
