### ISSUE TITLE
Bootbox Confirm Issue

### ISSUE THREAD

**Issue by rdd992** [makeusabrew/bootbox#489]
I'm using bootboox and ajax, the modal hides but stills here, and it block my icons 
![sin titulo](https://cloud.githubusercontent.com/assets/13080542/12026858/490224c2-ad9d-11e5-87e6-17c4d8a31692.png)
Here is the code:
function deleteDocument(uuid){
	bootbox.confirm("Se iniciara una petición de anulación del documento. ¿Desea continuar?", "Cancelar", "Aceptar", function(result) {
		if(result==true){
			$.ajax({
				url:'/share/page/dashlets/deleteDocument?uuid='+uuid,
				type: "get",
				dataType: "json",
				success: function(data) {
					if(data.status == true){
						popupSuccess("Petición de anulación iniciada exitosamente"); 
					}else{
						popupAlert("No se pudo iniciar la petición de anulación");
					}
				}
			});
		}
	}).addClass("mdsuccess").attr('id','smallModal'); 
}

**Comment by wangxulin** [comment]
can u make the code with syntax color?

**Comment by tanvan81** [comment]
Hi, I have issue when using confirm

 bootbox.confirm({
                title: " Title",
                message: "Are you sure reset password ?",
                callback: function (result) {
                    if (result == true) {
                        $.post(link, function (data) { // I call Json request to request pass
                            bootbox.show("That's ok");
                        });
                    }
                }
            })

when I run this code, FF error: bootbox.show is not a function

**Comment by ryanicle** [comment]
@tanvan81 as far as I know, there is no such function in bootbox library. Closet one will be `bootbox.alert("That's ok");`

**Comment by tanvan81** [comment]
tks so much. I'm sorry

**Comment by makeusabrew** [comment]
Hi there - I'm declaring bug bankruptcy on a lot of old issues today as I can't keep on top of them all. If there's still an issue here please raise a new one with as clear and concise an overview as possible. Thanks!
