### ISSUE TITLE
Confirm - TypeError: checkValidity

### ISSUE THREAD

**Issue by JDittmerCOM** [makeusabrew/bootbox#491]
Hello,

I bought myself a design about two days ago and so far no problems it can work.
Now I wanted to let the data Save function via the "JS confirm", only an error message every time after you click on the button.

**Info:**
Bootbox 4.4.0
jQuery v2.1.4 and before 1.11.3

![9o9hue86](https://cloud.githubusercontent.com/assets/11929467/12249525/994c8c1e-b8c0-11e5-9e34-02d4d6761461.png)

```javascript
$('#contact_sub').on('click', function(){
	var email = $('input[name="contact_email"]').val();
	var phone_number = $('input[name="contact_phone_number"]').val();
	var mobile_number = $('input[name="contact_mobile_number"]').val();

	bootbox.confirm({ 
	    message: "Wirklich aktualisieren?", 
	    callback: function(result){
	    	$.ajax({
				type: "POST",
				url: "js/php/SAVE_customer_data.php",
				data: {
					AREA: contact_sub,
					email: email,
					phone_number: phone_number,
					mobile_number: mobile_number
				},
				success: function(){
		            var place = "messenger-on-top messenger-on-right",
		                theme = "flat";
		            
		            msgOpt(place, theme);
		            Messenger().post({
		                message: 'Die Kontaktdaten wurden gespeichert.',
		                type: 'success',
		                showCloseButton: true
		            });
				},
				error: function(){
					bootbox.alert("Es ist ein Fehler beim Bearbeiten der Anfrage aufgetreten.\nBitte kontaktieren Sie den Administrator.");
				}
			});
	    }
	})
});
```

Sincerly,
Justin Dittmer

**Comment by makeusabrew** [comment]
Hi there,

`checkValidity` isn't a method exposed by Bootbox - from the looks of the code snippet above you have a few other external libraries which may or may not be interfering with each other. I'm afraid as I have no visibility of these I can't offer any advice on this one - sorry.

Nick
