### ISSUE TITLE
Bootstrap 4.0?

### ISSUE THREAD

**Issue by DavidAnderson684** [makeusabrew/bootbox#492]
Hi,

At what sort of stage are you likely to add support for Bootstrap 4, if you know? (Bootstrap 4 is at alpha 2 - alpha 1 was Aug 2015, then alpha 2 in December).

David

**Comment by tarlepp** [comment]
imho, there is no hurry when 4.0 is in alpha stage.

**Comment by PhilJ88** [comment]
Working just fine for me on v4 Alpha 2 so far :)

**Comment by DavidAnderson684** [comment]
That's good to hear. I'm also developing a project that's using the Bootstrap alpha.

**Comment by PascalPencil** [comment]
Only thing to do is change btn-default to btn-secondary

**Comment by makeusabrew** [comment]
As @tarlepp says, no plans while it's in Alpha stage; too much can break before release.

**Comment by achillesrasquinha** [comment]
Okay, what about now?

**Comment by tiesont** [comment]
Officially? I don't know. I've done some work in my own fork - see #545 for what what I'm working on. If you just want the current version to work properly, see #566 - the only real "breaking" change between 3.3.7 and 4.0.0-beta is the header, since 4.x uses flexbox instead of float.

**Comment by DavidAnderson684** [comment]
@achillesrasquinha You should open a new issue - this one was closed, so the developer may never see your question, depending on his habits.
