### ISSUE TITLE
Add 'message' option in bootbox.prompt 

### ISSUE THREAD

**Issue by crona2011** [makeusabrew/bootbox#493]
I had to add a body option in your prompt dialog for my code:

```javascript
if (g(j, function(a, b) {
                k += "<button data-bb-handler='" + a + "' type='button' class='btn " + b.className + "'>" + b.label + "</button>", l[a] = b.callback
            }), i.find(".bootbox-body").append(a.message).prepend(a.body), a.animate === !0 && d.addClass("fade"), a.className && d.addClass(a.className), "large" === a.size ? f.addClass("modal-lg") : "small" === a.size && f.addClass("modal-sm"), a.title && i.before(n.header), a.closeButton) {
            var m = b(n.closeButton);
            a.title ? d.find(".modal-header").prepend(m) : m.css("margin-top", "-10px").prependTo(i)
        }...
```

The `message` option was taken so I used `a.body` instead

**Comment by Mithgol** [comment]
That's right, `message` option should be displayed between the `title` option and the input.

**Comment by makeusabrew** [comment]
Thanks for this. IMO `bootbox.prompt` works as expected and doesn't need an extra body argument at present.

**Comment by samuelstein** [comment]
Another workaround would be something like this: `$("<p>Message</p>").prependTo(".modal-body");`

**Comment by tiesont** [comment]
@samuelstein That was already noted in later issues, #543 being the most recent I can recall. Thank you, though.
