### ISSUE TITLE
bootbox.confirm wrong button labels

### ISSUE THREAD

**Issue by pragmaware** [makeusabrew/bootbox#494]
When you confirm something you usually answer with a "Yes" or "No", not with an "OK" or "Cancel".
So bootbox.confirm should probably use "Yes"/"No" as button labels.

**Comment by ryanicle** [comment]
Have you tried bootbox.dialog? It should work as you'd like.

**Comment by tiesont** [comment]
It's probably an abuse of the option, but you *could* create a custom locale if you wanted to change the button text, and then specify the custom locale when calling the confirm function.
```
$(function() {

  bootbox.addLocale('alt-confirm', {
    OK: 'OK',
    CANCEL: 'No',
    CONFIRM: 'Yes'
  });
  
  bootbox.setLocale('alt-confirm');

  bootbox.confirm({
    locale: 'alt-confirm',
    message: "Are you sure?",
    callback: function(response) {}
  });
})
```
[jsFiddle: https://jsfiddle.net/ephq1how/](https://jsfiddle.net/ephq1how/)

Not sure I like the order of "No" then "Yes", but it's close.

**Comment by tiesont** [comment]
Another (much simpler) option: you can't change the order of the buttons, but you *can* change the text:

```
bootbox.confirm({
	message: "This is a confirm with custom button text! Do you like it?",
	buttons: {
		confirm: {
			label: 'Yes'
		},
		cancel: {
			label: 'No'
		}
	},
	callback: function (result) {
		console.log('This was logged in the callback: ' + result);
	}
});
```

**Comment by makeusabrew** [comment]
@pragmaware this comes back to one of the core principles of Bootbox - mimic the native prompt, alert and confirm methods as closely as possible. They use 'OK' and 'Cancel', but as @tiesont states you can customise the labels if you're not happy with them.
