### ISSUE TITLE
Standardize Bower distribution by adding dist folder with minified files

### ISSUE THREAD

**Issue by ste93cry** [makeusabrew/bootbox#496]
Usually Bower downloads have a `dist` folder where all production assets are located, possibly minified. Any plan on doing it too for bootbox?

**Comment by makeusabrew** [comment]
Yep, on the list... promise...

**Comment by makeusabrew** [comment]
Dupe of #208

**Comment by chule143** [comment]
any news on this?, the package from Bower doesn't come with the minified version
