### ISSUE TITLE
Unable to use Example.show()

### ISSUE THREAD

**Issue by ronfreelancer** [makeusabrew/bootbox#498]
I am trying to implement bootbox confirmation box every thing is working fine but example.show.

bootbox.prompt({
  title: "What is your real name?",
  value: "makeusabrew",
  callback: function(result) {
    if (result === null) {
      Example.show("Prompt dismissed");
    } else {
      Example.show("Hi <b>"+result+"</b>");
    }
  }
});

Prompt dismissed and results is not coming when confirm box is closed.

**Comment by Ebsy** [comment]
"Example" in this case is literally just an example. You could have your code do anything at that point.
Try replacing 
`Example.show("Prompt dismissed");`
with 
`alert("Prompt Dismissed");`

and 
`Example.show("Hi "+result+"");`
with
`alert("Hi " + result);`

**Comment by ronfreelancer** [comment]
But i don't want to show it in alert box instead of that i want to it in a box will will disappear in 5 seconds automatically.

Let me know how to handle this struggling from long time.

**Comment by makeusabrew** [comment]
Hi,

The `Example` object is just something used in the demo pages as @Ebsy notes. What you do in each callback is up to you dependent on your own needs.
