### ISSUE TITLE
Submit form from dialog callback

### ISSUE THREAD

**Issue by LeeDumond** [makeusabrew/bootbox#501]
We are attempting to use Bootbox to create a delete confirmation dialog where the user has to type the name of the entity he wants to delete. This is very much like Github does when you wish to delete a respository.

To do this, we are using a bootbox.dialog to interrupt the submittal. The dialog provides a textbox where the user types the confirmation string. 

If the string does not match, we show a bootbox.alert to tell the user that their input did not match and that the entity was not deleted. That works fine.

If the string DOES match, we want to go ahead with the form submit. We do that by getting a reference to the form that was clicked, and calling .submit on it. However, _the form does not get submitted.
_

Can anyone explain how to get the form to submit from the 'success' callback?

**This is the button:**
`
<button name="submit" value="index" data-confirm-name="@agency.Name" data-entity-type="agency" type="submit" class="btn btn-danger btn-xs">
                                 <i class="fa fa-trash"></i> Delete
                              </button>
`

**This is the button 'click' handler:**

`

$('[data-confirm-name]').on('click', function(e) {
            e.preventDefault();

            var theForm = $(this).closest('form');
            var stringToConfirm = e.target.dataset.confirmName;
            var entityType = e.target.dataset.entityType;

            bootbox.dialog({
               title: 'Are you ABSOLUTELY sure?',
               message: '<p style="padding: 10px;" class="bg-warning">Unexpected bad things may happen if you don\'t read this!</p> ' +
                  '<p>This action <b>CANNOT</b> be undone. This will permanently delete the <b>' + stringToConfirm + '</b> ' + entityType +
                  ' and all of its associated data.</p>' +
                  '<p>Please type the name of the ' + entityType + ' <i>exactly</i> as it appears above to confirm.</p>' +
                  '<form><div class="form-group"><input type="text" class="form-control" id="confirmationString"></div></form>',
               buttons: {
                  cancel: {
                     label: "Cancel",
                     className: "btn-default"
                  },
                  success: {
                     label: 'I understand the consequences, delete the ' + entityType,
                     className: "btn-danger",
                     callback: function() {
                        var confirmationString = $('#confirmationString').val();

                        if ($.trim(confirmationString) === stringToConfirm) {
                           theForm.submit();
                        } else {
                           bootbox.alert('The name you entered did not match. The ' + entityType + ' was not deleted.');
                        }
                     }
                  }
               },
               onEscape: {
                  callback: function () { }
               }
            });
         });
`

**Comment by LeeDumond** [comment]
Anything guys? Not to me a pain, but still just wondering if it is possible to submit a form existing on a page from a callback...

**Comment by btafoya** [comment]
Yes, just reference the form id which is easier. (Set an ID if it does not have one.)  I do it all the time. :)
$("#formID").submit();

**Comment by makeusabrew** [comment]
@btafoya's suggestion looks like it should do the trick here 👍
