### ISSUE TITLE
Download complete Package

### ISSUE THREAD

**Issue by accorinti** [makeusabrew/bootbox#502]
Hello, I find it very complicated and confused to download everything you need for this project.
If I got everything right, the user needs following files:
bootstrap.min.css
jquery.min.js
bootstrap.min.js
bootbox.min.js

Where is for example the css file? I couldn't find it. It's not even in the whole repository zip file.

Why don't you just make a package with those files for the "normal" user just to get started?
May be also a small demo directory with everything it is needed for the examples.

Thank you.

**Comment by tarlepp** [comment]
Actually this project don't need any extra CSS files, because we are just using bootstrap styles.

**Comment by tarlepp** [comment]
And what you need for this project is only that ```bootbox.min.js``` or ```bootbox.js``` which is used if you are using bower.

**Comment by makeusabrew** [comment]
@tarlepp is correct. This might just be poor documentation. @tiesont has done some work on the docs so we'll see if this is still an issue after they're merged in.
