### ISSUE TITLE
Change the Bootbox button style

### ISSUE THREAD

**Issue by varshavmane** [makeusabrew/bootbox#504]
Hi All,

I have 2 buttons in bootbox pop up and want to change the style as below:
`<div class='buttons-preview' style='cursor:not-allowed;'>
         <a href='javascript:void(0);' class='btn btn-labeled btn-primary'>
                 <i class='btn-label fa fa-check-square-o'></i>Save
         </a>
</div>`

Any pointers?

**Comment by tiesont** [comment]
There is an example for doing this in the documentation, as seen at http://bootboxjs.com/examples.html#bb-confirm-dialog
