### ISSUE TITLE
Bootbox jumps to bottom.

### ISSUE THREAD

**Issue by dutchiexl** [makeusabrew/bootbox#505]
When I open a bootbox, it fades in an scrolls from the top. but when the animation is finished the bootbox jumps to the bottom. So you have to scroll up to get to the top of the modal.

it's like the `top: 0;` css parameter is ignored.

**Comment by dutchiexl** [comment]
It seems this is the problem:

```    dialog.on("shown.bs.modal", function() {
      dialog.find(".btn-primary:first").focus();
    });
```

Is there a way to disable this ?

**Comment by makeusabrew** [comment]
@dutchiexl could you provide an example jsFiddle link or similar demonstrating this please?
