### ISSUE TITLE
Check if bootbox script was loaded

### ISSUE THREAD

**Issue by ivanhalen** [makeusabrew/bootbox#506]
Hello,
I'd like to have a fallback with a standard confirm box in case Bootbox script is not loaded for some reason: I wrote something like:
```
if (jQuery().bootbox) {
    ...
} else {
    [fallback here]
}
```
but it doesn't work... I used with success the `if (jQuery().plugin_here) ` stuff with other plugins, but with bootbox it doesn't seem to work

When I write `alert(jQuery().bootbox)` I get `undefined`

Please, any help? Thanks

**Comment by CristianH033** [comment]
bootbox is a object:

`if(bootbox){
   console.log("loaded");
}else{
   //not loaded
}`

**Comment by ivanhalen** [comment]
Thanks Cristian, but seems that my console keeps reporting this: `ReferenceError: bootbox is not defined`

This is my simple script:
```
<script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
<script>
$(function() {
  if (bootbox){
	alert('hello');  
  }
});
</script>
```

**Comment by makeusabrew** [comment]
@ivanhalen use either:

`if (window.bootbox) {} `

Or

`if (typeof bootbox !== "undefined") {}`

Cheers,

Nick
