### ISSUE TITLE
bootbox via npm install " bootbox is not defined "

### ISSUE THREAD

**Issue by ezekel** [makeusabrew/bootbox#507]
I installed bootbox via npm and I used this code 

```
 bootbox.alert("Hello world!", function() {
        console.log("Alert Callback");
    });
```

but it doesn't work I get error " bootbox is not defined ", how to require bootbox if I installed via npm ?

**Comment by makeusabrew** [comment]
Hi @ezekel - could you provide a more complete example of your surrounding code, including how you're importing bootbox into the current scope?

**Comment by mioo** [comment]
> npm i bootbox --save-dev

```javascript
var bootbox = require('bootbox');
bootbox.alert("Hello world!");
```
or

```javascript
require('bootbox');
bootbox.alert("Hello world!");
```

> in console panel
>ReferenceError: bootbox is not defined

**Comment by Shoaib-khawar** [comment]
check your Layout page where jquery scricpts rendered

**Comment by dlowhorn** [comment]
I know this was closed, but I had the same issue, and the answer was to use import instead of require:

```
import bootbox from 'bootbox';
bootbox.alert('hello, world');
```

**Comment by odura** [comment]
Perhaps a solution helps for a bootbox npm installation with a message in your browser

> bootbox is not defined

Instead of basically writing
`require('bootbox');`
below works for me :
`window.bootbox = require('bootbox');`

**Comment by genpas** [comment]
> bootbox is not defined

With symfony and Encore/Webpack, just add in your app.js
`global.bootbox = require('bootbox');`

**Comment by codepushr** [comment]
@genpas Doesn't work for me, I'm still getting `"$.fn.modal" is not defined;`. Can you share a bit more of your setup? Like imports, dependencies...

**Comment by Basher7** [comment]
after include

> "**/*.d.ts"
in tsconfig.app.json and tsconfig.spec.json my problem is solved
