### ISSUE TITLE
Button Icon

### ISSUE THREAD

**Issue by mehmetalidumlu** [makeusabrew/bootbox#508]
Hi,
Can we put span before button text? 

Standart Button: `<button data-bb-handler="success" type="button" class="btn btn-success">Save</button>` 

With Span: `<button data-bb-handler="success" type="button" class="btn btn-success"><span class="my_class_name"></span>Save</button>`

**Comment by tiesont** [comment]
Yes.

**Comment by mehmetalidumlu** [comment]
How? :)

**Comment by mehmetalidumlu** [comment]
How? :) @tiesont

**Comment by tiesont** [comment]
Here's an [example of a confirm with icons]( https://jsfiddle.net/t7oq663u/):

```
  bootbox.confirm({
    title: "Your Title",
    message: "Does this make sense?",
    buttons: {
      cancel: {
        label: '<i class="fa fa-times"></i> Cancel'
      },
      confirm: {
        label: '<i class="fa fa-check"></i> Confirm'
      }
    },
    callback: function(result) {
      /* your callback code */
    }
  });
```

**Comment by mehmetalidumlu** [comment]
Thanks, I had hoped it has icon parameter. I put icon class with another way.
As fallows... 

  ```
bootbox.confirm({
    title: "Your Title",
    message: "Does this make sense?",
    buttons: {
      cancel: {
        label: 'Cancel'
        icon: 'fa fa-times'
      },
      confirm: {
        label: 'Confirm',
        icon: 'fa fa-check'
      }
    },
    callback: function(result) {
      /* your callback code */
    }
  });
```

**Comment by tarlepp** [comment]
Icon support sounds like a good idea... but it should also support other icon libraries than font-awesome, eg. mdi and what about svg icons + tons of more similar libraries?

Could you make a PR about this feature request?

**Comment by tiesont** [comment]
@tarlepp Would the assumption be that the icons are applied via CSS classes (a la Glyphicons, Font Awesome, et cetera.)? Or, would it make sense to have some sort of plugin, where you specify the key for your chosen icon, and the plugin file is responsible for how the icon gets injected?

As an example for the second, say I had a file I called icons.fa.js, which looks something like:

```
/* container code omitted */
...
check = function(){ return '<i class="fa fa-check"></i>'; }
...
/* container code omitted */
```

This would called like
```
buttons: {
      confirm: {
        label: 'Confirm'
        icon: icon.check
      }
```
