### ISSUE TITLE
Callback for buttons not working after modal('hide');

### ISSUE THREAD

**Issue by ironicnet** [makeusabrew/bootbox#512]
I have the following code: http://jsfiddle.net/9L7essf0/4/

The first time you open the dialog it works great.
But the second time you open it, the callback of the buttons gets lost and stops working

**Comment by makeusabrew** [comment]
This is as designed; you don't really want dialogs hanging about after they're dismissed. Just create a new one each time you want to show it.

**Comment by hanishsingla** [comment]
@makeusabrew I don't think this always true. Sometimes, we need multiple dialog boxes working in conjugation with each other.

Please have a look at this case http://jsfiddle.net/9L7essf0/6/

**Comment by tiesont** [comment]
@hanishsingla Please open a new issue if you think this behavior is incorrect, but I seriously doubt that we're going to change the lifetime of Bootbox objects at this time.

**Comment by hanishsingla** [comment]
@tiesont It may not be possible to change its behaviour like this but I think there should be some way to support this case.
