### ISSUE TITLE
Pressing enter two times, calls the callback function two times

### ISSUE THREAD

**Issue by goblinbr** [makeusabrew/bootbox#514]
When you press enter two times really fast the callback function is called two times.

Also occurs when you click two times the confirm button

Example: https://jsfiddle.net/2399n2z8/

I am using Chome 50.0.2661.94 m , also tested with Firefox 43.0.1

**Comment by emileber** [comment]
I'm experiencing this exact problem.

**Comment by emileber** [comment]
Also, spamming the OK button with the mouse calls the callback multiple times.

**Comment by emileber** [comment]
As a workaround, you can set a flag when closing the modal and reset it on `hidden.bs.modal` event.

```javascript
var flag = false;
bootbox.confirm("Confirm?", function(conf) {
        if (conf && !flag) {
            flag = true;
            /* ... */
        }
    })
    .on("hidden.bs.modal", function() {
        flag = false;
    });
```

**Comment by emileber** [comment]
Or as a fix, you can add this snippet somewhere to override bootbox's `dialog` function:

```javascript
/**
 * Prevent multiple callback calls when spamming click, 'enter' or 'esc'.
 */
bootbox.dialog = (function(dialog) {
    return function(options) {
        var modal = dialog(options);
        modal.on("hide.bs.modal", function() {
            modal.off("click escape.close.bb");
        });
        return modal;
    };
})(bootbox.dialog);
```

**Comment by makeusabrew** [comment]
Definite bug which needs addressing - thanks.

**Comment by emileber** [comment]
@makeusabrew The last release is dating, when is the next patch/minor release planned?
