### ISSUE TITLE
Footer buttons not aligned

### ISSUE THREAD

**Issue by tepaleguiojo** [makeusabrew/bootbox#516]
Hi,

I used bootbox.dialog() to create a confirm box. The modal is working but the first button on the footer is not aligned to the next 2 buttons. 

How can I align the first button?

![screen shot 2016-05-19 at 4 30 53 pm](https://cloud.githubusercontent.com/assets/1028892/15387558/5ad41350-1de0-11e6-9b86-d389ba79ac55.png)

Bootbox: 4.4.0
jQuery: 2.2.3
Bootstrap: 3.3.5

**Comment by tiesont** [comment]
Please post a jsFiddle or similar demonstrating the issue, otherwise it's going to be difficult to make any reason suggestion.

Bootbox does have a [built-in confirm helper](http://bootboxjs.com/documentation.html#bb-confirm-dialog) - is there something that prevents you from using it?

**Comment by makeusabrew** [comment]
As @tiesont has mentioned, a jsFiddle or similar would help here. Thanks 👍
