### ISSUE TITLE
how to create button with loop

### ISSUE THREAD

**Issue by DevMakoto** [makeusabrew/bootbox#518]
var dataBox = {
  "titulo": "Hola soy un titulo",
  "mensaje": "hola soy el mensaje",
  "class": "modal-info",
  "boton": [
    {
      "id": "ACEPTAR",
      "icono": "fa-check",
      "label": "ACEPTAR",
      "class": "btn-saco",
      "callback": "funcion();funcion2();"
    },
    {
      "id": "CANCELAR",
      "icono": "fa-times",
      "label": "cancelar",
      "class": "btn-danger",
      "callback": "funcion();funcion2();"
    }
  ]
};

        bootbox.dialog({
            title: dataBox.titulo,
            message: dataBox.mensaje,
            className: dataBox.class + ' modal-center',
            buttons: {
                for(var i=0; i<dataBox.boton.length; i++){

                }
            }
        });

view error in console, help

**Comment by tarlepp** [comment]
example plunker would be nice.

**Comment by tiesont** [comment]
So, what is the error?

I would assume you would have to build up the buttons object outside of the dialog option.

**Comment by tarlepp** [comment]
Actually I don't see the point ot loop those buttons, why don't you just assign those like:

```
buttons: dataBox.boton
``` 

Another thing that I see which is propably wrong, is those callbacks for those buttons. Callback should be a callable callback, not string which contains n functions.

**Comment by tarlepp** [comment]
With that seems to work, and no errors to console. Example in plunker https://plnkr.co/edit/aKrfALot0O8cLdO7rJHT?p=preview

**Comment by makeusabrew** [comment]
Thanks @tarlepp. Closing to keep things tidy as not a Bootbox issue per se.
