### ISSUE TITLE
Selectbox not working in bootbox

### ISSUE THREAD

**Issue by BramCrins** [makeusabrew/bootbox#521]
Hello,

When i try to select a value form a selectbox which is openend by bootbox dialog it wil return always the first element. Nomather what is choose.

Here is a fiddle to show my point [jsFiddle](http://jsfiddle.net/3tbqwhg2/2/)

**Comment by makeusabrew** [comment]
You've got multiple elements sharing IDs on the page; the hidden template, and the copied contents shown in the modal. Thus when you alert() the value you're getting the first matching identifier's value, which is your hidden HTML.
