### ISSUE TITLE
Custom labels buttons 

### ISSUE THREAD

**Issue by crmmvio** [makeusabrew/bootbox#522]
not working the call through labels for the buttons, follow example and reference, from what I could see this work in version 2.x, could reactivate this feature is very useful in my opnion.

Sample of Calls:
alert
bootbox.alert("Custom label text!", "Very good.");

dialog
bootbox.confirm("Are you sure?", "No way!", "Yes, definitely!", function(result) {
    console.log("Confirmed? "+result);
 });

Ref: [http://paynedigital.com/articles/2011/11/bootbox-js-alert-confirm-dialogs-for-twitter-bootstrap]

**Comment by tiesont** [comment]
Are you asking how to change the text on the confirm buttons? That has been covered before.

**Comment by tarlepp** [comment]
@crmmvio also you could provide plunker to demonstrate your problem so that we can help you solve that problem easier.

**Comment by makeusabrew** [comment]
Closing, hopefully @tiesont's new docs will help
