### ISSUE TITLE
message element removed after dialog hidden？

### ISSUE THREAD

**Issue by 1120101929** [makeusabrew/bootbox#523]
I use an element as message in dialog. And I noticed that the message element was removed after the dialog hidden. But there are times when I want to reopen the dialog with the same element as message, and I will get an error then.
One approach is that let the developers determine whether to remove the element or not. For example, providing an option such as 'removeMessage', and do not remove the element when the option is set to false.
PS: Thanks for your work, it's really really helpful.

**Comment by makeusabrew** [comment]
Hi; you can either `clone` the object or simply re-create it when showing a new dialog.
