### ISSUE TITLE
Input type file Not working

### ISSUE THREAD

**Issue by hanynasyr** [makeusabrew/bootbox#526]
When submitting a form, all inputs are submitted but file input is not in the form data!

**Comment by tiesont** [comment]
Example, please? I assume you're using a custom dialog? Did you use the correct `enctype` (`multipart/form-data`) in your form?

**Comment by makeusabrew** [comment]
Unlikely to be a Bootbox issue, but as @tiesont states an example will help clarify :)

**Comment by tiesont** [comment]
Closing, since no example has been provided.
