### ISSUE TITLE
Header is scrolled down when 

### ISSUE THREAD

**Issue by sandip12081992** [makeusabrew/bootbox#528]
![image](https://cloud.githubusercontent.com/assets/18065414/17273576/a4b36c20-56d7-11e6-964c-62008c992a5b.png)

Header is scrolled down when modal is long.

`function createBootboxModal(title, modalHtml) {
    bootbox.dialog({
        message: modalHtml,
        title: title,
        closeButton: false,
        size: 'large',
        buttons: {
            main: {
                label: 'close',
                className: 'btn-primary',
                callback: function () {
                    $('#modalPopUpDiv').modal('hide');
                }
            }
        }
    });

}`

**Comment by tiesont** [comment]
It looks like you have two active modals. If that's the case, you're doing something that [Bootstrap doesn't support](http://getbootstrap.com/javascript/#modals).

**Comment by makeusabrew** [comment]
Thanks @tiesont. This is definitely a usage / Bootstrap issue.
