### ISSUE TITLE
Preventing default dismissal behaviour

### ISSUE THREAD

**Issue by Saldash** [makeusabrew/bootbox#530]
Hi,

Is there a way I can manually control whether the modal is dismissed or not?
I have a custom modal with an embedded form, and I need the modal button to do some background work and form validation before dismissing the form, or if the ajax call doesn't return a value I'm looking for, keep the modal as is on screen.

I use an ajax GET request to get the HTML markup for the form.
And the callback definition for the create button in the modal has an ajax POST request.

I need the modal to stay on screen when the create button is pressed so I can dismiss the modal myself in a controlled manner.

**Comment by tiesont** [comment]
Add a `return false` from the callback for the button. You will then need to manually close the dialog. You'll need a reference to the dialog object, somewhat like [this](https://tiesontrowbridge.com/bootbox/examples.html#bb-custom-dialog):

    var dialog = bootbox.dialog({
        buttons: {
            ok: {
                label: 'Send', 
                callback: function(){
                    /* your other code */

                     return false;
                }
        }
    });

    // do something in the background, then

    dialog.modal('hide');
