### ISSUE TITLE
Two bootbox calls after another cause margin issue.

### ISSUE THREAD

**Issue by otterslide** [makeusabrew/bootbox#531]
I have one bootbox.confirm and another .alert immediately following.

If I don't set a timeout, the confirm doesn't get a chance to close, and the alert opens.
This causes the body to receive a 17px padding to the right which never goes away.

Any ideas how I can wait until the first closes until the second opens other than with a timeout?.. It seems when the "OK" button is pressed, I receive the event right away, even before the modal gets a chance to close.

**Comment by tarlepp** [comment]
Custom callback function on button should work just fine.

**Comment by otterslide** [comment]
I'm using  bootbox.confirm(msg, function (result) {}); Is this what you mean?

So when I click "Ok", The call comes into my function even before the bootbox has had a chance to close. My code opens another one to display another message, and that's when the problem happens.

**Comment by tiesont** [comment]
If you want one dialog to open after another dialog closes, you'll want to handle the `hidden.bs.modal` event. Something like:

```
var dialog = bootbox.confirm({ /* your options */ });

dialog.on('hidden.bs.modal', function(){ 
    bootbox.alert({ /* your options */ });
});
```

If you only need to open the alert if something specific happens, you'd probably want to create a variable outside of the confirm's callback, and then check that in the hidden event:

```
var shouldDoSomething = false;
var dialog = bootbox.confirm({ 
    /* your options */,
    callback: funtion(result) {
        shouldDoSomething = result; // obviously, replace this with your logic
    }
});

dialog.on('hidden.bs.modal', function(){ 
    if(shouldDoSomething){
        bootbox.alert({ /* your options */ });
    }
});
```

**Comment by makeusabrew** [comment]
Or just get a bit dirty and use a `setTimeout` in the original callback. Either will work :).
