### ISSUE TITLE
Optional buttons

### ISSUE THREAD

**Issue by Saldash** [makeusabrew/bootbox#532]
Hi,

I've had a read about and can't see anything on this so I'll ask.
Is there a specific reason that buttons are required?

There is a case in a current project I'm working on where having a footer button simply isn't necessary.
All I'd like to do is have an informational dialog with only the x-button top right, and trigger a function as the modal is dismissed.

Is there a way to ignore creating a footer if no buttons object is passed?

**Comment by tiesont** [comment]
If you don't add any buttons, the footer isn't created. I have [an example of this here](https://tiesontrowbridge.com/bootbox/examples.html#bb-custom-dialog).

If you're seeing a footer, it would be useful if you could provide an example of how you're constructing your dialog.

**Comment by Saldash** [comment]
I hadn't tried not putting a buttons object in as the documentation has the buttons object marked as required. 

I'll give that a go in the morning as I'm not near my workstation at the moment.
If the buttons object is truly optional already, maybe the documentation could be updated to reflect as much?

Any idea how I might capture the x button being triggered?

**Comment by tarlepp** [comment]
just use that button callback function to identify it.

**Comment by tiesont** [comment]
@Saldash Are you specifically targeting the 'x' button being clicked, or just the modal closing? If the latter, it's helpful to remember that Bootbox is just a wrapper over Bootstrap modals, so you have access to [the modal events](http://getbootstrap.com/javascript/#modals-events). Something like:
```
var dialog = bootbox.dialog({ /* options here */ });

dialog.on('hidden.bs.modal', function(){ 
    /* This is called when the CSS animation to hide the modal has completed */  
});
```
See [https://jsfiddle.net/hfy80198/](https://jsfiddle.net/hfy80198/)

@tarlepp The callback doesn't appear to be called on a custom dialog, unless I'm missing something.

**Comment by tiesont** [comment]
@Saldash Yes, the docs are a bit misleading. That's my fault; when I volunteered to revamp the documentation a while back, I seem to have misunderstood some of the options. I have an open pull-request to fix that (and hopefully present the content better); in the meantime, I've been hosting my proposed updates [here](https://tiesontrowbridge.com/bootbox/documentation.html).

**Comment by tiesont** [comment]
You can also supply a function to the `onEscape` function, like so:
```
var dialog = bootbox.dialog({
    message: "<b>Hello!</b> I am a dialog.",
    onEscape: function() {
        console.log('I was called onEscape!')
    }
});
```
See https://jsfiddle.net/hfy80198/1/
