### ISSUE TITLE
Default Value for Backdrop

### ISSUE THREAD

**Issue by boldtrn** [makeusabrew/bootbox#533]
Hi,

I am pretty happy using Backdrop, however I have one request, do you think it would be worthwhile to setup the Defaults of Bootbox the same as it's with Bootstrap. If I click outside of a Bootstrap Modal, it closes by default. The same should apply for Bootbox, IMHO.

Best,
Robin

**Comment by tiesont** [comment]
Bootbox's primary goal is to serve as Bootstrap replacements for the native dialogs (alert, prompt, and confirm). Native dialogs do not close on clicking the background.

**Comment by boldtrn** [comment]
@tiesont I think you are right, sorry. I think we can close this issue.
