### ISSUE TITLE
Close a single bootbox within eval'd ajax response

### ISSUE THREAD

**Issue by maddo7** [makeusabrew/bootbox#536]
Hello,
I'm using bootboxes to interact with the website through ajax calls.
If an error occurs the bootbox should stay open and display the error somewhere within the HTML code, if everything went well, it should close.

Usually my code looks like this:

`bootbox.dialog({
  title: "Enter your Username",
  message: 'Username: <input type="text" id="username"><div id="username-response"></div>',
  buttons: {
                    success: {
                        label: "Check Username!",
                        className: "btn-success",
                        callback: function () {
                        	var username = $("#username").val();
                        	if(username == "") {
                        		alert("Please enter a username!");
                        		return false;
                        	}		
                        	$.post("check_username.php",{"u" : username},function(data) {
                        		eval(data);
                        	});
							return false;
                        }
                    }
                }
 });`

At the end there is a return false; to keep the bootbox open.

Now check_username.php can either return an error like `$("#username-response").html("Error, username taken");` or it should contain code to close the bootbox because it was successful. In this case I usually use `bootbox.hideAll();`.

Now there's a problem when I have multiple bootboxes that this will close them all instead of the corresponding bootbox. Is there a way to close a corresponding bootbox from the code that gets returned by check_username.php?

**Comment by tiesont** [comment]
This is covered [in the documentation](http://bootboxjs.com/documentation.html#bb-method-hideAll), but basically, store a reference to the Bootbox object:

`var mydialog = bootbox.dialog({ /* your options */ });`

When you want to close it, call the Bootstrap modal function with the `'hide'` argument:

`mydialog.modal('hide');`
