### ISSUE TITLE
backdrop in dialog option section of docs doesn't mention custom dialogs

### ISSUE THREAD

**Issue by lmj0011** [makeusabrew/bootbox#537]
stemming from https://github.com/makeusabrew/bootbox/issues/456

There should be a note in the docs for `backdrop`, that the `onEscape` option must be set to true in order for "dismissing modal by clicking on the background" to work with custom dialog boxes.

Took me an hour to figure this out. Only way you would find this out is if you read the options starting from the first one and going down the list.

http://bootboxjs.com/documentation.html#bb-dialog-options

there's a pull request already for this: https://github.com/makeusabrew/bootbox/pull/509/commits/310f01f3ec4f521dd44b8e9eb817c6c55e7a1eca

**Comment by tiesont** [comment]
@makeusabrew I can confirm this, as seen with https://jsfiddle.net/x67mq15L/ and https://jsfiddle.net/x67mq15L/1/ - is this by design? If so, I can update the docs.

**Comment by makeusabrew** [comment]
Yes; it's by design. See my reasoning in #395 and #402.

**Comment by tiesont** [comment]
This has been noted in the updated documentation. Thank you!
