### ISSUE TITLE
Custom Animation

### ISSUE THREAD

**Issue by ghimawan** [makeusabrew/bootbox#539]
Is it possible to add custom animation in <div class="modal-dialog"> like below URL?
[http://codepen.io/max_blue/pen/PzyYLL]

It will be great if there are additional bootbox option/params to do that. Thank you.

**Comment by tiesont** [comment]
I'm not sure how useful of a feature this would be to the general user of Bootbox. However, all of the Bootbox functions return a jQuery object on which that you can call the underlying Bootstrap functions, so you can use the same logic as in your linked codepen:
```
function testAnim(x) {
    $('.modal .modal-dialog').attr('class', 'modal-dialog  ' + x + '  animated');
};

// works the same with bootbox.confirm, bootbox.prompt, or bootbox.dialog
var dialog = bootbox.alert({ /* your options */ }); 

dialog.on('show.bs.modal', function (e) {
  var anim = $('#entrance').val();
      testAnim(anim);
})

dialog.on('hide.bs.modal', function (e) {
  var anim = $('#exit').val();
      testAnim(anim);
})
```

**Comment by ghimawan** [comment]
Thank you for your help. I've try your code and work for 'on hide', but not work for 'on show'.
Could you help me again?

Here the URL for my updated code:
[http://codepen.io/ghimawan/pen/vXYYOz]

Thanks.

**Comment by ghimawan** [comment]
Hi, I actually made it to make animation for on show.
It just use:
`
		var anim = $('#entrance').val();
`
`
		$(".modal .modal-dialog").attr("class", "modal-dialog " + anim + "  animated");
`

Here the URL for my updated code:
 [http://codepen.io/ghimawan/pen/vXYYOz]

Thanks.

**Comment by tiesont** [comment]
You can actually get the same behavior just using the `className` option on the dialog:
```
bootbox.alert({
    message: "This is an alert with an additional class!",
    className: 'rubberBand animated'
});
```
I haven't tested that extensively, so there may be times when applying the class to the `.modal-dialog` makes more sense than the wrapping `.modal`, but it's an interesting idea.

**Comment by makeusabrew** [comment]
Don't want to bloat the core library with this I'm afraid.
