### ISSUE TITLE
Setting `locale` in options object is not applied prior to button creation

### ISSUE THREAD

**Issue by tiesont** [makeusabrew/bootbox#542]
The `locale` option can technically be set on a bootbox object, but the value is not being used when constructing the dialog buttons. 

It appears to be the case that the button template is built before the `options.locale` value is updated. Placing a simple `console.log(options)` just before `dialog.modal("show");` is called shows that the locale value has been set to whatever value was passed into the function, but the button text values do not reflect that locale value. 

For example, this:
```
bootbox.confirm({
    locale: 'fr',
    message: "This is a confirm with a French locale! Do you like it?",
    callback: function (result) {
        Example.show('This was logged in the callback: ' + result);
    }
});
```
will create a confirm with English buttons, but the console will show a value of 'fr' for `options.locale`.

**Comment by tiesont** [comment]
I can get the locale to set if I add this to `mergeDialogOptions`:
```
if (args[0].locale) {
    defaults.locale = args[0].locale;
}
```
This doesn't seem right, though, because then it acts the same as `setLocale`. I assume what needs to happen is to adjust the `createLabels` function to also accept `locale` as a parameter, so that it can lookup the correct labels.

**Comment by Mithgol** [comment]
This is a comment that would bring this issue not only to my https://github.com/notifications/ page (like the “Subscribe” button does), but also to my https://github.com/notifications/participating page (to raise awareness).

This comment does not serve any other purpose. Therefore you may ignore it.

**Comment by tiesont** [comment]
@makeusabrew Should the locale be able to be set as an option? If so, should it be persistent, or only for the current dialog? If not, I need to remove locale from the options grid in the documentation.

**Comment by makeusabrew** [comment]
At present `locale` isn't _meant_ to be supported as an argument to any of the dialog methods - the idea is to use the global `setLocale` method instead. The fact it looks like it could be an option is really just a combination of some legacy code and some newer code between different releases. It boils down to the fact that `defaults` are indeed just defaults, but they're not necessarily things you can override per method call. They're just some sensible defaults for the library which you can override in different ways.

To be honest, the locale stuff has been inadequate for quite a while now and probably needs redoing anyway.

@tiesont for now it'll need removing from the options grid as it's not the intended use.

**Comment by tiesont** [comment]
@makeusabrew Done. Thanks for the clarification.
