### ISSUE TITLE
bootbox.prompt does not work as expected as stated in the API documentation

### ISSUE THREAD

**Issue by mondwan** [makeusabrew/bootbox#543]
Original post is #450.

According to document here, prompt accepts `message` and `title`. However, only `title` work.

Fiddler [here](https://jsfiddle.net/Gzagv/44/)

As the previous post, there is pending pull requests #397 and identical requests on #230 talking about same issues

**Comment by tiesont** [comment]
Documentation will be updated/corrected at some point, probably as soon as I get my pull-request squared away. You can see a work-in-progress, with the updated prompt docs, here: https://tiesontrowbridge.com/bootbox/documentation.html#bb-prompt-dialog

**Comment by mondwan** [comment]
Great. It clarifies the problem.

However, may I know why `message` is not allowed for `prompt()`?

In the last post, you have mentioned about disallowing message is because
of avoiding misleading inputs from developer (eg dialog in dialog).

Would it be nice for adding a check or allowance for simple text around the
input box provided by prompt?

Sometimes a little description or hint can better address the purpose of
prompt() addition on a single title

Thanks

2016年9月24日 14:34，"Tieson Trowbridge" <notifications@github.com>寫道：

**Comment by tiesont** [comment]
I would agree - I would prefer to be able to prepend a message to, say, a prompt with a textarea. That isn't how it's coded, though, so that's a question for @makeusabrew - there's a reason it's not allowed, and I would assume it was causing more problems than allowing it solves.

It's not optimal, but if you really want to use prompt instead of building a custom dialog, you can do something like [this](https://jsfiddle.net/z0qs6g7e/):
```
var dialog = bootbox.prompt({
  title: 'Some title',
  callback: function(result) {

  }
});

dialog.on('shown.bs.modal', function() {
  dialog.find('.bootbox-body').prepend('<p>Some extra text</p>')
});
```
or [this](https://jsfiddle.net/z0qs6g7e/1/):
```
bootbox.prompt({
  title: 'Some title',
  callback: function(result) {

  }
}).find('.bootbox-body').prepend('<p>Some extra text</p>');
```

**Comment by makeusabrew** [comment]
I've always objected purely because Bootbox's guiding principle is to follow the native methods it replaces as closely as possible. What stops you putting whatever you want to put in 'message' in the title of the prompt?

**Comment by tiesont** [comment]
@makeusabrew I'll put together some updated verbiage for the documentation (to explain why prompt works as it does), and add a version of the above code to the examples page. Sound good?

**Comment by makeusabrew** [comment]
Sure; but as I said I'm genuinely curious what it is about prompt which doesn't currently fulfil people's needs; I've no desire to be stubborn about its functionality if there's a genuine need for change.

**Comment by mondwan** [comment]
Ummm, how about a description about the required value format?

For example, prompt showing a title with input your name and there is a
description about name we accept alphanumeric only under or above the input
box?

2016年9月28日 16:59，"Nick Payne" <notifications@github.com>寫道：

Sure; but as I said I'm genuinely curious what it is about prompt which
doesn't currently fulfil people's needs; I've no desire to be stubborn
about its functionality if there's a genuine need for change.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/makeusabrew/bootbox/issues/543#issuecomment-250111141>,
or mute the thread

**Comment by makeusabrew** [comment]
Okay; input restrictions / validation is one (pretty strong argument), but not necessarily as a freeform 'message' parameter (since that won't actually restrict or validate anything). Any others?

**Comment by mondwan** [comment]
How about a disclaimer or warning?

For example, deleting a github repository will require you to enter the
name of repository for confirmation. In that box, there is a warning
statement about this cannot be undone.

It will be awkward if adding such statement into the title.

2016年9月28日 17:50，"Nick Payne" <notifications@github.com>寫道：

**Comment by makeusabrew** [comment]
True enough. Probably does merit adding.

**Comment by tiesont** [comment]
Would the primary reason be to bring the prompt in line with the other dialogs (which do allow both title and message)? If not, the use case above *could* be accomplished with [what I noted before](https://github.com/makeusabrew/bootbox/issues/543#issuecomment-249350685). I'm not against it, and it would simplify the process a bit.

Otherwise, would we just need an admonishment in the docs that any form controls added to `message` will be ignored?

**Comment by djmattyg007** [comment]
You could use `$('selector').text()` instead of `$('selector').html()` for `message` inside of a prompt.
