### ISSUE TITLE
Bootbox dialog with closing timeout

### ISSUE THREAD

**Issue by Wmas** [makeusabrew/bootbox#547]
This is not an issue but merely a question.
I didn't know where to post this, so my excuses for that.

I am using the bootbox previous version which does his job perfectly. A time ago I was in the need to use a message which has to be closed after a predefined time.

Someone (sorry if I don't remember the name anymore) added a pul-request adding this to your code:

bootbox.dialog({
        message  : ''The data has been successfully deleted.',
        timeOut : 3000
}); 

This is really handy.
Because I am using this functionality extensively I am wondering if you still have this option in the new updated version?

Thank you

N.B. - sorry again for posting this in the issues

**Comment by tiesont** [comment]
No, this is not something in the current library. You could wrap a setTimeout into a helper function, though:
```
function growl(message, milliseconds){
    var dialog = bootbox.dialog({ 
        message: message 
    }); 

    setTimeout(function(){ 
        dialog.modal('hide');
    }, milliseconds);
}
```

and then you would use it like:
```
growl("The data has been successfully deleted.", 3000);
```
If you always wanted to use the same timeout value, just omit the milliseconds parameter and hard-code the value you want.

Demo: https://jsfiddle.net/z4onq1b5/
