### ISSUE TITLE
Change "close" icon

### ISSUE THREAD

**Issue by stefdelec** [makeusabrew/bootbox#548]
Hi,

Thank for you work.

I'd like to change the "close-icon", in the top right corner. I ve read the doc, I can't understand how I can change it. 
 ```
var defaultoption={
        message:  dataLang.bootbox.message,
        title: "UN TITRE?",
        closeButton: {
            icon: "icon-ok-sign ???????????????????????????????"
        },   
        buttons: {
            confirm: {
                label: dataLang.bootbox.labelYes,
                className: "btn-validate",               
            },
            cancel: {
                label: dataLang.bootbox.labelNo,
                className: "btn-unvalidate btn-outline"
            },
          
                   
        }
    }
```

**Comment by tiesont** [comment]
`closeButton` is not for setting the icon - it takes a Boolean value indicating whether to show the button or not. 

There currently isn't an option for changing the icon. If you really, really need to, you would need to clone the project and change line 52.
