### ISSUE TITLE
How can I use bootstrap's modal events?

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [makeusabrew/bootbox#551]
I tried this code

``` JAVASCRIPT
bootbox
    .alert('Message')
    .on('show.bs.modal', function (e) { alert('showing') })
```

but the event is ignored. How can I use events?

**Comment by tiesont** [comment]
`show` seems to happen earlier than hooking into the jQuery/Bootbox object can allow. You *can*, however, [hook into the `shown.bs.modal` event](https://jsfiddle.net/e1h1c1vn/).
```
bootbox
    .alert('Message')
    .on('shown.bs.modal', function (e) { alert('showing') })
```

There is also the `.init` function you can call, which should run just prior to the modal being shown: http://bootboxjs.com/documentation.html#bb-function-init

[You would use it like so](https://jsfiddle.net/e1h1c1vn/1/):
```
 bootbox
    .alert('Message')
    .init('function (e) { alert('showing') })
```

**Comment by djmattyg007** [comment]
Like this:

    var modal = bootbox.alert({
        message: "My Message",
        show: false
    });
    modal.on("show.bs.modal", function(e) { console.log("show!"); });
    modal.modal("show");
