### ISSUE TITLE
Modal box in center

### ISSUE THREAD

**Issue by Sarfroz** [makeusabrew/bootbox#552]
Hello sir how can i show the modal box  in center of page.

Also is there way to make corners square instead of rounded.
Thanks

**Comment by tiesont** [comment]
I would suggest reading https://github.com/makeusabrew/bootbox/blob/master/CONTRIBUTING.md

That being said, to get square corners, you would either need to override the default Bootstrap CSS,
```
.modal-content
{
    border-radius: 0 !important;
}
```
or use the `className` option, and then override the CSS for just the current modal:
```
.square-modal .modal-content
{
    border-radius: 0 !important;
}
```
with
```
bootbox.alert({
    message: "It's hip to be square!",
    className: 'square-modal'
});
```

Vertically-centering a modal isn't trivial, but this seems to more or less work: https://codepen.io/dimbslmh/full/mKfCc

**Comment by tiesont** [comment]
Bootbox 5 will have this option if the user is using Bootstrap 4 - see https://github.com/twbs/bootstrap/issues/24439
