### ISSUE TITLE
options.pattern won't work for prompt

### ISSUE THREAD

**Issue by SleepWalker** [makeusabrew/bootbox#554]
Hello,

when you specify `options.pattern` for prompt it will have no effect, when user click on confirm button (because confirm button won't trigger form submit and therefore validation). The validation will work only, when user presses enter inside input:

``` js
bootbox.prompt({
    title: "This is a prompt with a date input!",
    pattern: '^[a-z]{2}$',
    callback: function (result) {
        console.log(result);
    }
});
```

Bootbox v4.4.0

**Comment by tiesont** [comment]
@makeusabrew I can confirm this: https://jsfiddle.net/aknwe3ej/. I can work on a patch - for now, I'll let the browser handle displaying the error message, unless we want a browser-agnostic implementation.

**Comment by tiesont** [comment]
@SleepWalker I'm not jazzed about the changes I've made to get this workaround, but does this fiddle seem to work as expected? https://jsfiddle.net/aknwe3ej/1/

**Comment by SleepWalker** [comment]
It works, but it is too complicated. What do you think about this approach: https://jsfiddle.net/aknwe3ej/2/?

It would be cool to be able to show custom error messages, but this is completely another feature.

**Comment by tiesont** [comment]
@SleepWalker Closer, but a native prompt doesn't require a non-empty input, so I'm not sure if @makeusabrew would want to go that route. Of course, a native prompt doesn't allow you to apply an input pattern or use alternate input types, soooo...

**Comment by SleepWalker** [comment]
I've added a new `options.required`. So it would work as native prompt,
till you specify that option.

**Comment by tiesont** [comment]
@SleepWalker I've been able to make this work, up to not being able to display the native error messages, in the v5 branch without needing to generate a temporary button. Would you be interested in testing [v5x](https://github.com/makeusabrew/bootbox/tree/v5.x), to see if this works for what you need?

**Comment by SleepWalker** [comment]
The problem is that I'm not using your lib anywhere. That PR was created
because I've helped my friend (a long time ago) with form submit issue and
decided to share the code with you. If everything works in v5, this is fine
and the current issue may be simply closed. I don't believe, that I will
find the time to retest the lib, because I don't use it now and probably
won't use in future due to the specific of the projects I'm working on.
Sorry

**Comment by tiesont** [comment]
No worries whatsoever. Thank you for responding.
