### ISSUE TITLE
the multi button example code wont work

### ISSUE THREAD

**Issue by ramteen** [makeusabrew/bootbox#558]
hey guys.

trying this example in my website to test 

> $(document).ready(function() {
		
		function dispModal()
		{
			
			bootbox.dialog("I am a custom dialog", [{
				"label" : "Success!",
				"class" : "btn-success",
				"callback": function() {
					
				}
			}, {
				"label" : "Danger!",
				"class" : "btn-danger",
				"callback": function() {
					
				}
			}, {
				"label" : "Click ME!",
				"class" : "btn-primary",
				"callback": function() {
					
				}
			}]);
	
			
		}
		
		
		dispModal();

		
	});

and it wont work.
I get this error

> bootbox.min.js:6 Uncaught Error: Please supply an object of options(…)

The basic dialog or alert examples work fine though.

can someone please tell me what im doing wrong?

**Comment by tiesont** [comment]
That syntax isn't valid for the current (4.x) version. What version are you using?

**Comment by bmills74** [comment]
Would be nice if the documentation was updated to reflect this

**Comment by tarlepp** [comment]
@bmills74 Hmm, docs are showing that http://bootboxjs.com/examples.html#bb-custom-dialog which docs you refer?

**Comment by tiesont** [comment]
There's also http://bootboxjs.com/documentation.html#bb-option-buttons
