### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by flightsurvey** [makeusabrew/bootbox#559]
Feature request:

As it stands it appears that the user can select OK when no choice has been made in a "Prompt Select".

Could the OK button be disabled until a selection has been made - either that or default to the first option in the list? 

Thanks.

**Comment by tiesont** [comment]
The prompt helper is intended to mimic the behavior of the native prompt, which allows an empty value. If your use-case requires a non-empty value, handle it in the callback. For example:

```
var dialog = bootbox.prompt({
    title: 'What is your name?',
    callback: function(result) {
        if($.trim(result) == "") {
            dialog.find('.bootbox-body').addClass('has-error');            
            return false;
        }
    }
})
```

See it in action: https://jsfiddle.net/cpvdhapz/
