### ISSUE TITLE
Bootbox added at the end of the page instead above the page

### ISSUE THREAD

**Issue by Sicos1977** [makeusabrew/bootbox#561]
Hi,

Does somebody have an idea what is going wrong overhere? For some reason my bootbox dialog is added to the end of the page instead above it.
![25-11-2016 15-08-40](https://cloud.githubusercontent.com/assets/6692947/20627557/21ee3616-b321-11e6-887c-b98129bdda3c.jpg)

**Comment by tiesont** [comment]
I'll need to see something (working code) that reproduces what you're seeing, or this is going to be entirely guesswork.

As a wild guess: you've got some CSS that's conflicting with Bootstrap. The modal has a fixed position, with the actual "dialog" having a relative position to that container.

**Comment by Sicos1977** [comment]
I got it fixed by adding a div with <div style="position: absolute;"> container and put all the layout stuff inside this div. So you were right it indeed had to do with my CSS :+1:

**Comment by user20161119** [comment]
@Sicos1977 could you add snippet to show your resolution,i also have this issue.thanks in advance.

**Comment by Sicos1977** [comment]
I mentioned the solution in my other post on Nov 28. Just paste this html code around your code where you are generating the bootbox.

<div style="position: absolute;">html inside here...</div>
