### ISSUE TITLE
dialog.init function does not work with jquery 1.9.1

### ISSUE THREAD

**Issue by michaelnguyen547** [makeusabrew/bootbox#563]
Demo is @ https://jsfiddle.net/p5pcyt4d/4/

The error is Uncaught TypeError: Cannot read property 'ready' of undefined when using jquery 1.9.1

Works on jQuery 1.11.0

**Comment by tiesont** [comment]
`init` is actually calling the `jQuery.init` function, which is where the error is originating. I'm not sure why it works in a later version, at this point. I'll have to do a diff and see what the differences are.

Depending on your needs, it's possible to use `.on('shown.bs.modal', function() ...)` instead, although that happens after the dialog has been rendered, so you'll see a slight delay in whatever your code is doing.
