### ISSUE TITLE
Required updates for Bootstrap 4 compatibility

### ISSUE THREAD

**Issue by tiesont** [makeusabrew/bootbox#566]
This is what I've found so far, in using Bootbox 4.4 with the **v4-alpha-6** version of Bootstrap 4.

1. Line 59: Checkboxes use a new wrapper and have additional classes. If you want both BS3 and BS4 support, use:
```
"<div class='form-check checkbox'><label class='form-check-label'><input class='form-check-input bootbox-input bootbox-input-checkbox' type='checkbox' /></label></div>"
```

BS3 will ignore (essentially) the BS4 classes, since they don't exist.

2. Line 180: `btn-default` changes to `btn-secondary`, or just use both classes.

3. Line 624: `prepend` must change to `append` - Bootstrap 4 uses flexbox wherever possible, and prepending the button puts it before the header text. This yields the correct order:
```
dialog.find(".modal-header").append(closeButton);
```

Once Bootstrap 4 goes to Beta or better, I'll work on a pull-request to get Bootbox 4.x updated, unless it makes more sense to push this off to Bootbox 5.

**Update post Beta:**

The above changes are consistent with the current Beta release of Bootstrap 4. <s>We still don't have an ETA on either an updated 4.x release or a new 5.x version bump. </s>  <ins>I'm [currently working](https://github.com/tiesont/bootbox) on a v.5 release, although I can't promise when anything will be ready.</ins>

**Comment by Hexodus** [comment]
Would make me happy to see this workable before beta.

**Comment by tiesont** [comment]
@Hexados If you make these changes on a local copy, it works as-is with the current alpha. I don't know when BS4 is supposed to go to beta, nor do I know @makeusabrew's plans for Bootbox going forward.

**Comment by Hexodus** [comment]
Thank you this was indeed very helpful ;) 

Yes it would be cool if @makeusabrew could reveal his plans.  I've got a simple idea. Why not allow the user to define which Bootstrap version should Bootbox use? This would result in just few switches - to have both versions under one hood. Sample code: 

	var defaults = {
		// default Bootstrap version
		bootstrap-version: "3"
	}

	bootbox.setDefaults({
		bootstrap-version: "4" 
	});

	if (options.bootstrap-version == "4")
		//the 3.x code here
	else
		//the 4.x code here

**Comment by tiesont** [comment]
@Hexodus Actually, Bootstrap plugins have had a VERSION property for quite a while, so I actually don't need the user to specify the version. I've gotten this to work reliably in my locale repo, and interestingly enough, the close button / header is the only thing that needs this; since the button and checkbox/radio classes are mutually-exclusive between the versions, you can just add both and the controls will render correctly regardless.

**Comment by firesharkstudios** [comment]
BTW, a rather simple fix for the close button being on the left side of the header text in the Bootbox dialog is to add this CSS...

```
.bootbox .modal-header h4 {
    order: 0;
}
.bootbox .modal-header button {
    order: 1;
}
```

Since the Bootstrap 4 header is using a flex layout and the flex layout allow you to order the child content using the order attribute.  Posting this in case anyone else finds this workaround useful.

**Comment by tiesont** [comment]
@firesharkstudios That is pretty useful, assuming someone is using Bootstrap 4. The v5 branch I'm working on is intended to continue supporting Bootstrap 3, hence the reason I implemented an option to flip the order in which the buttons are appended. 

Good to know going forward, though. Thanks!

**Comment by ray73864** [comment]
Now that Bootstrap 4 has been released, are there any changes that have to be made to BB4 beyond what is listed above?

Or is the current v5 branch in a stable enough position to start using? (Notice it was last updated October 2017).

**Comment by tiesont** [comment]
@ray73864 The v5 branch should be functional at the moment. My fork, where I do the lion's share of updates before pulling in here, is broken at the moment, as I was trying to implement support for the vertical center option that is being added to Bootstrap modals, but probably works (I think the new tests are just not coded properly). 

It would help me very much if someone besides me was using the v5 branch (I use it in some non-mission-critical projects), so that I can find out what the tests might be missing. Be aware, if you use it, that I pulled the locales into separate files. You would need to also include the bootbox.locales.js file, or the matching locales from the locales directory, if you need something other than English.

All other updates are noted in #545 and in the (work in progress) [updated documentation](https://tiesont.github.io/bootbox/documentation.html)

**Comment by gelinger777** [comment]
any news on this?

**Comment by tiesont** [comment]
@gelinger777 Depends on what you mean. This was closed since it's been accounted for in v5, as noted in #545

**Comment by gelinger777** [comment]
when do you plan to release v5?

**Comment by gelinger777** [comment]
@tiesont  thank you very much for your answer. I will keep my eyes on it. 
Thank you for a great plugin.

**Comment by eleenak** [comment]
this was so helpful
