### ISSUE TITLE
Padding after bootbox is closed

### ISSUE THREAD

**Issue by Kappyh** [makeusabrew/bootbox#570]
Hi,

When I call a bootboox alert or confirm in my body appear a "style="padding-right: 15px;" automatically and this not disappear after a I close the bootbox alert/confirm.

Sorry for bad english, but basically bootbox give for a body element one padding-right(with 15px) nonexistent in my css.

**Comment by tiesont** [comment]
This is actually being added by the Bootstrap modal plugin itself, to account for the overlay temporarily "hiding" the scrollbar. What version of Bootstrap are you using? I think this was a monkey patch that's since been removed, if I recall correctly.

**Comment by Kappyh** [comment]
I see...
So I'm using Bootstrap 3.3.7 and Bootbox 4.4.0.
