### ISSUE TITLE
How to capture result of a custom dialog?

### ISSUE THREAD

**Issue by ericscheid** [makeusabrew/bootbox#572]
If I create a custom dialog with `bootbox.dialog (...)` and I pass in a few `<input>` (etc) elements, how do I obtain the values of those `<input>` elements once the user hits the OK button?

I tried using `callback: function(result) {console.log(result)}` but nothing ever shows up.

**Comment by ericscheid** [comment]
A workaround .. use `bootbox.confirm(...)` instead, which does call the `callback` function (and also automatically inserts the OK and Cancel buttons, unlike `bootbox.dialog`).

          dialog = bootbox.confirm ({
            title: "Here is a tiny form", 
            message: contentNode, // contains various <input>, <textarea>, and <select> elements
            callback: function(result) {
                if (result) {
                  results = {};
                  results.fieldname1 = dialog[0].querySelector("[name=fieldname1]").value;
                  results.fieldname2  = dialog[0].querySelector("[name=fieldname2]").value;
                  results.fieldname3 = dialog[0].querySelector("[name=fieldname3]").value;
                  doStuffWithResults(results);
                }
              }
            }
          );

         function doStuffWithResults(results) {console.log('results: ', results);}

So, apart from (massively) extending the semantics of "confirm", are there any problems with this approach?

**Comment by ericscheid** [comment]
Would be real nice if we could do `bootbox.prompt(inputType='form', inputOptions=formNode)` and it returns an array of named values.

5.0?

**Comment by tiesont** [comment]
To answer your original question:

You would use the callback for your "OK" button in combination with something like `find()`. For example:

```
var dialog = bootbox.dialog({
    title: 'A custom dialog',
    message: /* your form markup here */,
    buttons: {
        ok: {
            label: 'OK',
            className: 'btn-primary',
            callback: function(){
                
                var form = dialog.find('form');
                var data = form.serialize();
                
                /* data is serialized to a format suitable for using in $.ajax, $.post, etc. */
            }
        }
    }
});
```

Dialog-level callbacks for anything other than confirm and prompt won't have a response/result value, so you're correct in seeing nothing there.

**Comment by ericscheid** [comment]
Thanks. I also found https://github.com/macek/jquery-serialize-object which handles some extra quirks.
