### ISSUE TITLE
How to trigger another modal after prior is done?

### ISSUE THREAD

**Issue by ericscheid** [makeusabrew/bootbox#575]
The various options for `callback` functions, afaict, fire before the bootbox modal is demolished. That is, after the modal OK button is hit and before the modal is hidden/removed.

I have a use case where I want to sometimes pop another modal after the first modal (dependent on what values were entered into the first modal).

How would I do that?

**Comment by tiesont** [comment]
Since Bootbox is, in part, a wrapper around Bootstrap modals, you can subscribe to their events. You probably want `hidden.bs.modal`:

> This event is fired when the modal has finished being hidden from the user (will wait for CSS transitions to complete).

From http://getbootstrap.com/javascript/#modals-events

[For example](https://jsfiddle.net/w63m03L5/):
```
bootbox.confirm('Are you sure!', function(result){ /* Your confirm callback code */ })
    .on('hidden.bs.modal', function(e){

        bootbox.alert("I'm after the confirm!");

    });
```
