### ISSUE TITLE
Long message causes bottom of the modal to show

### ISSUE THREAD

**Issue by SuperFuentes** [makeusabrew/bootbox#576]
As you can see in the screenshot below, the bottom of the modal is showing first for devices with small screens. I found that if I add a CSS property of bottom: inherit, to the main bootbox class element the modal shows from the top, but then I am unable to scroll the modal an the iOS device. If I shorten the message (which is not going to work for this specific application) the modal appears fine.

![screen shot 2017-01-16 at 9 28 46 am](https://cloud.githubusercontent.com/assets/6511551/21993206/7fe75448-dbce-11e6-84d3-7975f7646028.png)

I am using the following code:
```

var messageContent = "Lorem ipsum dolor..........ipset"

$(context).once('modal').on('ready', function(){
	var dialog = bootbox.confirm({
	    title: "<h3 class='media-library-agreement-modal__header'>Information Regarding Usage</h3>",
	    message: messageContent,
	    className: 'han-solo',
	    buttons: {
	        confirm: {
	            label: 'Agree & Download'
	        },
	        cancel: {
	            label: 'Disagree & Close'
	        }
	    },
	    callback: function (result) {
	        if (!result) {
	        	window.location = "/";
	        }
	        // console.log('This was logged in the callback: ' + result);
	    }
	});
});
```

**Comment by SuperFuentes** [comment]
Temporarily solved this by adding:

`dialog.find('.bootbox-body').parents('.han-solo').animate({ scrollTop: 0 }, 'fast');`

On page load, it's not at all noticeable that the modal is being scrolled from bottom to top.

**Comment by tiesont** [comment]
This has been reported before, although I've not found the previous issue yet. This happens because the primary button receives focus as the last step of showing the modal. Since your buttons are off the page, it scrolls down.

I've fixed this in the past by limiting the size of the modal content, although that does require the modal to have a scroll bar.
