### ISSUE TITLE
bootbox prompt checkbox can not display fully

### ISSUE THREAD

**Issue by HackToday** [makeusabrew/bootbox#584]
Have code like this

```
+         bootbox.prompt({
+             title: "This is a prompt with a set of checkbox inputs!",
+             inputType: 'checkbox',
+             inputOptions: [
+                 {      
+                     "text": 'dd',
+                     "value": 1
+                 }      
+             ],         
+             callback: function (result) {
+                alert('hello');
+             }          
+         });     

```

And found that checkbox can not display fully, like this

![default](https://cloud.githubusercontent.com/assets/10363809/23539332/9705e30e-0015-11e7-8877-50c5303bb986.JPG)

**Comment by tiesont** [comment]
That doesn't happen with the [example posted here](http://bootboxjs.com/examples.html#prompt-with-checkbox), which leads me to assume you've overridden the Bootstrap CSS somewhere. We would need an example that reproduces what your screenshot shows. It also helps to note the specific version of Bootstrap you are using.

**Comment by HackToday** [comment]
I will check about and update new finding. Thanks
