### ISSUE TITLE
confirm className btn-primary change style

### ISSUE THREAD

**Issue by pablosym** [makeusabrew/bootbox#585]
Hello, I am using the confirmation and confirm button I have set the btn-primary class and automatically change it by default.

In the btn-primary style I have it overwritten in my CSS file from blue to white, when the dialog is appearing it works, when it finishes, it changes by the blue color

.btn-primary:hover{
    background: #E5C879;
    color: white;
}

`bootbox.confirm({
                            title: "Caja abierta",
                            message: mensaje,
                            buttons: {
                                cancel: {
                                    label: ''
                                },
                                confirm: {
                                    label: '<i class="fa fa-check"></i> OK',
                                    className: 'btn-primary'
                                }
                            },
                            callback: function (result) {
                                //console.log('This was logged in the callback: ' + result);
                            }
                        });`

**Comment by tiesont** [comment]
I'm not sure I quite get what you're asking, but it sounds like you also need to override the `:active` styles from [here](https://github.com/twbs/bootstrap/blob/v3.3.7/dist/css/bootstrap.css#L3132).

**Comment by pablosym** [comment]
Thanks for modifying that style worked correctly
