### ISSUE TITLE
Bootbox + JAVA HttpServletResponse 

### ISSUE THREAD

**Issue by hlaranjeira** [makeusabrew/bootbox#590]
Cheers,

I am raising this issue in order to clarify one subject I couldn't found in other Internet sites.

I am working in a J2EE web application which uses JAVA Servlets and JSP/ HTML / Javascript as front-end technologies. 

In our project, sometimes we rise some Javascript alerts using the object Response (HttpServletResponse response).

We have been using bootbox alerts / confirm in a lot of webpages (JSP)  in this project but we can't do it using the printWriter+response objects that generate HTML / JS code to the webpage.

e.g.:
PrintWriter out=response.getWriter(); 
out.println(" <script> alert('Registo inserido com sucesso. Teste as suas credenciais.'); </script>");
out.println("<script>location.replace('login.jsp')</script>");

Our goal (not working): 
out.println(" <script> bootbox.alert('Registo inserido com sucesso. Teste as suas credenciais.'); </script>");

We wanted to use bootbox in that way because a lot of our business logic is validated in PL/SQL scripts and the results have more performance if displayed like that in a JAVA Servlet.

How can you help me with this issue?

Keep on the good work,
Hugo Laranjeira

**Comment by tiesont** [comment]
If your goal is to not have the redirect occur until the Bootbox alert is dismissed, you need to use a callback, [as noted in the documentation](http://bootboxjs.com/documentation.html#bb-notes). Bootbox doesn't (and can't) block the page from loading, so it's not a drop-in replacement for the "real" alert.

**Comment by hlaranjeira** [comment]
@tiesont  thank you for the quick answer.

My goal is to **display a bootbox alert from a Java servlet** using that PrintWriter combined with HTTPServletResponse, the present issue is not on the redirect action.

The example I gave **works fine with classic javascript Alerts** (it even waits for the OK click to redirect the page):
e.g.: 
PrintWriter out=response.getWriter();
out.println(" <script> alert('Registo inserido com sucesso. Teste as suas credenciais.'); </script>");
out.println("<script>location.replace('login.jsp')</script>");

I really wanted to display the bootbox alert that way (e.g. code bellow) instead of that classic javascript alert, but somehow it just doesn't work like that :
out.println(" <script> bootbox.alert('Registo inserido com sucesso. Teste as suas credenciais.'); </script>");

Any thoughts on this matter?
Cheers,
Hugo Laranjeira

**Comment by tarlepp** [comment]
@hlaranjeira I haven't never worked with Java servlet's but google hit I got with this was: http://stackoverflow.com/questions/13124234/best-way-to-include-javascript-in-java-servlets maybe this will help you.
