### ISSUE TITLE
Bootbox confirm takes long time to show up in IE9 (not in IE9 Compatibility)

### ISSUE THREAD

**Issue by advapiIT** [makeusabrew/bootbox#591]
Hello,
I've got a strange problem on machines that runs IE9 native. The popup confirmation takes 1-2minutes to show up, while in IE9 emulated or other browser won't take time.
I've just seen your link [here](https://github.com/makeusabrew/bootbox/issues/52) but I've bootbox js locally referenced

Thanks

**Comment by tiesont** [comment]
Without something that demonstrates this problem, I'm afraid we can't really help you. At a minimum I need a jsFiddle, Bootply, whatever - _something_ to reproduce what you're seeing.
