### ISSUE TITLE
Meetfinch ad on bootbox site

### ISSUE THREAD

**Issue by skylord123** [makeusabrew/bootbox#592]
I was using finch for a while but they are no longer in business. I recommend removing the advertisement for it on the bootbox website. This may not be the place for this request but I have no clue how else to go about bringing this to the attention of the devs.

**Comment by tiesont** [comment]
Well, there's a Twitter link in the footer, but yeah, I've already brought this up with Nick. I assume we'll remove it at some point.

**Comment by tiesont** [comment]
Done.
