### ISSUE TITLE
Bootbox jumps to bottom of large modals to focus .btn-primary

### ISSUE THREAD

**Issue by Premixedpie** [makeusabrew/bootbox#596]
Referencing #505.

When a modal has a button with the .btn-primary bootbox focuses it by default. Normally don't see any issues but if the modal has a lot of content and it's height is larger then the view port the browser jumps down to the bottom of the modal.

Simple temporary fix is to not use the .btn-primary class for a button or make a class named something else with the same style as .btn-primary. Having a built in option to disable the focus or to change the name of the class to focus would be great.

OS: Windows 7
Browser: Chrome 57.0.2987.133
bootbox v4.4.0
bootstrap v3.3.7
jQuery v2.2.4

Example: http://jsfiddle.net/xbywh6Lc/1/

**Comment by tiesont** [comment]
This has been reported a few different times (#576, #260. for instance). I'm not sure that we've ever come to a consensus of how it _should_ be handled, but it probably makes more sense to constrain the height of your modal's content. @tarlepp @makeusabrew ?

**Comment by tarlepp** [comment]
@Premixedpie and that same works like what within pure bootbox ?

@tiesont and @Premixedpie imho this "quite" small use case that can quite easily to fix with some custom code.

So imho these kind of cases you know that modal content is not going to fit on your screen, and then you make your own adjust to that.

**Comment by tiesont** [comment]
I would assume a max-height with overflow would do it, either on the bootbox-body div or a wrapper included in the dialog content. That's how I handle it, anyway:

.bootbox-body
{
    max-height: 500px; // or rems or ems, if you prefer
    overflow-y: auto;
}

You're looking at one of two less-than-optimal UX outcomes: either you show the top of the modal, and the user has to scroll down to click a button, or (at the moment) the viewport gets scrolled to the bottom of the dialog when it loads. Constraining the modal height so that it will fit your viewport seems like a better compromise. You'd probably need some media queries, if you expect your app to be viewed on large _and_ small devices.

**Comment by tarlepp** [comment]
imho - if you're doing your application for large and small devices you should think what to show on those dialogs. And by that determine what to do.

**Comment by Premixedpie** [comment]
Default bootstrap  behavior doesn't have the focus on .btn-primary class so it took some time to figure out what was causing it. I had different classes on the button so the focus wasn't obvious. I have content that expands past the viewport and I want the user to see the top of the content first rather then having to scroll up to start reading then back down to click the button. That was my thought process anyways. I can see how putting a scroll bar in the modal would work for some cases but wasn't something I wanted to do.

I see that you can also just use .off("shown.bs.modal") to disable it as well now. Mostly just a feature request I thought might make it easier to enable/disable the behavior for others in the future. Actually looks like there is already a pull request for it https://github.com/makeusabrew/bootbox/pull/497. Thanks for the help and the quick replies!
