### ISSUE TITLE
Support specifying id attribute for button objects

### ISSUE THREAD

**Issue by manderson23** [makeusabrew/bootbox#598]
To aid using automated test tools it would be useful if each button object could support specifying an id attribute.

**Comment by tiesont** [comment]
@tarlepp What's your thought on this? Either we implement this, or I close the issue.

**Comment by AyoubEd** [comment]
Yes, i was jus looking for a way to do this.It would be very helpful.

**Comment by Dravee** [comment]
Hi, I've been needing to do this and using the jQuery selector is a workaround that seems to work.
Example : 

`bootbox.confirm({
    message: 'message',
    buttons: {
        'cancel': {
            label: 'Cancel',
            className:'btn btn-default bootbox-cancel-class'
        },
        'confirm': {
            label: 'OK',
            className:'btn btn-primary bootbox-confirm-class'
        }
    },
    callback: function(result) {
        if (result) {
            console.log("OK clicked");
        }
    }
});

$(".bootbox-cancel-class").attr('id', 'bootbox-cancel-id');
$(".bootbox-confirm-class").attr('id',  'bootbox-confirm-id');`

I get : 

![image](https://user-images.githubusercontent.com/18500388/30969170-e10a019c-a461-11e7-921f-dfc5f8b36536.png)

**Comment by ronan-paul** [comment]
Hello

I ask to re-open this request, because it is a major need for test automation: 
- select elements (like buttons) with their id so that there is no risk of ambiguity
- using a specific class looks like an easy workaround, but it is not semantically correct, because:
1. a class name is supposed to be related to the design
2. multiple elements might have the same class name

So I would propose this to be implemented with either:

**Option 1 - create an optional id property for each button**
```
bootbox.dialog({ 
    title: 'FullScreen ',
    message: '<p>Do you want to go for fullscreen</p>',
    buttons: {
        cancel: {
            label: 'Oh no',
            id: 'dialog-fullscreen-btn-cancel', //new property
            className: 'btn-primary',
            callback: function(){
                  //whatever
            }
        },
        accept: {
            label: 'Go for it',
            id: 'dialog-fullscreen-btn-accept', //new property
            className: 'btn-info', 
            callback: function(){
                  //whatever
            }
        }
    }
})
```

**Option 2 - use button key as id property**
```
bootbox.dialog({ 
    title: 'FullScreen ',
    message: '<p>Do you want to go for fullscreen</p>',
    buttons: {
        dialog-fullscreen-btn-cancel: {
            label: 'Oh no',
            className: 'btn-primary',
            callback: function(){
                  //whatever
            }
        },
        dialog-fullscreen-btn-accept: {
            label: 'Go for it',
            className: 'btn-info', 
            callback: function(){
                  //whatever
            }
        }
    }
})
```

Any version would create these 2 buttons : 
```
<button id="dialog-fullscreen-btn-cancel" type="button" class="btn btn-primary">Oh no</button>
<button id="dialog-fullscreen-btn-accept" type="button" class="btn btn-info">Go for it</button>
```


This improvement would allow automation tests to run with specific selector like: 
```
$I->click('#dialog-fullscreen-btn-accept');
```

and no longer:
```
$I->click('button[title="Go for it"]');
```
or 
```
$I->click('button.my-button-class');
```

Thank you in advance

**Comment by txwizard** [comment]
I notice that this issue appears to have been closed without giving a reason. Though that is of course your prerogative, I don't see such behavior as in keeping with the spirit of open source. I think the suggestion made by @ronan-paul  has merit, and it deserves more than the silent treatment.

**Comment by tiesont** [comment]
> I notice that this issue appears to have been closed without giving a reason. Though that is of course your prerogative, I don't see such behavior as in keeping with the spirit of open source. I think the suggestion made by @ronan-paul has merit, and it deserves more than the silent treatment.

It was closed because it was implemented: https://github.com/bootboxjs/bootbox/blob/222147501f368e4b083578c6688af40d81d4bc2a/bootbox.js#L268

**Comment by txwizard** [comment]
I noticed that a while later in another issue, but I didn't think to go back and say something here. It's too bad that GitHub doesn't automatically cross reference related issues. 😒
