### ISSUE TITLE
3 bootbox option

### ISSUE THREAD

**Issue by verza** [makeusabrew/bootbox#600]
First, apologize for my English, it's not my language
I need help with this code that I am implementing

```
bootbox.confirm({
    size: "small",
    message: "A que estado desea cambiar?",
    buttons: {
        confirm: {
            label: 'Cerrado',
            className: 'btn-warning'

        },
        cancel: {
            label: 'Abierto',
            className: 'btn-success'
        }
    },

    callback: function (result) {
        if(result){
                    $.post("./backend/ajax/expedienteAjax.php?op=ModificarEstado", {id: id, estado: 'C'}, function (e) {
                    console.log(id + " " + estadoFalse)
                    swal("Mensaje del Sistema", result);
                    tabla.ajax.reload();
                    });
                  }
        else{
            $.post("./backend/ajax/expedienteAjax.php?op=ModificarEstado", {id: id, estado: 'B'}, function (e) {
                    console.log(id + " " + estadoFalse)
                    swal("Mensaje del Sistema", e, "success");
                    tabla.ajax.reload();
                    });
        }
    }
});
```

my problem:
I need a third option, when the alert is canceled
Try onscape but it does not work
The problem is that I use the cancel button to make an option
I need something like a third choice or a third button

Thanks for helping this newbie

pd:I did not find anything similar on the internet

**Comment by tiesont** [comment]
Unfortunately, if you [review the code](https://github.com/makeusabrew/bootbox/blob/master/bootbox.js#L355), you'll find that you can't override the `onEscape` function for a confirm dialog. It sounds like the best fit for your use-case is a custom dialog.
