### ISSUE TITLE
Bootstrap is missing from the dependencies set in the UMD snippet

### ISSUE THREAD

**Issue by lddubeau** [makeusabrew/bootbox#602]
bootbox needs Bootstrap to run, but the UMD code only requires `jquery`:

```
  "use strict";
  if (typeof define === "function" && define.amd) {
    // AMD. Register as an anonymous module.
    define(["jquery"], factory);
  } else if (typeof exports === "object") {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.

    if (typeof $ === "undefined") {
      module.exports = factory(require("jquery"));
    } else {
      module.exports = factory($); // jshint ignore:line
    }

  } else {
    // Browser globals (root is window)
    root.bootbox = factory(root.jQuery);
  }
```

The "browser globals" is fine because its up to the developer using bootbox to use the right `script` elements. However the two other branches are brittle and *require* that users of bootbox take special measures to make sure Bootstrap is loaded somewhere somehow before bootbox executes.

Someone who uses RequireJS would for instance, set a `map` that forces `bootbox` to load `bootstrap` when `jquery` is required:

```
  map: {
    "bootbox": {
      jquery: "bootstrap",
    },
  },
```

and set a `shim` for `bootstrap` that provides the right return value:

```
  shim: {
    bootstrap: {
      deps: ["jquery"],
      exports: "jQuery.fn.popover",
      init: function ($) { return $; }
     },
   },
```

(In the code above, the `exports` is used to only test whether Bootstrap has loaded. If `jQuery.fn.popover` exists after RequireJS loads and executes the file, then it is a successful load. The value of the module is provided by the value returned by `init`.)

What I have above is just one example of how it can be done. There are other ways that could get it done but the problem is that people using an AMD loader **must** work around the inadequate dependencies set by bootbox if they want their code to load reliably.

**Comment by tiesont** [comment]
This has been brought up (more or less) before. I don't think it's going to be changed in a 4.x branch, but if we go forward with a 5.0 release I'll try to make sure this is at least discussed.

**Comment by lddubeau** [comment]
I managed to miss the earlier discussion in my issue search.

I'm going to add here the SystemJS config I use to work around the issue when I use SystemJS instead of RequireJS. RequireJS does not allow using a configuration to *directly* add a dependency to an AMD module. (The dependencies of AMD modules are defined *solely* through the dependency list they pass to `define`.) So you have to use workarounds like the one I've shown in my initial report. SystemJS, contrarily to RequireJS, does allow to directly add dependencies to modules through configuration, so this is what I use:

```
{
  paths: {
    "npm:": "/node_modules/",
  },
  map: {
    bootstrap: "npm:bootstrap/dist/js/bootstrap.js",
    bootbox: "npm:bootbox",
  },
  meta: {
    // Using the asterisk allows to hit both the minified and non-minified version.
    "npm:bootbox/*": {
      deps: ["bootstrap"],
    },
  },
  packageConfigPaths: [
    "npm:*/package.json",
  ],
}
```

**Comment by tiesont** [comment]
They weren't really much in the way of discussion. I think the same problem comes up with Bower and some other similar tools which expect bootbox to explicitly define all of their dependencies. I don't know why bootbox doesn't check for the Bootstrap modal function earlier - it's there, it's just way down when the dialog is being generated. I assume that it's just a historical artifact from the few rewrites bootbox has been through.

I, unfortunately, am most a issue monitor and focus on updating the docs site as needed, so I can't really offer a timeline of when anything might be updated. I'll keep this in mind, though.
