### ISSUE TITLE
Size "small" not working

### ISSUE THREAD

**Issue by Tri125** [makeusabrew/bootbox#603]
Related: #432
bootbox.js : 4.4.0 - latest stable release
jQuery : 1.10.2 
bootstrap.js : v3.0.0

Tested on: Chrome and Firefox, Edge, and Internet Explorer
OS: Windows 10.

Reproduced on jsfiddle: https://jsfiddle.net/57pjj9j8/

According to the documentation ([example BB.5](http://bootboxjs.com/documentation.html#advanced-usage-1)), using the "size" attribute with value "small" should produce a small box. However, it doesn't seems to be working

**Comment by tiesont** [comment]
Bootstrap 3.0.0 doesn't have the size option. You'll need to update to a newer version. [3.1.0](https://github.com/twbs/bootstrap/releases/tag/v3.1.0) is the earliest version that supports the size options. I would recommend taking the latest version, 3.3.7, if you can.
