### ISSUE TITLE
Bootstrap css with media width min 768px is not apply on large dialog

### ISSUE THREAD

**Issue by yuyenkan** [makeusabrew/bootbox#604]
as title, when I trying to use bootbox custom dialog, I found out some of the bootstrap css is not applied on the element within bootbox custom dialog

**Comment by tiesont** [comment]
We'll need to see some sort reproducible example before attempting to trouble-shoot this. Please add a jsFiddle, Bootply, or similar.

**Comment by yuyenkan** [comment]
https://jsfiddle.net/54q0zdu0/2/

**Comment by tiesont** [comment]
I'm not getting what issue you're having. If I resize the frame in which the dialog is rendered, the CSS switches when it reaches the appropriate breakpoints. What are you expecting to happen?

**Comment by yuyenkan** [comment]
The Problem is, when my screen is 768px, the property should be red color, but in bootbox dialog, the property is still blue color

**Comment by yuyenkan** [comment]
I think it is my mistake, the property is not override when screen size different.

**Comment by tiesont** [comment]
The text color changes when I resize the frame in the fiddle. Not sure what you're seeing, but regardless, this isn't a Bootbox issue.
