### ISSUE TITLE
Overwriting templates

### ISSUE THREAD

**Issue by giero** [makeusabrew/bootbox#605]
Hello,

Is or will it be possible to overwrite input templates from outside (for example in config)? On my page I am using [Awesome Bootstrap Checkbox](https://github.com/flatlogic/awesome-bootstrap-checkbox) and it requires different template for checkboxes. Now it's unable to work properly.

Best Regards,
Giero

**Comment by giero** [comment]
Ok, I can see there was a similar request even with pull request: https://github.com/makeusabrew/bootbox/pull/546 - is it possible to merge it soon?

**Comment by tiesont** [comment]
> is it possible to merge it soon?

No. This would be a major change, and probably wouldn't happen until a 5.0 release, which is still just in the planning stage.

**Comment by giero** [comment]
Thx for response,

I've created more complex solution in https://github.com/makeusabrew/bootbox/pull/606.
I don't think it's a major change - just a new simple function for overwriting predefined templates.

**Comment by tiesont** [comment]
> I don't think it's a major change

Anything that adds new functionality is a major change. Templates are not an option with the current 4.x version, so adding that feature requires a major version bump.

> just a new simple function for overwriting predefined templates

I doubt it would be "simple." There's a non-trivial amount of effort that goes into structuring the result value(s) from the prompt function, and that code would have to be updated to handle the introduction of user templates.

I'm not saying this will never happen, but it won't happen anytime soon.

**Comment by tarlepp** [comment]
@giero and you can always use custom dialog with content that you like to use.

**Comment by stevenjlho** [comment]
This is a great feature. I want to customize template , not just customize body content.

**Comment by tiesont** [comment]
@stevenjlho You already can, if you use the custom dialog. 

The only benefit to allowing input templates is to give the user the ability to customize the prompt, but like I mention above, handling the prompt result is not a trivial process. We also likely have to add checks to make sure that the templated input matches the prompt type (i.e. that a `<select>` template was provided if the `inputType` option is set to `'select'`.

I do like the idea of templates. I'm thinking something like how numeral.js handles locales might be a good pattern to follow (not to mention switching Bootbox's locales to work the same way), but that's for the 5.0 version, assuming we ever start working on it.

**Comment by tiesont** [comment]
Closing, as I'm not going to implement this.
