### ISSUE TITLE
Dialogs don't close when the user clicks outside of the dialog

### ISSUE THREAD

**Issue by lordspace** [makeusabrew/bootbox#607]
I'd expect the dialogs to close when the user clicks outside of the dialog.

**Comment by tiesont** [comment]
That's not the default behavior of Bootbox, but you can enable it with the [backdrop option](http://bootboxjs.com/documentation.html#bb-option-backdrop):

```js
bootbox.alert({
    message: 'I will dismiss when you click the backdrop',
    backdrop: true
})
```

**Comment by lordspace** [comment]
Cool
