### ISSUE TITLE
Step property on prompt

### ISSUE THREAD

**Issue by cmpm72** [makeusabrew/bootbox#608]
How can I put the step property in input type number?

**Comment by tiesont** [comment]
Bootbox doesn't currently provide a step option. For now, you'd have to set the value either using the `init` function or Bootstrap's `show.bs.modal` or `shown.bs.modal` event.

```js
var modal = bootbox.prompt({
    type: 'number',
    // ... your other options ...
});

modal.init(function(){
    modal.find('.bootbox-input-number').attr('step', your_value_here);
});

modal.on('show.bs.modal', function(){
    modal.find('.bootbox-input-number').attr('step', your_value_here);
});
```

**Comment by cmpm72** [comment]
Tanks

**Comment by tiesont** [comment]
This has been implemented in the [v5x branch](https://github.com/makeusabrew/bootbox/tree/v5.x). If you're fine with a beta version, give it a try.
