### ISSUE TITLE
Possible to add label above textfield in prompt dialog?

### ISSUE THREAD

**Issue by prakashraman** [makeusabrew/bootbox#610]
Hi,

I would like to know if it is possible to add a "label" field above the "textfield" in the "prompt" dialog.

Right now, the prompt window shows just the "title", "textfield", "action buttons". I would like to it show
"title", "label", "textfield", "action buttons".

Thanks!

**Comment by tarlepp** [comment]
nope that isn't supported, if you like to make "prompts" like that then you need to use custom dialog for that.

Or if you have some proposal for this feature please make a pr

**Comment by prakashraman** [comment]
Ah, I see. Thanks, will give it a go.

**Comment by tiesont** [comment]
See also: https://github.com/makeusabrew/bootbox/issues/543#issuecomment-249350685

**Comment by prakashraman** [comment]
Ah! That is a great idea! That should work just fine 👍 

Thanks!
