### ISSUE TITLE
Need to provide Sync and Async event

### ISSUE THREAD

**Issue by shaangidwani** [makeusabrew/bootbox#611]
Its great if we got the functionality like browser prompt , alert buttons. they all are based on sync. if we update the alerts we need to customized lots of things like when click on yes then there separate function if we click on some other button so there must be separate function. So if  this model is sync so that we can get the answer in prompt like browser prompt and we can go further without changing the existing code which is run with browser prompt and messages.

Please suggest on this.

**Comment by tiesont** [comment]
That's not possible, nor should it be. If you need blocking operations, use the native dialogs.
