### ISSUE TITLE
Prompt, continues offer password completion dispite autocomplete is set to off.

### ISSUE THREAD

**Issue by running-web-dev07** [makeusabrew/bootbox#612]
Hi

Mozilla Firefox does not obey autocomplete = 'off' on password on prompt off that type continues to offer password saved passwords on sites that you save your credentials.
As workaround i compile an ttf font that has only dots as symbols to entire charset ranges as an webfont and then use it that font in a prompt with normal text-field. Althought this solution increase the amount off KBs downloaded this was the only one that worked for me.

I saw that webkit has an -webkit-text-security css rule, but firefox does not have an vendor specified alternative for this rule.

**Comment by tiesont** [comment]
How is this a Bootbox issue? 

I also don't think you're reading the spec properly - remembering passwords and filling in a form is not the same as the input automatically completing an input value, which is what autocomplete does.

**Comment by running-web-dev07** [comment]
I just thought it was a place for debate here too. I just wanted to discuss the alternatives.

**Comment by tiesont** [comment]
> I just thought it was a place for debate here too

Unfortunately, no. This is for reporting issues or suggesting new features. Dealing with each browser's auto-fill/"remember login" feature is out-of-scope for Bootbox.
