### ISSUE TITLE
Submit Form ( POST ) after Button Clicked

### ISSUE THREAD

**Issue by marcoczen** [makeusabrew/bootbox#616]
Hi,

I have a bootstrap form with a submit button as below;

```
<button type="submit" class="btn btn-primary" name="button_deluser" > Delete Selected User </button>
```

When the button is clicked - the form is submitted. I would like a confirmation box (Yes - Delete, No ).
I don't understand how to incorporate Bootbox into the button above from the documentation provided.

Any ideas ? Alert - jQuery newbie here.

**Comment by tiesont** [comment]
There is a [confirm function](http://bootboxjs.com/documentation.html#bb-confirm-dialog), that will provide a "Yes/No" dialog.

If you want to use your own dialog content, then you need to use the [custom dialog function](http://bootboxjs.com/documentation.html#bb-confirm-dialog), and handle the submit event in the callback for your "Yes" button.

If you've asking how to show a confirm dialog when the button above is pressed, that's a bit out of scope for Bootbox, but in a nutshell, you have to handle the submit event for your form (don't just handle the click event of the button). Since you don't show your form, here's a simplified example:

Form:
```html
<form id="the-form">
    <button type="submit" class="btn btn-primary" name="button_deluser" > Delete Selected User </button>
</form>
```

JavaScript:
```javascript
$('#the-form').on('submit', function(e){
    // prevent the normal form submission
    e.preventDefault();

    bootbox.confirm('Really delete!', function(result){
        // result will be a true or false value
        if(result){
            /* Submit the form via ajax? */
        }
    })

});
```

**Comment by marcoczen** [comment]
@tiesont - Thanks.
From the page you provided -> All Bootstrap modals, unlike native alerts, confirms, or prompts, generate non-blocking events.

Therefore i gather - this CANNOT replace a normal js confirm box ? Bcos , for me, it MUST not proceed with the form submission if the user does not select Yes.

Or have i understood this wrongly?

Also, if bootbox can do this ...What would be the form submission syntax ? form.submit ? or something like that?

My apologies for these newbie questions .

**Comment by tiesont** [comment]
You can't use the bootbox.confirm function as a drop-in replacement for the native function. The example I already provided shows most of what you need to do to use Bootbox in place of the native function. Are you asking how to perform an Ajax request?

**Comment by marcoczen** [comment]
@tiesont Hi,

> You can't use the bootbox.confirm function as a drop-in replacement for the native function. > 

Noted.

 The example I already provided shows most of what you need to do to use Bootbox in place of the native function. Are you asking how to perform an Ajax request?

**Comment by tiesont** [comment]
Like I mentioned, you really should be hooking into the submit event of the form, not the click event of the button, but it you really want to just handle the click event, you need to remember that JavaScript functions like this aren't blocking operations.

You would need something like:

```javascript
$('#action').on('click', function(e){
    var _this = $(this);

    // (1)
    bootbox.confirm('Really delete?', function(result){
        if(result){
            _this.closest('form').submit();
        }
    });

    // (2)
    e.preventDefault(); // or return false;
});
```

Using a native confirm at the point noted (1) above, the browser will sit and wait for you to respond (the confirm blocks the flow of execution). So you wouldn't get to point (2) until you click the yes or no option in the confirm dialog. 

With Bootbox (or any similar markup-based dialog), when you call `bootbox.confirm()` at point (1), that's a non-blocking function, meaning the code will continue on it's merry way to point (2). To prevent the form submission from occurring before the user has interacted with the modal, you either prevent the default action of the button (which in this case is to trigger the submit event of the parent form), or return false, which accomplishes the same thing.

**Comment by tiesont** [comment]
If you are only targeting Chrome, you _could_ try updating Bootbox to use the [dialog](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element) element, which is the only HTML tag that I know of the is capable of blocking the document. It's not in any W3C spec, though, since it hasn't made it out of the WHATWG yet, so I don't see it being supported to any degree for at least another 2 or 3 years. That's on you, though; we won't be going that route with Bootbox anytime soon.

**Comment by marcoczen** [comment]
@tiesont 

> Like I mentioned, you really should be hooking into the submit event of the form, not the click event of > the button

Yes. That is what I am looking for. 

`<button` type="submit" id="action" value="edit" onclick="return confirm('Proceed with Action?');" />

**Comment by marcoczen** [comment]
Bump ? Or just mark this as UnResolved ? And close ?

**Comment by tiesont** [comment]
Sorry, this isn't a Bootbox issue, so you're not going to get a "this is how you do it" answer.

If you want some pseudo-code, this is roughly the process you probably need to follow:

```javascript
// global variable
var canSubmit = false;

// Handle form submission
$('#the-form').on('submit', function(e){
    if(!canSubmit){
        // prevent the normal form submission
        e.preventDefault();

        // store reference to form
        var _form = $(this);

        bootbox.confirm('Really delete?', function(result){
            // result will be a true or false value
            if(result){
                // toggle the global variable, so that next form submission proceeds as normal
                canSubmit = true;
                _form.submit();
            }
        });
    }
});
```

**Comment by marcoczen** [comment]
Noted. Thanks. Dropping this for now.

**Comment by marcoczen** [comment]
@tiesont 

UPDATE - Just went back to Jquery UI. Got a nice looking confirmation box that works properly in a form. 
Sometimes its best to avoid projects that have insufficient documentation or are just not newbie-friendly.

**Comment by tarlepp** [comment]
@marcoczen if you look example that @tiesont provided - you should be able to figure the rest of that on your needs.

If you want a working example could you please provide plunker with structure + instructions that what you want to complish?
