### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by odahcam** [makeusabrew/bootbox#619]
Bootstrap 4 beta has launched today. So what's the possibility of updating a BS3 + bootbox UI to BS4?

**Comment by tiesont** [comment]
Won't happen until/unless we move forward with a 5.0 release, but (assuming nothing changed between Alpha 6 and Beta) I have noted the changes I had to make in #566.

I'll take a look and see if anything major has changed in the Beta for modals, but that's probably the best you'll get for now.

**Comment by tiesont** [comment]
Closing as a dupe of #566 - please comment there if you need clarification.
