### ISSUE TITLE
[FR] Allow custom attributes for input type

### ISSUE THREAD

**Issue by samuelstein** [makeusabrew/bootbox#620]
Hello,
thanks for the great dialog framework. i have an idea how to make it greater. i got a case where i needed to customize the inputType `number` with options for step and min value to get this type of input field: `<input type="number" min="1" step="1">`. would be great if the lib would support this type of customizations.

**Comment by tiesont** [comment]
Step, min, and max are actually on the roadmap (see #545) and has been implemented in my [development fork](https://github.com/tiesont/bootbox). #608 shows how to add them with the current Bootbox version. As far as allowing any and all attributes, I'm not inclined to implement that - I'd have to see a better use-case for that, and more users asking for such a feature. 

You can always use a custom dialog if you want full control over your inputs.

**Comment by samuelstein** [comment]
perfect. thanks. i didn't saw the roadmap.
