### ISSUE TITLE
too long message

### ISSUE THREAD

**Issue by gitshancai** [makeusabrew/bootbox#622]
![Uploading image.png…]()
![tim 20170901164621](https://user-images.githubusercontent.com/4264842/29962246-1bee66b4-8f35-11e7-9d49-b2887e82699f.png)

[](url)

**Comment by tiesont** [comment]
So, what's the question?

**Comment by tarlepp** [comment]
@gitshancai simpliest solution for your long message is attach additional css rule to your modal with `word-break: break-word;`
