### ISSUE TITLE
Alert header title is on right position

### ISSUE THREAD

**Issue by tokidoki11** [makeusabrew/bootbox#623]
bootbox.js v4.4.0

As shown in the image somehow my header title is at right, not left

<img width="499" alt="screen shot 2017-09-06 at 1 29 55 pm" src="https://user-images.githubusercontent.com/7564844/30097430-c97f19c4-9307-11e7-991f-4265bf5cf0be.png">

**Comment by tiesont** [comment]
That's because you're using Bootstrap 4, which we don't officially support yet. See #566 for the changes you need to make.

**Comment by jonjay80** [comment]
I had the same problem, but did a quick fix using CSS since the it's using flex boxes.

.bootbox .modal-header {
	flex-direction: row-reverse;
}

**Comment by MDCopen** [comment]
This did not work me. Any other alternatives for this?

**Comment by tiesont** [comment]
> This did not work me

Can you elaborate on what "did not work" means, please?
