### ISSUE TITLE
Hide a button before show

### ISSUE THREAD

**Issue by gjohncock** [makeusabrew/bootbox#624]
I need to be able to hide a button when the dialog opens as it will be made visible only when the user meets a criteria in the other elements of the dialog.  
Can this be done easily?

**Comment by tiesont** [comment]
Yes, using either the [init function](http://bootboxjs.com/documentation.html#bb-function-init), or by subscribing to the `shown.bs.modal` event. `show.bs.modal` doesn't always seem to work with Bootbox, but if it did that would allow you to hide the button just before the modal is shown.

You could also use `show: false` in your options object, and hide the button before manually triggering `show`.

Lastly, if you want to use Bootstrap's helper classes (like `hidden`), you can use more than one class name in string value for the `className` option when defining your buttons.

**Comment by gjohncock** [comment]
Thanks for the quick response.  You are right about "show.bs.modal", it doesnt work and that would be the ideal event to perform thie hide in.  "shown.bs.modal" is a little to late as you will see the button briefly when the dialog loads.  I tried assigning a custom class to the button then specifying display:none !important; in the css file but this did not work either.
Currently I have the code chained as you outline above.  using hidden might be the one I am after - i will look into that first.
Cheers
Greg J
