### ISSUE TITLE
Webpack Compatibility

### ISSUE THREAD

**Issue by mvastola** [makeusabrew/bootbox#626]
This may be the same issue as #507, but I'm not sure. I'm not able to directly use `bootbox` with webpacker/yarn. When I use the command `import 'bootbox'`, there are no errors, but in the javascript console of the webpage, I get the error, `bootbox is not defined`. 

The only way I'm able to work around this is to instead use `import '../contrib/bootbox-setup'`, where `contrib/bootbox-setup.js` is a script of my own making containing just the line `window.bootbox = require('bootbox');`.

I am happy to provide any additional information needed to help identify/troubleshoot the source of this issue. Please let me know.

**Comment by tiesont** [comment]
I don't use webpacker, so anything you can provide to help me trouble-shoot this would be (very) helpful.

Bootbox is wrapped as a UMD module, so maybe the first two checks are failing, in the context of webpacker? if so, your fix makes sense, since the fallback loader just makes bootbox a global object on the window object.

**Comment by mvastola** [comment]
I just created a minimal example at https://github.com/Partyista/bootbox-issue-626. (Instructions to set it up are in the `README.md`). 

Webpack fully supports both AMD and commonJS, so the checks are working just fine as far as I can tell.. 

Note that I'm renaming this issue. Wepback*er* refers to the integration of `webpack` into `rails`, which -- though what I'm using -- is not related to the issue. My knowledge of javascript when it comes to modules and such is a bit limited, but it seems like the issue is in how the code is exported (by `bootbox`) and then imported (by `webpack`). 

I've also enabled source maps in my example in the hopes that helps somewhat.

**Comment by tiesont** [comment]
@mvastola Sorry, I haven't forgotten about this, I just haven't had a good chance to dig into it. I'll try to do so sometime this week, if you still need this.

**Comment by mvastola** [comment]
Yes, please.

**Comment by tiesont** [comment]
Okay. I'll be honest, I'm primarily a C# developer who just happens to know C/C++, Java, Ruby, JavaScript, etc. well enough to be <s>dangerous</s> <ins>productive when required.</ins> I don't use Node.js for anything at the moment, so it's going to take me some time to debug this. Still working on it, though, as the day jobs allow.

**Comment by mvastola** [comment]
Hah. I totally get it. I'm still fairly new to node.js, or else I'd have more knowledge to share on why this might be broken.

**Comment by LDSign** [comment]
Any news in this? Have you found a "common" way to use Bootbox with Webpack?

**Comment by sifiro** [comment]
Hi another C#/Java Developer here, For me is almost work...
is only add this line in the plugin array in webpack.config.js (and of course, install by npm):
",new webpack.ProvidePlugin({bootbox:"bootbox"})"
and should works buuuuuuuuuuuuuuut 
I have a Exception with "mapArguments" function from bootbox and said "Invalid argument length" while loading.
So... I think is the general issue. so... I am going to looking about that.

**Comment by RyanReedUSE** [comment]
I had this same issue and was able to use the following. It appeared that bootstrap and bootbox were loading in parallel and bootbox was not able to find a function in bootstraps.  

```
import 'bootstrap';
import bootbox from 'bootbox';
```

**Comment by sifiro** [comment]
Hi, I'm here again (I Forgot write here), but my Exception with "mapArguments" was because i did a bootbox.alert(); without any arguments so, for me is working with last solution.

**Comment by tiesont** [comment]
@RyanReedUSE That would make sense, since at it's core Bootbox is nothing but a wrapper around Bootstrap's modal function. @mvastola if you're still trying to make this work, does @RyanReedUSE's comment work for you?

**Comment by mvastola** [comment]
Sorry for the extended delay in dealing with this. @RyanReedUSE's suggestion did not work, but I did just find out how to get this working after researching this anew.

The issue is that anything you import will be scoped locally to the file you're importing it in. The solution to this is to use a plugin called [expose-loader](https://github.com/webpack-contrib/expose-loader#expose-loader). 

To install, simply run `yarn add -D expose-loader` (for `yarn`) or `npm i --save-dev expose-loader` (pure `npm`). 

From there, you can follow the directions in their `[README.md](https://github.com/webpack-contrib/expose-loader#expose-loader)` to configure it in `webpack.config.js`, but the quick and dirty way to to just use `import 'expose-loader?bootbox!bootbox'` in your entry file.

I'll leave this open in case you want to offer these instructions in the `README.md`, but otherwise feel free to close.

**Comment by tiesont** [comment]
@mvastola Okay. I'll add this to the list for getting v5.x released, and add a note to the current docs at some point. Thanks.
