### ISSUE TITLE
Setting className for buttons removes default focus

### ISSUE THREAD

**Issue by dougfinnie** [makeusabrew/bootbox#628]
When setting the className property of a button for a confirm dialog, the default focus is removed.

If className is not set, pressing enter will default to "OK" and run the callback fine, which is my desired action. Removing className and it works.
this works:
`bootbox.confirm({
                    buttons: {
                    confirm: {
                        label: 'Change'
                    },
                    cancel: {
                        label: 'Cancel'
                    }
                },
                    title: 'dialog title',
                    message: 'message',
                    callback: myFunction
                });`
this does not:
`bootbox.confirm({
                    buttons: {
                    confirm: {
                        label: 'Change',
                        className: 'btn-default'
                    },
                    cancel: {
                        label: 'Cancel',
                        className: 'btn-default'
                    }
                },
                    title: 'dialog title',
                    message: 'message',
                    callback: myFunction
                });`

**Comment by tiesont** [comment]
This isn't unexpected - the confirm code looks for a button with a class of "btn-primary" and sets the focus there. Not sure that there was an expectation of someone not having a primary button. Will have to think about how we should handle this case.

**Comment by dougfinnie** [comment]
That makes sense; I tried setting focus after the dialog is shown, but that hasn't worked, but then I'm no JS ninja.
Given the expected behaviour, I won't be offended if you drop this issue :)

Thanks,

**Comment by tiesont** [comment]
Well, it _does_ seem to be a bug, and one that is fixed relatively easily. Just not sure what the official stance on fixing this should be.

**Comment by dougfinnie** [comment]
You've been a great help, many thanks. 
It didn't respect my setting the class to btn-default, but I commented out where it mandates "btn-primary" and it works to the spec I've been given (which is non-standard, but you know...!).

**Comment by tiesont** [comment]
@dougfinnie I added 'bootbox-cancel' and 'bootbox-accept' as classes for the cancel and ok/confirm buttons, respectively, and updated Bootbox to look for those instead on 'btn-primary'. That seems to allow the code to function as-is, and the tests still pass (after updating the class they look for), so that might be a more viable option. I'm not sure if this is something that will make it into the 4.x branch, though. For now, you'd have to use my fork or the v5.x branch after I pull the changes in (not done yet).
