### ISSUE TITLE
bootbox double alert msg ?

### ISSUE THREAD

**Issue by 15838028035** [makeusabrew/bootbox#629]
Hi, I use bootbox for me project,  There are  bug for me,  when i click  delete  button,
the msg 'would you want to delete it ?'  The alert msg is 
(1)would you want to delete it ?
(2)opt okay
(3)would you want to delete it ?

could you can help me ? Next is my code 

```html
<button id="btn_delete" type="button" class="btn btn-default"  onclick="mulDelete();">
    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>delete  
</button>
 ```
```javascript
function mulDelete(){
    bootbox.confirm('would you want to delete it ?',function (result) {  
        if(result) {  
            var ids = $("#parentId").val();
            var result = jQuery.ajax({
                  url:"${ctx}/jsp/user/upmUserGroupAction!multidelete.action?multidelete=" + ids,
                  async:false,
                  cache:false,
                  dataType:"json"
              }).responseText;
            var obj = eval("("+result+")");
            bootbox.alert('opt okay');
            refreshGrid();
        }
    });
}

function refreshGrid(){
    $tableList.bootstrapTable('refresh');
}
```

**Comment by tiesont** [comment]
Is this button in a grid? If so, you are likely repeating your ID values, which is invalid. You also really shouldn't be using the `async: false` option on `$.ajax` - move everything that should happen when the call resolves into the done() callback.

I don't see anything wrong with the Bootbox usage, so there's really nothing for us to fix.

**Comment by 15838028035** [comment]
okay ! thanks !
