### ISSUE TITLE
Feature request: option to choose button to receive focus, or to choose none at all

### ISSUE THREAD

**Issue by 185driver** [makeusabrew/bootbox#632]
Looking through previous issues involving setting the default button to receive focus when the dialog is displayed, I noticed some users would like the option to decide for themselves which button that should be (left one, right one, cancel, ok, close, etc.).  This would be a helpful feature in my view due to the variety of use cases out there.

My own need is somewhat different.  I'm using bootbox primarily on mobile and so prefer that no button receive focus by default. In my experience, it is unusual on mobile to pre-focus a button; doing so creates an unnecessary visual artifact since no keyboard is typically visible for use.

If a property could be added to allow the user to select the default button to receive focus or alternatively none at all, that would be most appreciated.  Thanks for considering.

Using:
bootbox v.4.4.0
bootstrap v.4.0.0-beta
jquery v.3.2.1

**Comment by tiesont** [comment]
I'm not going to implement this, but if you (or someone else) wants to make the effort to create a pull-request, I'd review it and consider merging. I'm ambivalent about the general usefulness of this option, though.

Also, Bootbox 4.x doesn't work as-is with Bootstrap 4, so if that's your target, you would probably want to consider trying the v5 branch, which is a work-in-progress.
