### ISSUE TITLE
onEscape: false not working with confirm

### ISSUE THREAD

**Issue by nodesocket** [makeusabrew/bootbox#634]
Pressing `escape` still closes the modal with:

````javascript
bootbox.confirm({
    message: "Some message here?",
    onEscape: false,
    buttons: {
        confirm: {
            label: "Confirm",
            className: "btn-danger"
        },
        cancel: {
            label: "Cancel"
        }
    },
    callback: function(response) {}
});
````

**Comment by tiesont** [comment]
I think this may actually be more of an error in the documentation (from when I overhauled the site) than a bug in the code. The `onEscape` option works as intended with the custom dialog, but each of the helpers overrides the option value, so it's possible @makeusabrew didn't intended it to applied to anything but the custom dialog. I'll see if I can get some clarification.

**Comment by foofingers** [comment]
<img width="956" alt="Image" src="https://github.com/user-attachments/assets/cf71dbfc-5b2e-4bc5-a4d0-6575e6af3e41" />
