### ISSUE TITLE
Feature request: draggable bootbox

### ISSUE THREAD

**Issue by jeanie77** [makeusabrew/bootbox#636]
Hello, I did a large use of bootbox library in our web application, since I find it very helpful.
Now I need to make all the modals opened with bootbox draggable.
I'm wondering how I could accomplish this task and why [CGeorges pull-request](https://github.com/makeusabrew/bootbox/pull/382) wasn't accepted: was it buggy or wasn't it fully functional maybe? Are there any problems I should be aware of, trying to implement such a feature?
Thanks! :)

**Comment by tiesont** [comment]
It wasn't accepted because I don't find draggable modals to be a feature that needs to be in the library. You're more than welcome to fork this repo and merge that request, if you need that feature.

I'll leave this request open for now, but I don't see this feature being added.
