### ISSUE TITLE
Feature Request: Title Bar Class

### ISSUE THREAD

**Issue by ahmad6242** [makeusabrew/bootbox#637]
I want to show the title of the Box with different colors using the classes of the Bootstrap, Example is shown in the attached image... It is a Good Feature i hope it will be here soon. :) 👍 
![image](https://user-images.githubusercontent.com/12858657/33005819-08a5a1a4-cde1-11e7-9e3f-37e3ca68c61d.png)

**Comment by stvowi** [comment]
good idea e.g. the Contextual Classes for Backgrounds of Twitter Bootstrap : 
http://www.tutorialspark.com/twitterBootstrap/TwitterBootstrap_Contextual_Classes_Background.php

**Comment by tiesont** [comment]
You can already accomplish this by adding your own custom class to the modal (using the `className` option) and apply your own CSS.

**Comment by ahmad6242** [comment]
yes using that className i can apply my own css... But i want to use the Bootstrap class "alert alert-danger/alert alert-success" for the header of the popup, so i don't have to write my own css. That is the sole purpose of using Bootstrap to use the library classes. 
As i have show in the image i want to apply the class only to the header. Maybe that feature you can add later. I am just suggesting you. For now i will use the className and apply my own css.

**Comment by tiesont** [comment]
You can accomplish what you're after using the Sass version of Bootstrap, but I don't see this a useful enough feature to include in Bootbox. If you want to create a pull-request that implements this feature, I would review it and consider pulling it in, but I make no promises.
