### ISSUE TITLE
Modal Title Not Propertly Rendering

### ISSUE THREAD

**Issue by joebetmutia** [makeusabrew/bootbox#642]
Hi guys!

Just want to share Modal Title is not properly rendering in bootstrap4.. 

![image](https://user-images.githubusercontent.com/35093942/34553974-6c467d62-f165-11e7-869f-d86a69feffc9.png)

as for my checking the problem is the close button was rendered first then the modal title.. so i just change

line 631
   dialog.find(".modal-header").prepend(closeButton);

to
   dialog.find(".modal-header").append(closeButton);

now it works.

**Comment by tiesont** [comment]
This has been covered many times already. Please check existing issues before posting a duplicate.

There are a few changes that are required when using Bootstrap 4. See #566.
