### ISSUE TITLE
Fix Title and Close Button in Alert (Bootstrap v4)

### ISSUE THREAD

**Issue by afonsoft** [makeusabrew/bootbox#648]
Alter de Code for put the Close button after de title.

Bootstrap v4.0.0

![code](https://user-images.githubusercontent.com/11299396/36845535-e105a53c-1d35-11e8-89f6-f2d8485bb7c0.jpg)

Image of error and fix after code

![imgerrofix](https://user-images.githubusercontent.com/11299396/36845536-e120b8b8-1d35-11e8-81f7-ab07f489ebbb.jpg)

HTML befor and after alter

![html](https://user-images.githubusercontent.com/11299396/36845723-93662a44-1d36-11e8-9a18-c5c418a33e2a.jpg)

**Comment by JasonGoble** [comment]
Just as an FYI, I was able to make the same change except by changing "prepend" to "append".

**Comment by tiesont** [comment]
See #566 - not going to fix this for 4.x., especially since changes like this would break Bootstrap 3 compatibility.
