### ISSUE TITLE
Screen Reader Support for bootbox.prompt

### ISSUE THREAD

**Issue by jdwill916** [makeusabrew/bootbox#653]
Currently bootbox.prompt() does not include a label tag linked to the input on the screen. This causes issues for screen readers and other accessibility tools, which depend on either a label or a aria-labeled-by to identify the context of the input. Is this in the works to be fixed in a future version?

**Comment by tiesont** [comment]
Currently, no, there isn't really anything being done as far as accessibility is concerned. You can add that to #545 if you want, although I can't guarantee when I'd get to it. Not really looking to add any new functionality to the 4.x branch at this point, unless you want to make the required changes and create a pull-request.
