### ISSUE TITLE
Fill inputOptions for select dynamically 

### ISSUE THREAD

**Issue by allaghi** [makeusabrew/bootbox#654]
I want to use it for filling inputOptions for select dynamically . if there is other way not using vue js . I would be pleasure to tell me

**Comment by tiesont** [comment]
Not sure what you mean by "dynamically." The entire dialog is created from scratch every time you call bootbox.prompt(). If you need to fetch remote options, do so first, and then create the prompt:

```javascript
$.get(url, data)
    .done(function(result){ 
        bootbox.prompt({ 
            // ... other options
            inputOptions: result // assuming result is your options data
        }); 
})
```
