### ISSUE TITLE
Please make modal window draggable

### ISSUE THREAD

**Issue by masch55** [makeusabrew/bootbox#662]
Currently any bootbox cannot be moved from its position. There are circumstances where this is required, because the modal window is hiding information you need to know.

**Comment by tiesont** [comment]
Bootbox modals are, for the most part, dynamically-generated Bootstrap modals. If Bootstrap adds the ability to drag a modal, sure, otherwise, no, I'm not adding this feature.

**Comment by masch55** [comment]
Have you seen the implementation at https://nakupanda.github.io/bootstrap3-dialog/ ? It offers the possibility to drag the dialogs. I'm not sure if it is based on JQuery's draggable function.
