### ISSUE TITLE
Bootstrap 4 is released now...

### ISSUE THREAD

**Issue by RambosRide** [makeusabrew/bootbox#664]
Bootstrap 4 is released now...what are the plans?

**Comment by tiesont** [comment]
Plans are to push the [v5.x branch](https://github.com/makeusabrew/bootbox/tree/v5.x) to master, at some point, which will add some features (see #545), fix some bugs, and make Bootbox compatible with both Bootstrap 3 and Bootstrap 4. Waiting on some feedback from @makeusabrew on some of that, as well as figuring out what needs to be done with some of the external dependencies (like NPM, bower, et cetera) to make sure things aren't being broken by the updated repo structure.

So, I don't have any hard dates for you. Use the v5.x branch if you really want Bootstrap 4 compatibility, or fork the repo and make the changes noted in #566.

**Comment by VictorioBerra** [comment]
Subscribed. I am awaiting this now as well.

**Comment by RambosRide** [comment]
tiesont - thanks for the update. #566 is pretty close to what I found too. - the one thing I'm not 100% on is that breakpoints might be different - my understanding is bootstrap 4 -xs designations are now the "default" for example col-xs-12 in bootstrap3 would now be col-12 in bootstrap 4 and so on.. so not sure if the plugin code would need to change to support that?

**Comment by tiesont** [comment]
> so not sure if the plugin code would need to change to support that?

@RambosRide The [modal markup](https://github.com/makeusabrew/bootbox/blob/v5.x/src/bootbox.js#L75) doesn't include any column markup, so no, that's not relevant or required. I haven't really modified the templates from the current (4.x) version, other than adding a few new templates for new input types (for prompt) and the tweaks needed for the checkbox/radiobutton inputs.

I hope to have 5.x released soon. I don't plan on making any more changes, I just need to make sure I have everything in place before doing the switch-over (pulling the v5.x branch into master is just a small part of that).

**Comment by yannrobin** [comment]
Hello,

Do you have any idea from when the V5 will be pushed on master ?

Thanks

**Comment by tiesont** [comment]
@yannrobin I can push an update to the master branch, but can't really create releases or update any of the third-party things like npm, so I've been holding off.
