### ISSUE TITLE
Close button and modal title in wrong order

### ISSUE THREAD

**Issue by RalphvK** [makeusabrew/bootbox#667]
When using bootbox.js with the latest version of Bootstrap, the close button and modal title are both pushed right, with the close button aligning on the left of the title.

All that is required to fix this, is to place the `<button>` element after the `<h4>`.

**Comment by RalphvK** [comment]
Created a [pull request](https://github.com/makeusabrew/bootbox/pull/668).

**Comment by RalphvK** [comment]
Just read Bootbox v4 doesn't support Bootstrap v4. My apologies for the confusion. I see this change is already implemented on Bootbox v5.

**Comment by tiesont** [comment]
Yeah, sorry, at some point I need to update the README. I have #665 to remind me what needs to be done to make v5 the new master, but I haven't had time to make any progress on the remaining items yet. The code itself isn't going to change, unless someone reports a major bug with v5x, so if you _need_ Bootstrap 4 support, I'd recommend that branch.
