### ISSUE TITLE
Does bootbox support full screen?

### ISSUE THREAD

**Issue by onlinegenerator** [makeusabrew/bootbox#677]
bootbox支持全屏吗

Does bootbox support full screen?

**Comment by tiesont** [comment]
Not sure what you mean by "full screen". If you mean, can the modal expand to more or less fill the viewport, then: there isn't anything built into Bootbox to do that. Bootbox creates Bootstrap modals, though, so if you were to find some CSS or whatnot that makes the modal expand (like this, for instance: https://www.codeply.com/go/DLPXHfEIiS/bootstrap-4-full-screen-modal), you could apply it to any Bootbox modal.
