### ISSUE TITLE
Validate bootbox.prompt() input example?

### ISSUE THREAD

**Issue by aadrian** [makeusabrew/bootbox#679]
Please add an example how to validate the input of the `bootbox.prompt()`.

Thank you.

**Comment by fivem** [comment]
+1

**Comment by tiesont** [comment]
Sure, as soon as someone defines what "validate" means in this context.

**Comment by kadian1470** [comment]
From the example of prompt, how would you validate a string length from a prompt and then display a message in the bootbox saying what is wrong with the string?

**Comment by tiesont** [comment]
In 4.4, there isn't a built-in way to do it. The 5.x branch has a maxlength and required option, which would trigger the browser's built-in validation. 

Assuming this question is for 4.4, I'll work on adding an example of checking the prompt's value, but it will be a little while. The gist is this:

1) Add `return false;` as the last line of the prompt's callback (keeps the modal from closing)
2) Add an if/else statement inside the callback, something like 
    ```js
        if(result && result.length < yourminvaluehere){
            // some code to add an error message
        } else {
            bootbox.hideAll();
        }
   ``` 
3) Where the comment says "// some code...", you might append an error message to `.bootbox-body`, which is a container we add the `.modal-body` when generating the dialogs.

I'll try to add an actual example sometime this weekend.

**Comment by tarlepp** [comment]
also you could easily hook _your_ own logic to that  if needed, it's just some jQuery that you need to do after that modal has been rendered - I have used this way in [this repository](https://github.com/tarlepp/Taskboard) (and really this repository was the thing that I first started to use Bootbox, also just remember that I haven't do anything with that repository for years) a lot to get some custom validations etc. working like I wanted.
