### ISSUE TITLE
Version 4.4.0 with Bootstrap 4.1.3 title incorrect

### ISSUE THREAD

**Issue by uribes78** [makeusabrew/bootbox#681]
I'm using the last bootstrap version and with it show the custom dialog with title parameter is render the title after the close button, so the title is not show correctly

![title-incorrect-position](https://user-images.githubusercontent.com/18754899/46910919-52783680-cf0b-11e8-84b9-f37a474d37c8.png)

**Comment by tiesont** [comment]
This has been reported and noted multiple times already. See #566 for updating 4.4 yourself, if you want that version to work, or use the 5.x branch.
