### ISSUE TITLE
Add ability to customize templates (e.g. similar to `setDefaults` but `setTemplates`)

### ISSUE THREAD

**Issue by niftylettuce** [makeusabrew/bootbox#684]

**Comment by tiesont** [comment]
This _was_ in the roadmap for 5.0 (see #545), but I decided against it for now until I can get the current 5.x branch pushed to master. I definitely want to do something like this for 5.1, but I need to work out how to update things like npm first.

I imagine updating templates to work the same as how locales work in 5.x is really all that's necessary.
