### ISSUE TITLE
Error: Uncaught (in promise) Error: alert requires callback property to be a function when provided

### ISSUE THREAD

**Issue by martinmurciego** [makeusabrew/bootbox#686]
I have an ajax call that runs fine but when the response comes to show in a message, I find this error when I just saved it will show a message that notifies the saved:

![bootbox js error 2018-11-10 11-41-36](https://user-images.githubusercontent.com/7759127/48302628-a3188a80-e4dd-11e8-8ae7-6a41f1e5e153.png)

```
                $.ajax({
                  url: "/reservas/new",
                  type: "POST",
```
...
```
                  success: function(response) {
                        //console.log('response: \n', response);

                        var save = async function () {
                            console.log('response: \n', response);
                            if (! response.error){
                                reservaSaved = response.reserva_id
                                bootbox.alert({
                                    title: '<h4><i class="fa fa-check" style="color:lime;"></i>Agregar Reserva</h4',
                                    message: '<h2>Los datos fueron guardados correctamente!!!</h2>',
                                    size: 'small',
                                    className: 'bb-alternate-modal',
                                    buttons:{
                                        ok:{
                                            label: '<i class="fa fa-check"></i> Aceptar',
                                            className: 'btn-success'
                                        }
                                    },
                                    callback: async function () {
                                            await (window.open("/view/" + reserva_id, '_blank'));
                                            location.reload(true); //recarga pagina desde server en lugar de cache
                                    }
                                });
                            }
                        }
                        save();
                  },
```
...

**Comment by tarlepp** [comment]
You're not providing function as in `callback` you're using `async function() { ... }` which isn't the same.

**Comment by tarlepp** [comment]
That callback expect _function_ and nothing else, sure you could wrap your async / wait like that which is the proper way to do that within bootbox.

But really you're not doing anything that need promise / async handling in your callback. That `window.open` function isn't returning any promise to you, so really using those async / await there is just pointless.

**Comment by martinmurciego** [comment]
any way to read the id retrieved from the server and then open the other page, when it requires the id to open the other page. I did not put the code generated by the pdf with pdfmake, which still requires a callback to put an image in the header of the generated document. And putting callback is not comfortable if I have to put several. In client I have a hard time waiting for something to do, maybe I'll add setTimeOut.

**Comment by tiesont** [comment]
As @tarlepp says, there's not really anything you're doing here where the async/await pattern is all that relevant. You _could_ capture the dialog and then handle it's modal events (`hide.bs.modal` or `hidden.bs.modal`), but I would be surprised if those worked any better - you'd have to consult Bootstrap's documentation to see if the modal plugin works with async/await.

I'll put this on the list of things to investigate for the next release, but at this point I don't really see this as a Bootbox issue. If you can make a case otherwise, we can discuss re-opening the issue.
