### ISSUE TITLE
Possible bug with confirm modal

### ISSUE THREAD

**Issue by jarodium** [makeusabrew/bootbox#692]
Hello,
I have an issue with the confirm method that it is switching the order of the elements ( title is at the right of the close button ) ( see image )

![_bug](https://user-images.githubusercontent.com/1470446/50928086-8fdc5980-1451-11e9-8ab1-fc6f5b03ded8.png)

Bootstrap version: 4.2.1
Booswatch Darkly theme
Bootbox v: 4.4.0

JS code:
`bootbox.confirm({
                 title: "Descarregar sitemap?",
                message: "Deseja descarregar o mapa do site? Pode fazê-lo mais tarde!",
                buttons: {
                    cancel: {
                        label: '<i class="fa fa-times"></i> Não'
                    },
                    confirm: {
                        label: '<i class="fa fa-check"></i> Sim'
                    }
                },
                callback: function (result) {
                    if (result === true) {
                      console.log("ah-ah!");
                    }
                }
            });   `

When I test it on bootbox's website, it works ok but I think this is because of the bootstrap versions.

**Comment by tiesont** [comment]
This has been covered a few times in previous issues - you'll this when using Bootbox 4.x with Bootstrap 4. Issue #566 has my suggestions for making the 4.x version work with Bootstrap 4, plus some suggestions from other users. There is a [5.x branch](https://github.com/makeusabrew/bootbox/tree/v5.x) you can try, although I can't guarantee it's 100% free of bugs.
