### ISSUE TITLE
Question: Version 5.0.0 in NPM

### ISSUE THREAD

**Issue by silentFred** [makeusabrew/bootbox#693]
Hi there,

Really excited to start using the latest version. Was wondering if I was missing something as I cant seem to install version 5.0.0. Has it been published yet?

Cheers,

**Comment by silentFred** [comment]
yarn add makeusabrew/bootbox#v5.0.0
npm install makeusabrew/bootbox#v5.0.0

**Comment by silentFred** [comment]
Anyone actually got this up and running in a angular 2+ app?

**Comment by endelwar** [comment]
I managed to install v5 with yarn using github link
`yarn add https://github.com/makeusabrew/bootbox#v5.0.0`

As stated in https://github.com/makeusabrew/bootbox/issues/665#issuecomment-468511180 @tiesont is trying to contact who manage npm and yarn publication and fix the issue

**Comment by tiesont** [comment]
I was granted admin access to the npm package today, so when I have some time (hopefully very soon) I'll update the package.

This _may_ not work in Angular, given it's (Bootbox's) reliance on jQuery. Haven't tried yet. There's this project: https://github.com/eriktufvesson/ngBootbox

**Comment by tiesont** [comment]
Closed. See #665
