### ISSUE TITLE
IntroJs has a problem with the pop-up box used for bootbox

### ISSUE THREAD

**Issue by sandheart** [makeusabrew/bootbox#696]
IntroJs has a problem with the pop-up box used for bootbox

code:
```
var dialog = bootbox.dialog({
    title: 'A custom dialog with buttons and callbacks',
    message: "<p id='testBtn'>This dialog has buttons. Each button has it's own callback function.</p>",
    size: 'large',
    buttons: {
        cancel: {
            label: "I'm a cancel button!",
            className: 'btn-danger',
            callback: function(){
                console.log('Custom cancel clicked');
            }
        }
    }
});
introJs().setOptions({
    steps: [{
        element: '#testBtn',
        intro: 'asdfaf'
    }]
}).start();
```
![img](https://s2.ax1x.com/2019/03/13/AkKhUU.jpg)

**Comment by tarlepp** [comment]
try to trigger Intro.js start _after_ the dialog has been rendered to DOM

**Comment by sandheart** [comment]
首先感谢您的回复，
现在启动顺序的问题已解决，但还有另外两个问题:
1、引导层出现后，原有的弹层附加了一个class：introjs-fixParent，因z-index属性改变，而被遮挡；
2、引导框因透明度问题，照成内容看不清；
![img1]https://imgchr.com/i/AkQJmt
![img2]https://imgchr.com/i/AkQY0P

**Comment by tarlepp** [comment]
Could you provide working plunker where we could actually see this happening and try to solve your issue there? Also could you keep your comments in English so we could understand you better.

**Comment by sandheart** [comment]
First of all, thank you for your reply.

Now the startup sequence problem has been solved, but there are two other problems:

1. After the appearance of the bootstrap layer, a class was added to the original shell layer: introjs-fixparent, which was occluded due to the change of z-index attribute;

2. The guide box cannot be seen clearly due to the transparency problem;

**Comment by sandheart** [comment]
This is the contrast after modifying class (.introjs-fixparent)

![img3](https://s2.ax1x.com/2019/03/13/Ak3STP.jpg)

![img4](https://s2.ax1x.com/2019/03/13/Ak39Ff.jpg)

**Comment by tiesont** [comment]
I wouldn't classify this as a Bootbox issue, per se, given that we don't have any custom CSS. From just a quick review of Intro.js, I'd say this is an incompatibility with Bootstrap.

**Comment by sandheart** [comment]
Well, then, let's work it out ourselves, thank you

**Comment by tiesont** [comment]
You may find this useful: https://stackoverflow.com/a/28831079/534109

**Comment by tiesont** [comment]
Is this more or less what you're after? http://jsfiddle.net/e0yhg8to/1/

**Comment by sandheart** [comment]
Oh, sorry, that's the question for introjs
