### ISSUE TITLE
 Will this support nested iframe?

### ISSUE THREAD

**Issue by wlm212** [makeusabrew/bootbox#701]
```js
var dialog = bootbox.dialog({
    title: 'A custom dialog with init',
    message: '<p><i class="fa fa-spin fa-spinner"></i> Loading...</p>'
});
            
dialog.init(function(){
    setTimeout(function(){
        dialog.find('.bootbox-body').html('I was loaded after the dialog was shown!');
    }, 3000);
});
```

message 
Can it be a url address?

message：'/user/userinfo.html'

Just like above, load an external html and do the content

**Comment by tiesont** [comment]
This isn't something built into Bootbox, so no, you can't just use a URL. You can (probably) use an iframe as content, since we don't sanitize your `message` value, but that's up to you.
