### ISSUE TITLE
cdnjs latest version is 4.4.0 - no v5

### ISSUE THREAD

**Issue by bradleypatton** [makeusabrew/bootbox#702]
https://cdnjs.com/libraries/bootbox.js/ has versions up 4.4.0. None of the v5 versions are listed there. Any possibility of getting them to pick up the latest versions?

**Comment by tiesont** [comment]
This is noted in #665 - I'm waiting on them to update, which is why the current docs don't have a link to CDNjs.

**Comment by bakbuz** [comment]
please upload to the cdnjs.

**Comment by tiesont** [comment]
@bakbuz That's not how cdnjs works. They pull from the repo. They have not done so yet.

**Comment by tarlepp** [comment]
@bakbuz note that cdnjs should be updated automatically - and for some reason it has not been updated like ~30days - we don't have any "direct" tools for that.

But if you want to help, you could open an issue to cdnjs repository about this issue.

**Comment by tiesont** [comment]
There is an open issue and pull-request to update cdnjs - see https://github.com/cdnjs/cdnjs/issues/13280

**Comment by tiesont** [comment]
Looks like this was finally pulled in: https://cdnjs.com/libraries/bootbox.js. Closing.
