### ISSUE TITLE
Dialog input is not sanitized

### ISSUE THREAD

**Issue by nandafirmans** [makeusabrew/bootbox#707]
I found this issue while auditing npm package. its said that bootbox are vulnerable to Cross-Site Scripting. 
![Annotation 2019-05-23 135238](https://user-images.githubusercontent.com/5415777/58231859-39b5e600-7d62-11e9-894a-443c0060704b.png)

**Comment by tiesont** [comment]
This has been reported before (see https://github.com/makeusabrew/bootbox/issues/683), and I'm aware of that notice and the hackerone report that lead to it. We consider sanitizing input out of scope for Bootbox, as I've noted in the documentation: http://bootboxjs.com/documentation.html#bb-note-html
