### ISSUE TITLE
:first deprecated in jQuery

### ISSUE THREAD

**Issue by andrews05** [makeusabrew/bootbox#708]
Following the deprecation of positional selectors in [jQuery 3.4](https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/), it would be good to replace the use of these with other methods. There seems to be just one use of `:first` which can be replaced with `.first()`.

**Comment by tiesont** [comment]
Fixed in 5.3.4. Not sure if I'll update the 4.x branch, but closing this for now.
