### ISSUE TITLE
setLocale not work

### ISSUE THREAD

**Issue by Shaun-Yao** [makeusabrew/bootbox#712]
I use v5.1.3,  bootbox.setLocale("zh_CN") not work, and bootbox.setDefaults("locale", "zh_CN") aslo not work.

**Comment by tiesont** [comment]
Have you also included bootbox.locales.js? If not, you need to do one of the following:
1. Include bootbox.locales.js or bootbox.locales.min.js
2. Include the relevant locale file (src/locales/zh_CN.js, in this case).
3. Use bootbox.all.js (or bootbox.all.min.js)

bootbox.js only contains the en locale at this point, so you need to include one of the additional files noted above to use anything else.
