### ISSUE TITLE
bootbox set input-textarea height is no effect.

### ISSUE THREAD

**Issue by luckrill** [makeusabrew/bootbox#713]
bootbox set input-textarea height is no effect.

.bootbox-input-textarea {
  height: 300px;
  width: 100%;
}

reasion is bootstrap
before bootstrap/4.1.2, can modify height.
after bootstrap/4.1.3, modify height is no effect.

**Comment by luckrill** [comment]
I use bootbox version is CDN 4.4

**Comment by tiesont** [comment]
The CDN is out-of-date, unfortunately. If you're using Bootstrap 4, you would need to use the 5.x version of Bootbox to be compatible. As for your original issue, a fiddle or similar would be helpful. Otherwise, you'll be waiting until I have time to set up some test cases, which won't be soon.

**Comment by luckrill** [comment]
bootbox set input-textarea height is no effect.

.bootbox-input-textarea {
height: 300px;
width: 100%;
}

reasion is bootstrap
before bootstrap/4.1.2, can modify height.
after bootstrap/4.1.3, modify height is no effect.

for bootbox 5.x.x  or 4.x.x the result is same.

**Comment by luckrill** [comment]
my app at here
http://search.readmorejoy.com/
TellMe and About use bootbox, you can check if you need.

**Comment by tiesont** [comment]
Works for me:

![search-readmorejoy-com](https://user-images.githubusercontent.com/420293/62747409-4a513080-ba22-11e9-8b3b-490dd28a4c48.png)

Is that not what you are seeing? That's not the default height for a textarea, both unstyled and via Bootstrap, so _something_ is changing that. Bootbox doesn't have it's own stylesheet, so something on your end is doing that.
