### ISSUE TITLE
how to set the alert to show it in the middle of the screen?

### ISSUE THREAD

**Issue by david-young-fax** [makeusabrew/bootbox#716]
it always show up at the top of the screen.

**Comment by tarlepp** [comment]
If you look examples - http://bootboxjs.com/examples.html - that isn't the use case.

Could you provide plunker that shows that behaviour?

**Comment by tiesont** [comment]
The default behavior of Bootstrap modals is top of the screen. If you want it vertically centered, you have to set the `centerVertical` option to true, and be using Bootstrap 4.1.3 or greater.
