### ISSUE TITLE
Add Hello Bar (Top Bar) theme

### ISSUE THREAD

**Issue by LukaTCE** [makeusabrew/bootbox#719]
Hi please add hello bar (top bar) theme like.
With button (for website link) and close option. I see BootBox is easy to use if you don't have Wordpress

hellobar.com is not self hosted and it's freemium
Overhang is hard to use
http://paulkr.github.io/overhang.js/

https://www.jqueryscript.net/other/sliding-notification-bar-notify.html
https://www.jqueryscript.net/other/sticky-notification-bar-notif.html

**Comment by tarlepp** [comment]
Not sure how this is related to this library.

**Comment by tiesont** [comment]
Closing as off-topic - all @tarlepp noted, Bootbox does not provide any of it's own styles, so you're free to use whatever you want.
