### ISSUE TITLE
Group CheckAll for inputType: 'checkbox'

### ISSUE THREAD

**Issue by igramnet** [makeusabrew/bootbox#720]
Hey.
I have a request to add a group for checkbox, by clicking on which all the elements of this group would be highlighted.

For example, I have three groups:
The first group includes 10 parameters. And I would like to massively select the parameters of this group and remove the selection.

**Comment by igramnet** [comment]
![image](https://user-images.githubusercontent.com/15707768/64846409-3d24f400-d615-11e9-98c3-dd245120c17f.png)

I have it now. It is not comfortable. I would like there to be an opportunity for each group to tick, when clicked on, the whole group stood out. Something like “Select All for Group”

**Comment by igramnet** [comment]
For exmaple, Select all for Google or select all for Yandex.

**Comment by mikha-lukashevich** [comment]
Hello. @igramnet, nice idea. I would also like to group the data in 2 or 3 columns.

**Comment by igramnet** [comment]
Hey. @tiesont , is this revision worth the wait? If yes, then when? If not, I will look for another solution. Thank.

**Comment by tiesont** [comment]
I won't be implementing this, if that's what you are asking.
