### ISSUE TITLE
Create a Minimize Button in modal

### ISSUE THREAD

**Issue by yaserf2000** [makeusabrew/bootbox#722]
Plaese Add a minimize button side of close button in header bar

**Comment by tiesont** [comment]
Not entirely sure how that would work. These aren't "windows", so there's no taskbar to minimize to. 

I won't close this, but it seems unlikely this will be added.

**Comment by tarlepp** [comment]
Hmm, does Bootstrap modals contain this "Minimize" feature?

**Comment by yaserf2000** [comment]
> Hmm, does Bootstrap modals contain this "Minimize" feature?

No

**Comment by yaserf2000** [comment]
I want to work in this issue

**Comment by tiesont** [comment]
In order for a minimize button to make sense, you need to be able to restore the modal from it's minimized state. As I've already noted, there's no "taskbar" in a website, so not exactly sure how we'd make this work.
