### ISSUE TITLE
height 100% bug on IE 11

### ISSUE THREAD

**Issue by bluedasher13** [makeusabrew/bootbox#724]
Unfortunately, `.modal-dialog { height: 100%; } .modal-content { margin-top: auto; margin-bottom: auto; }` is not working on Windows 7 + IE11, you must add `.modal-dialog { align-items: center; }` style, then it works.

**Comment by tiesont** [comment]
This sounds like you're trying to vertically-center the modal. If that's correct, you need to use the `centerVertical: true` option or manually add the 'modal-dialog-centered` class to the modal. The Bootstrap docs site works just fine, for me: https://getbootstrap.com/docs/4.3/components/modal/#vertically-centered
