### ISSUE TITLE
bootbox.prompt with input type number will not accept decimal value

### ISSUE THREAD

**Issue by morrison999** [makeusabrew/bootbox#727]
bootbox: ^5.3.2
bootbox.prompt: options.step validation

When checking the step value, you use the test expression:
```
if (options.step === 'any' || (!isNaN(options.step) && parseInt(options.step) > 0)) {
              input.attr('step', options.step);
            }
            else {
              throw new Error('"step" must be a valid positive number or the value "any". See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-step for more information.');
            }
```

when checking for a positive step value. This, however, excludes currency where one might like to use 0.01 as the step value. parseInt will return 0 and an exception is thrown.

**Comment by tiesont** [comment]
Seems like out tests should have caught that, but perhaps I only tested whole numbers. Seems easy enough to fix.

**Comment by tiesont** [comment]
Should be fixed now. May take a bit for cdnjs to get updated, but npm is up-to-date.
