### ISSUE TITLE
stacking BS modals

### ISSUE THREAD

**Issue by awheintz** [makeusabrew/bootbox#741]
Not an issue, but more of a Tip:

Without inviting discussions the likes of :
"why would you ever want to create such a UI atrocity?"
I had to find a way to stack modals and with a little change in the bootstrap.js I got it to work:

Search for this code:
```
var doAnimate = Util.supportsTransitionEnd() && animate;
this._backdrop = document.createElement('div');
this._backdrop.className = ClassName.BACKDROP;
```

now insert these lines after it:

```
if(window.navigator.userAgent.indexOf(".NET4")>0){
          this._backdrop.style.zIndex = (1040+($$$1("."+ClassName.BACKDROP).length * 20));
          this._element.style.zIndex = (1050+($$$1("."+ClassName.BACKDROP).length * 20));
} else {
          this._backdrop.style = 'z-index: '+(1040+($$$1("."+ClassName.BACKDROP).length * 20))+";";
          this._element.style = 'z-index: '+(1050+($$$1("."+ClassName.BACKDROP).length * 20))+";";
}
```

And now you can stack modals.
HTH

**Comment by tiesont** [comment]
That's probably a better fit for Bootstrap's issue board, but thank you for taking the time to post it.
