### ISSUE TITLE
[DOCS] Nav-Link for Custom Dialog does not work

### ISSUE THREAD

**Issue by Tilogorn** [makeusabrew/bootbox#743]
When you open http://bootboxjs.com/documentation.html and click on "Custom", you do not get a reaction.

`href="#bb-dialog"` is set on the link while the actual heading is `id="custom-dialog"`

Should be a small fix, chaning it either in the nav or in the heading to the same id.

**Comment by tiesont** [comment]
Fixed. https://github.com/makeusabrew/bootbox/commit/b2e385bf3727ed12b5e65a1a35266744cfac92fe
