### ISSUE TITLE
set z-index 

### ISSUE THREAD

**Issue by liusishan** [makeusabrew/bootbox#748]
How do I set the value of z-index

**Comment by tiesont** [comment]
There's no option for doing that. If you need to tweak the z-index for whatever reason, you pretty much need to do it manually, like you would any other HTML element.

Here's an example:

```javascript
let dialog = bootbox.alert({
    title: 'Some title',
    message: 'Some message'
});

dialog.css({ zIndex: 100 });
```

You can also use the `className` option to add a custom class to the modal, and then add whatever rules you're trying to set:

```javascript
bootbox.alert({
    title: 'Some title',
    message: 'Some message',
    className: 'my-class'
});
```

```css
.my-class
{
    z-index: 100;
}
```

**Comment by liusishan** [comment]
Thank you for your answer, which is very helpful to me

> There's no option for doing that. If you need to tweak the z-index for whatever reason, you pretty much need to do it manually, like you would any other HTML element.
> 
> Here's an example:
> 
> ```js
> let dialog = bootbox.alert({
>     title: 'Some title',
>     message: 'Some message'
> });
> 
> dialog.css({ zIndex: 100 });
> ```
> 
> You can also use the `className` option to add a custom class to the modal, and then add whatever rules you're trying to set:
> 
> ```js
> bootbox.alert({
>     title: 'Some title',
>     message: 'Some message',
>     className: 'my-class'
> });
> ```
> 
> ```css
> .my-class
> {
>     z-index: 100;
> }
> ```

Thank you for your answer, which is very helpful to me
