### ISSUE TITLE
How to use npm package in webpack environment

### ISSUE THREAD

**Issue by hussain1368** [makeusabrew/bootbox#751]
This does not work for me:
`import 'bootstrap';
import bootbox from 'bootbox';
bootbox.alert("Hello world!");`

**Comment by codepushr** [comment]
Same... I'm searching for hours now to make this work in a webpack setup. 

Basically it always fails with: `Error: "$.fn.modal" is not defined; ...`

I tried importing everything:
```js
import $ from "jquery";
import "popper.js";
import "bootstrap";
import bootbox from "bootbox";
...
```
The weird part is that usual BS4 modals work out of the box, so bootstrap.js seems to be imported and working, it's just bootbox that won't work.

Deps:
```
"dependencies": {
    ...
    "bootbox": "^5.4.0",
    "bootstrap": "^4.4.1",
    "jquery": "3.4.1",
    ...
  }
```

**Comment by tiesont** [comment]
I haven't seen @makeusabrew around for quite a while, so you're probably not going to get a response, there. I don't use webpack (or pretty much any package manager), so I'm not sure what help I can be.

If/when I get some time, I'll see what I can figure out, but it might be awhile.

**Comment by tarlepp** [comment]
Something that could help here is to provide some simple repository where this error is happening - just to help other people to jump in without knowing any "details" about that webpack environment itself.

**Comment by harrio** [comment]
I just took bootbox into use in a Webpack project and it works fine right out of the box.
I have the following imports in my entry JS file (actually Typescript...) I guess I took these from some documentation concerning including Bootstrap in general in npm/Webpack.

```javascript
import "jquery";
import "popper.js";
import "bootstrap";
```
And in the file actually using bootbox:
```javascript
import bootbox from "bootbox";
```

**Comment by akheron98** [comment]
I used the suggestion by @harrio and it works in Svelte/Rollup).

**Comment by giero** [comment]
I have also problem with `Error: "$.fn.modal" is not defined; ...`

After some inspections I realized bootbox, since > 5.0, has its own bootstrap and jquery in dependencies and ignores my libraries from package.json. I use Webpack Encore (because it's a Symfony project) with autoProvidejQuery(), but this should not be the case.

In my example
```
package.json
{
  "dependencies": {
    "bootbox": "^5.4.0",
    "bootstrap": "^3.4",
    "jquery": "3.4.1",
  },
```
and in source code
```javascript
import $ from 'jquery';
import 'bootstrap';
import bootbox from 'bootbox';
```
I checked sth like this
```javascript
import $ from 'jquery';
import 'bootstrap';
console.log($.fn.jquery, $.fn.modal);
```
and it's 3.4.1 (as in my package.json) and $.fn.modal is a proper function.

So then I edited bootbox.js in node_modules and added `console.log($.fn.jquery, $.fn.modal);` just after
```javascript
}(this, function init($, undefined) {
  'use strict';

  console.log($.fn.jquery, $.fn.modal);
```
and it's `3.5.1, undefined`. So here's a problem.

**Comment by hussain1368** [comment]
The following worked for me:
`
// webpack.config.js
module.exports = {
    ...
    plugins: [
        new webpack.ProvidePlugin({
           $: "jquery",
           jQuery: "jquery"
       })
    ]
};
`

**Comment by giero** [comment]
@hussain1368 This is exactly what `autoProvidejQuery` does in Encore :)

**Comment by giero** [comment]
I've already created PR solving this issue: https://github.com/makeusabrew/bootbox/pull/759.

To test this I added cloned locally version of Bootbox repo (with peerDepenecies) to my project - no `node_modules` in Bootbox dir and everything worked as well.

**Comment by giero** [comment]
By the way: according to http://bootboxjs.com/getting-started.html#bootbox-dependencies
Bootbox version: 5.x.x (Latest)
Min. Bootstrap version: 3.0.0 / 3.1.0
Max. Bootstrap: 4.x.x
Min. jQuery: 1.9.1

So why in package.json there's:
```
  "dependencies": {
    "bootstrap": "^4.4.0",
    "jquery": "^3.4.1",
    "popper.js": "^1.16.0"
  }
```
?

**Comment by tiesont** [comment]
@giero Those dependencies assume you're loading bootbox et all manually, via script tags. It's more of a compatibility chart than a dependency chart, when it comes down to it.

package.json is updated when I find myself working in a npm environment, which is mostly just when trying to update the documentation or run the test suite prior to accepting a pull-request. That being said (and as I noted somewhere above) I don't generally use npm, so if something's not quite right, I wouldn't be surprised. I've seen you pull-request and I'll try to take some time to review it, unless @tarlepp gets to it first.

**Comment by giero** [comment]
I think it would be a good idea to edit `peerDependencies` in my pull-request to be consist with documentation (for Bootbox 5.x.x):
before: `"bootstrap": "^4.4.0"`
after: `"bootstrap": "^3.1.0 || ^4.4.0"`

**Comment by codepushr** [comment]
Will this get merged any time soon?
