### ISSUE TITLE
 BootboxAsset Not Working with Bootstrap 3.4 Conflict 

### ISSUE THREAD

**Issue by gajendra7590** [makeusabrew/bootbox#752]
BootboxAsset Not Working with Bootstrap 3.4 Conflict everything , i used **Modal**, **Drop-down**, and other  bootstrap JS related things are not working please guide me what to do.

Thanks in advanced

**Comment by tiesont** [comment]
I'm not entirely sure what you're reporting here. Bootbox does work with Bootstrap 3.4. The order in which you load the libraries does matter. See http://bootboxjs.com/getting-started.html#bb-script-order - you don't need Popper.js if you're using Bootstrap 3.x, but everything else is the same.
