### ISSUE TITLE
Can't handle event ‘hide.bs.modal’ right

### ISSUE THREAD

**Issue by felixfb0916** [makeusabrew/bootbox#753]
When ‘hide’ events triggered by children of the current dialog before received event "hide.bs.modal",the code below can't worked right.Due to the use of "one",the listener is "off" :

 dialog.**one**('hide.bs.modal', function (e) {
        if (e.target === this) {
          dialog.off('escape.close.bb');
          dialog.off('click');
        }
    });

**Comment by tiesont** [comment]
This isn't in the [current release](https://github.com/makeusabrew/bootbox/releases/tag/v5.4.0) - what version are you using?

**Comment by felixfb0916** [comment]
v5.3.2

**Comment by tiesont** [comment]
5.4.0 should fix that - I moved that code into a named function, in part to make the built-in handlers works, so `.one()` should respect your custom handler.

You can also do something like

````js
bootbox.alert({
    message: 'I have a handler for the hide event!',
    onHide: function() {
        console.log('hide.bs.modal triggered and handled!');
    }
});
```
