### ISSUE TITLE
Support for BS 4.5?

### ISSUE THREAD

**Issue by VictorioBerra** [makeusabrew/bootbox#755]
BS 4.5 is out now, I noticed there had been some small changes here and there with things like this: https://github.com/twbs/bootstrap/pull/29986

I haven't gotten to test myself yet, but does this support BS 4.5?

**Comment by tiesont** [comment]
Depends on what you mean by "support" - for probably 99% of scenarios, yes, Bootbox will continue to work. I haven't had time to test Bootbox against Bootstrap 4.5, though, so I don't have a better answer for you.

**Comment by tiesont** [comment]
I've upgraded my current project to Bootstrap 4.5 and haven't noticed any issues, so I'm going to close this. If someone finds a bug **related to 4.5** I'll reopen.
