### ISSUE TITLE
Immediate close of a confirm dialog does not work (web testing)

### ISSUE THREAD

**Issue by drauch** [makeusabrew/bootbox#758]
We're using Selenium to execute a web test suite against our applicaiton. These tests also trigger a very fast "cancel" after a confirm dialog is opened via Bootbox.

This works with "default" Bootstrap: https://jsfiddle.net/s4t7dmyq/ notice that the dialog is always hidden.

However, this runs into some kind of race condition with Bootbox: https://jsfiddle.net/gzm3vcLw/ notice that the dialog stays visible although we clicked the cancel button.

If you add some timeout between creating the dialog and clicking the cancel button it works. So there is some kind of race condition (you can comment out the await line in the jsfiddle above to see it working)

My question: is there a definite way for us to determine whether the dialog is fully active and that we can click the cancel button now? We would want to wait for this condition in our Selenium tests.

Best regards,
D.R.

**Comment by drauch** [comment]
Weird side note: the configured callback from the options seems to be called just fine even without a timeout between opening the dialog and clicking the cancel button. It's just that the dialog is not properly closed...

**Comment by drauch** [comment]
Another note: callback is called _before_ onShown - maybe it works only _after_ onShown? Is there a chance to wait for onShown to be finished?

**Comment by tiesont** [comment]
There is _some_ overhead to dynamically creating the modal's markup, which is (to overly simplify) most of what Bootbox does. So, yeah, I'm not entirely surprised that there are timing issues with your tests. There are a few existing issues that basically boil down to the same thing.

Can't say that I have any suggestions for you. Bootbox's codebase isn't all that sophisticated, and I'm not sure what I could do to try to handle what you're describing. Nor do I think I would, to be completely honest - I'd have to see a valid use-case for a real, live person being able to replicate what a testing framework can do before I'd even think about trying to allocate time to look into this.

**Comment by drauch** [comment]
We've implemented a workaround now: we're using the isShown callback to add a class to the dialog and wait for the existence of this class before interacting with the dialog.

Best regards,
D.R.

**Comment by tiesont** [comment]
That's pretty much what I would have suggested. Glad you found a work-around.

Closing. Let me know if you want this re-opened.
