### ISSUE TITLE
Priority order

### ISSUE THREAD

**Issue by rere3091** [makeusabrew/bootbox#763]
Hi,

I wish to know how I can await the user click on bootbox alert and execute after the code and not put the code in the callback option...

In this example -> 

```javascript
var i;
for (i = 0; i < 2; i++) {
  bootbox.alert("Your message here…");

  console.log("test 1");
  console.log("test 2");
}
```

console.log("test 1") and console.log("test 2"); is execute in the same time or before the bootbox alert, and on the screen there are two bootbox alert superimposed... it is problematic for my utility !

I want bootbox alert -> user click -> console.log() -> bootbox alert -> user click -> console.log()

[Capture d’écran 2020-07-23 à 18 52 05](https://user-images.githubusercontent.com/24252289/88315030-1562ea00-cd16-11ea-8b01-432ada2999ed.png)

Best regards.

**Comment by tiesont** [comment]
This is covered in the documentation, both [here](http://bootboxjs.com/documentation.html#bb-note-nonblocking) and on Bootstrap's site. Short answer: **you can't.** Bootstrap modals are asynchronous functions, and most of what Bootbox does is generate Bootstrap modals on the fly.

**Comment by rere3091** [comment]
No, I can, I success to resolve that with Promise command and async function ;)

Best regards.

**Comment by tiesont** [comment]
Promises aren't really going to help you here, but best of luck in your endeavors.

**Comment by tarlepp** [comment]
What you could do is to use custom bootbox dialog and implement your logic there when user clicks some button.
