### ISSUE TITLE
Fix for backdrop not disappearing issue was not included in bootbox.all.js

### ISSUE THREAD

**Issue by michalhalas** [makeusabrew/bootbox#771]
From what I can tell, the issue discussed in #766 and fixed in #767 was only fixed in bootbox.js but not in bootbox.all.js. Using bootbox.all.js replicates said bug again.

**Comment by tiesont** [comment]
Closed in https://github.com/makeusabrew/bootbox/commit/8d8f0394ea7ae25be88c463f75f277651a944465
