### ISSUE TITLE
Dialog size

### ISSUE THREAD

**Issue by vascofor2000** [makeusabrew/bootbox#774]
Hi, 
This probably is not an issue and more an ask for help. I'm using dialog in my program and I want to give seven different buttons to my user to use. The problem is when I name all this buttons they get too big for the size of the box of dialog, I tried to change the size to xl but nothing changed and I don't know if there's another way to do it.
Thank you for your attention.

**Comment by tiesont** [comment]
Using the `xl` size requires version 5 - what version are you using?
