### ISSUE TITLE
Dialog not show in center screen

### ISSUE THREAD

**Issue by GeeSuth** [makeusabrew/bootbox#778]
hey! why dialog not show in center screen (Middle center)
it's showed in top center 
![image](https://user-images.githubusercontent.com/10328974/102817722-55232000-43e1-11eb-9fbf-85df46cafc14.png)

**Comment by tiesont** [comment]
That's how Bootstrap works. If you want to have a vertically centered modal, a) read the documentation, both here and on Bootstrap's site, and b) use the [centerVertical](http://bootboxjs.com/documentation.html#bb-option-centerVertical) option:

```js
bootbox.prompt({
    title: "This is a prompt, vertically centered!", 
    centerVertical: true,
    callback: function(result){ 
        console.log(result); 
    }
});
```

as shown on the Examples page: http://bootboxjs.com/examples.html#prompt-centerVertical
