### ISSUE TITLE
Maximize,move & resize

### ISSUE THREAD

**Issue by carles9000** [makeusabrew/bootbox#780]
Hi,

Do you know if is posible maximized (with button), move and/or resize ? Exist this features?

Thanks and great work
Carles

**Comment by tiesont** [comment]
No, these features do not exist in Bootbox (or Bootstrap, for that matter), nor will they be added.

A quick Google search will show how some developers have had success applying jQuery UI's Draggable plugin, but a) jQuery UI and Bootstrap tend not to work well together - they have conflicting functions, and b) I haven't tried any of them, so I don't know what works and what doesn't.
