### ISSUE TITLE
The server http://bootboxjs.com seems dead?!  not reachable!

### ISSUE THREAD

**Issue by w2know** [makeusabrew/bootbox#781]
The server http://bootboxjs.com is not reachable these days.  Is the project home moved?

**Comment by tiesont** [comment]
Looks like the domain is expired. If you need access to the documentation, I have a slightly out-of-date version here: https://tiesont.github.io/bootbox/documentation.html

**Comment by tiesont** [comment]
@tarlepp Looks like pretty much every domain @makeusabrew owns (or owned) is expired - perhaps a sign to officially move on to a different project?

**Comment by w2know** [comment]
Thanks for the information.  I like this plugin.  It is useful.

**Comment by tiesont** [comment]
Basically, if I can reregister the domain, it will be back up. Until then (and assuming someone doesn't just squat on it), don't hold your breath. I have a version of the docs on the Github-hosted link above, although it's not 100% updated.
