### ISSUE TITLE
Add medium size

### ISSUE THREAD

**Issue by bjarnef** [makeusabrew/bootbox#790]
Currently the following sizes are available: http://bootboxjs.com/documentation.html#bb-option-size

```
Small | 'small', 'sm'
Large | 'large', 'lg'
Extra large | 'extra-large', 'xl'
```

Any reason not to include a `Medium`, `md` size as well.
If seems if not size is set (null) the modal has a medium size by default, but could be useful with this option. Maybe if you wanted to set this dynamically based on a condition or if we could override the default size, e.g. `Large` by default, but in some cases if should be `Medium` size.

**Comment by tiesont** [comment]
The options available are based on the [Bootstrap options](https://getbootstrap.com/docs/4.6/components/modal/#optional-sizes). There would literally be no effect of having a "medium" option
