### ISSUE TITLE
Featue request - Separate input attributes as options in bootbox.prompt

### ISSUE THREAD

**Issue by yhojann-cl** [makeusabrew/bootbox#792]
When use `bootbox.prompt` the input properties are declared in root options object, like as:

```
bootbox.prompt({
    title: "foo",
    placeholder: 'foo',
    class: 'foo',
```

But the input type text prompt is a html input and require other specials attributes, like as:

```
    <input
        class="text-danger"
        type="text"
        placeholder="foo"
        required
        maxlength="255"
        autocomplete="off"
        pattern="[^\\\/:;]+" />
```

But is a bad idea set the input attributes in the root settings. Please, put a dynamic input attributes for the html object, by example:

```
bootbox.prompt({
    title: "foo",
    controls: {
        input: {
            class: 'foo', type: 'text', placeholder: '', required: true, maxlength: 255, autocomplete: 'off', pattern: '...', etc
        }
    },
```

**Comment by tiesont** [comment]
Well, two things:
- The attributes and properties you mentioned can all be set via the options object (except perhaps "autocomplete") - I don't see how your suggestion really improves that, and
- This would be a fairly drastic change to how the prompt template is generated, which equals major version bump, which also equals not likely to happen anytime soon.

A pull-request with your proposed changes, on the other hand, would be more likely to be accepted, assuming it provided tests showing that the existing behavior of prompt stays the same (in other words, the scenarios covered in the current tests must still work).
