### ISSUE TITLE
Incorrect locale code for Brazilian Portuguese

### ISSUE THREAD

**Issue by rossellhayes** [makeusabrew/bootbox#794]
[Available Locales](http://bootboxjs.com/documentation.html#bb-locales) lists `br` as the language code for Brazilian Portuguese, but that is the [ISO 639-1 code for Breton](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=br). Brazilian Portuguese should be assigned the code `pt_BR`.

**Comment by tiesont** [comment]
Fair enough. Not sure when I'll have time to adjust this, but it does make sense to use the correct ISO code.

Pull-requests are welcome, as well.

**Comment by tiesont** [comment]
This will be corrected/updated in v6, which I hope to release soon.

**Comment by tiesont** [comment]
Closed in #820.

Please note that I've normalized the locale codes to what I see in the IANA list, so the new locale would be `pt-BR`.
