### ISSUE TITLE
Modal close button - Bootstrap 5.2x support

### ISSUE THREAD

**Issue by HarpunDK** [makeusabrew/bootbox#814]
Button-close are rendered incorrect. 

For Bootstrap 5.2x support, the following should be correct:
templates.closeButton value: `'<button type="button" class="btn-close bootbox-close-button close" aria-hidden="true"></button>'`,
Bootbox.js (l:94-95)

Instead of: `'<button type="button" class="bootbox-close-button close" aria-hidden="true">&times;</button>,'`

This issue also exists in 5.1x i think.

Let me know if I should create a Pull request. Dont know if compatibility issues with lower versions of Bootstrap, how these are handled.

Thank you for a very nice library

**Comment by tiesont** [comment]
This has been discussed before. For example, in #777 

If you need Bootstrap 5 support, the closest available is the v6-wip branch, which seems to work, but I am still not quite ready to push that to master yet.

**Comment by YashPatkar** [comment]
dd
