### ISSUE TITLE
Title and Close X

### ISSUE THREAD

**Issue by Cytotoxic** [makeusabrew/bootbox#816]
The title is right aligned and the close X floats on the left side of the title length. BS 5.1.3
![bootbox](https://user-images.githubusercontent.com/29076974/189196402-fd127e8b-da5a-4aef-8369-33a9af0acda2.jpg)

**Comment by tiesont** [comment]
This has been covered before - this is what you're going to see using Bootbox 5 with **Bootstrap 5**.

**Comment by Cytotoxic** [comment]
Sorry I am using 6.0.0-wip

**Comment by tiesont** [comment]
@Cytotoxic If you want to provide a reproducible example of this using the v6 branch and Bootstrap 5, I'll reopen the issue. I'm using both in a current project and I do not see what your screenshot demonstrates.

**Comment by Cytotoxic** [comment]
You are correct it worked when building out a test it must be a conflict with something else I am running.

**Comment by tiesont** [comment]
@Cytotoxic Yeah, if you're relying on npm or similar, the v6 branch has not been published anywhere, so it would pull in v5.

**Comment by Cytotoxic** [comment]
@tiesont I found out what just not why it's building the <h5> tag after the <button> tag when it should be building the h5 tag first. But again, not an issue since my bare bones test worked with only necessary files for the test.

**Comment by Cytotoxic** [comment]
@tiesont Actually there is an issue with the ".min" version here is the test: https://jsfiddle.net/kyr8saxt/1/ 

It works when I run the unminified version but not with the minified version of 6.0.0-wip
