### ISSUE TITLE
Is bootbox 6.0.0 really compatible with Bootstrap 5 series?

### ISSUE THREAD

**Issue by yo-nishizawa** [makeusabrew/bootbox#831]
I have tried using bootbox 6.0.0 against bootstrap 5.2.1.
However, I get the following error

"$.fn.modal" is not defined; please double check you have included the Bootstrap JavaScript library.

Are you sure you support bootstrap5 series?
Do you have a solution?

**Comment by yo-nishizawa** [comment]
Sorry, self resolved.

**Comment by umairali** [comment]
@yo-nishizawa how you solved this issue?

**Comment by tiesont** [comment]
@umairali You'll see this error if you don't have jQuery loaded. While Bootstrap 5 doesn't require it, we do.

**Comment by umairali** [comment]
I am loading like below but not working

import $ from 'jquery';
window.$ = window.jQuery = $;

import * as bootstrap from 'bootstrap';
window.bootstrap = bootstrap;

import bootbox from 'bootbox';
window.bootbox = bootbox;

**Comment by tiesont** [comment]
Sorry, not really all that familiar with modules. Bootbox.js has a UMD wrapper, which probably isn't compatible with what you're trying to do.

**Comment by MGeurts** [comment]
@yo-nishizawa how you solved this issue?
