### ISSUE TITLE
Add support for jQuery Deferred/Promise instead of callback

### ISSUE THREAD

**Issue by cmwelsh** [makeusabrew/bootbox#95]
Hello there, I am working on a feature for Bootbox to return promises from each function. That way you don't need to supply the callback as a function parameter. Here is a rundown:
### Acceptance Criteria
1. bootbox.alert returns instance of jQuery.Deferred
2. bootbox.confirm returns instance of jQuery.Deferred
3. bootbox.prompt returns instance of jQuery.Deferred
### Tasks
- Create a new $.Deferred in each function
- Return the $.Deferred().promise() value from each function
### Additional Notes
- None

**Comment by cmwelsh** [comment]
Here is an example with Bluebird:

https://gist.github.com/cmwelsh/fb26c6c82f59b83f80b5

**Comment by avindra** [comment]
@makeusabrew : Have you given much thought to supporting promises natively? Our code base uses `bootbox` and the `callback(data)` signature littered across the code base sticks out like a sore thumb.

**Comment by avindra** [comment]
For others looking for a quick workaround, this is a wrapper for `confirm` that works with Promises (which allows you to use `async/await`):

```js

import { confirm, alert } from 'bootbox'

function wrappedConfirm(options)
{
  return new Promise(resolve =>
    confirm({
      ...options,
      callback : confirmed => resolve(confirmed),
    })
  );
}

export { wrappedConfirm as confirm, alert }
```

**Comment by avindra** [comment]
With proper native support, it should allow zero-callback usage such as  below with `async/await`:

```js
import { confirm, alert } from 'bootbox'

async function demo() {
    const confirmed = await confirm({ title : "Test", message : "Do you agree?" })
    alert('User clicked ' + (confirmed ? 'yes' : 'no')
}

demo();
```

**Comment by sgrannan** [comment]
@avindra are you still using your wrapper and is this compliant with ES5 still? (can't use ES6 Promises)

If so, what does one of your implementations for the confirm look like using the wrapper?

**Comment by avindra** [comment]
The implementation for `confirm` is above. I no longer work at the company where I implemented this but they are surely still using it. 

We were using Babel to transpile the es6 to es5. We were using Google's closure compiler before but that proved to be far too slow for iterating quickly.
